#pragma once

// PlayerUnknown's Battlegrounds (0.27.0) SDK Generated By @IDRAGONCHEATS
namespace SDK
{
//---------------------------------------------------------------------------
//Script Structs
//---------------------------------------------------------------------------

// UserDefinedStruct BP_STRUCT_CHAR_EXP_DETAIL.BP_STRUCT_CHAR_EXP_DETAIL
// 0x0010
struct FBP_STRUCT_CHAR_EXP_DETAIL
{
	int                                                daily_exp_max_0_7294F5400DB4F36174116AE101202598;         // 0x0000(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	int                                                level_1_2C2122401321611B51E413390B555ACC;                 // 0x0004(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	int                                                daily_exp_2_57528C0043D04C143679FD1A0A461110;             // 0x0008(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	int                                                max_level_3_5D7ECB804F01947610FD5AC80C3998AC;             // 0x000C(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
};

}

