#pragma once

// PlayerUnknown's Battlegrounds (0.27.0) SDK Generated By @IDRAGONCHEATS
namespace SDK
{
//---------------------------------------------------------------------------
//Script Structs
//---------------------------------------------------------------------------

// UserDefinedStruct BP_STRUCT_FriendLiteProfile.BP_STRUCT_FriendLiteProfile
// 0x000C
struct FBP_STRUCT_FriendLiteProfile
{
	struct FString                                     gid_0_73C6B800203BCA3C09F24FC105E4BF84;                   // 0x0000(0x000C) (Edit, BlueprintVisible, ZeroConstructor)
};

}

