// PlayerUnknown's Battlegrounds (0.27.0) SDK Generated By @IDRAGONCHEATS
#include "../SDK.hpp"

namespace SDK
{
//---------------------------------------------------------------------------
//Functions
//---------------------------------------------------------------------------

// Function bp_lucky_unback.bp_lucky_unback_C.EventLuckyUnbackEnterFromLobby_NoFetch
// (BlueprintCallable, BlueprintEvent)

void Abp_lucky_unback_C::EventLuckyUnbackEnterFromLobby_NoFetch()
{
	static UFunction *pFunc = 0;
	if (!pFunc)
		pFunc = UObject::FindObject<UFunction>("Function bp_lucky_unback.bp_lucky_unback_C.EventLuckyUnbackEnterFromLobby_NoFetch");

	Abp_lucky_unback_C_EventLuckyUnbackEnterFromLobby_NoFetch_Params params;

	auto flags = pFunc->FunctionFlags;

	UObject *currentObj = (UObject *) this;
	currentObj->ProcessEvent(pFunc, &params);

	pFunc->FunctionFlags = flags;
}

// Function bp_lucky_unback.bp_lucky_unback_C.EventLuckyUnbackEnterFromLobby
// (BlueprintCallable, BlueprintEvent)

void Abp_lucky_unback_C::EventLuckyUnbackEnterFromLobby()
{
	static UFunction *pFunc = 0;
	if (!pFunc)
		pFunc = UObject::FindObject<UFunction>("Function bp_lucky_unback.bp_lucky_unback_C.EventLuckyUnbackEnterFromLobby");

	Abp_lucky_unback_C_EventLuckyUnbackEnterFromLobby_Params params;

	auto flags = pFunc->FunctionFlags;

	UObject *currentObj = (UObject *) this;
	currentObj->ProcessEvent(pFunc, &params);

	pFunc->FunctionFlags = flags;
}

// Function bp_lucky_unback.bp_lucky_unback_C.EventLuckyUnbackSwicthRound_NoFetch
// (BlueprintCallable, BlueprintEvent)

void Abp_lucky_unback_C::EventLuckyUnbackSwicthRound_NoFetch()
{
	static UFunction *pFunc = 0;
	if (!pFunc)
		pFunc = UObject::FindObject<UFunction>("Function bp_lucky_unback.bp_lucky_unback_C.EventLuckyUnbackSwicthRound_NoFetch");

	Abp_lucky_unback_C_EventLuckyUnbackSwicthRound_NoFetch_Params params;

	auto flags = pFunc->FunctionFlags;

	UObject *currentObj = (UObject *) this;
	currentObj->ProcessEvent(pFunc, &params);

	pFunc->FunctionFlags = flags;
}

// Function bp_lucky_unback.bp_lucky_unback_C.EventLuckyUnbackSwicthRound
// (BlueprintCallable, BlueprintEvent)

void Abp_lucky_unback_C::EventLuckyUnbackSwicthRound()
{
	static UFunction *pFunc = 0;
	if (!pFunc)
		pFunc = UObject::FindObject<UFunction>("Function bp_lucky_unback.bp_lucky_unback_C.EventLuckyUnbackSwicthRound");

	Abp_lucky_unback_C_EventLuckyUnbackSwicthRound_Params params;

	auto flags = pFunc->FunctionFlags;

	UObject *currentObj = (UObject *) this;
	currentObj->ProcessEvent(pFunc, &params);

	pFunc->FunctionFlags = flags;
}

// Function bp_lucky_unback.bp_lucky_unback_C.EventLuckyUnbackShowRule_NoFetch
// (BlueprintCallable, BlueprintEvent)

void Abp_lucky_unback_C::EventLuckyUnbackShowRule_NoFetch()
{
	static UFunction *pFunc = 0;
	if (!pFunc)
		pFunc = UObject::FindObject<UFunction>("Function bp_lucky_unback.bp_lucky_unback_C.EventLuckyUnbackShowRule_NoFetch");

	Abp_lucky_unback_C_EventLuckyUnbackShowRule_NoFetch_Params params;

	auto flags = pFunc->FunctionFlags;

	UObject *currentObj = (UObject *) this;
	currentObj->ProcessEvent(pFunc, &params);

	pFunc->FunctionFlags = flags;
}

// Function bp_lucky_unback.bp_lucky_unback_C.EventLuckyUnbackShowRule
// (BlueprintCallable, BlueprintEvent)

void Abp_lucky_unback_C::EventLuckyUnbackShowRule()
{
	static UFunction *pFunc = 0;
	if (!pFunc)
		pFunc = UObject::FindObject<UFunction>("Function bp_lucky_unback.bp_lucky_unback_C.EventLuckyUnbackShowRule");

	Abp_lucky_unback_C_EventLuckyUnbackShowRule_Params params;

	auto flags = pFunc->FunctionFlags;

	UObject *currentObj = (UObject *) this;
	currentObj->ProcessEvent(pFunc, &params);

	pFunc->FunctionFlags = flags;
}

// Function bp_lucky_unback.bp_lucky_unback_C.EventLuckyUnbackHideBubble_NoFetch
// (BlueprintCallable, BlueprintEvent)

void Abp_lucky_unback_C::EventLuckyUnbackHideBubble_NoFetch()
{
	static UFunction *pFunc = 0;
	if (!pFunc)
		pFunc = UObject::FindObject<UFunction>("Function bp_lucky_unback.bp_lucky_unback_C.EventLuckyUnbackHideBubble_NoFetch");

	Abp_lucky_unback_C_EventLuckyUnbackHideBubble_NoFetch_Params params;

	auto flags = pFunc->FunctionFlags;

	UObject *currentObj = (UObject *) this;
	currentObj->ProcessEvent(pFunc, &params);

	pFunc->FunctionFlags = flags;
}

// Function bp_lucky_unback.bp_lucky_unback_C.EventLuckyUnbackHideBubble
// (BlueprintCallable, BlueprintEvent)

void Abp_lucky_unback_C::EventLuckyUnbackHideBubble()
{
	static UFunction *pFunc = 0;
	if (!pFunc)
		pFunc = UObject::FindObject<UFunction>("Function bp_lucky_unback.bp_lucky_unback_C.EventLuckyUnbackHideBubble");

	Abp_lucky_unback_C_EventLuckyUnbackHideBubble_Params params;

	auto flags = pFunc->FunctionFlags;

	UObject *currentObj = (UObject *) this;
	currentObj->ProcessEvent(pFunc, &params);

	pFunc->FunctionFlags = flags;
}

// Function bp_lucky_unback.bp_lucky_unback_C.EventLuckyUnbackShowGet_NoFetch
// (BlueprintCallable, BlueprintEvent)

void Abp_lucky_unback_C::EventLuckyUnbackShowGet_NoFetch()
{
	static UFunction *pFunc = 0;
	if (!pFunc)
		pFunc = UObject::FindObject<UFunction>("Function bp_lucky_unback.bp_lucky_unback_C.EventLuckyUnbackShowGet_NoFetch");

	Abp_lucky_unback_C_EventLuckyUnbackShowGet_NoFetch_Params params;

	auto flags = pFunc->FunctionFlags;

	UObject *currentObj = (UObject *) this;
	currentObj->ProcessEvent(pFunc, &params);

	pFunc->FunctionFlags = flags;
}

// Function bp_lucky_unback.bp_lucky_unback_C.EventLuckyUnbackShowGet
// (BlueprintCallable, BlueprintEvent)

void Abp_lucky_unback_C::EventLuckyUnbackShowGet()
{
	static UFunction *pFunc = 0;
	if (!pFunc)
		pFunc = UObject::FindObject<UFunction>("Function bp_lucky_unback.bp_lucky_unback_C.EventLuckyUnbackShowGet");

	Abp_lucky_unback_C_EventLuckyUnbackShowGet_Params params;

	auto flags = pFunc->FunctionFlags;

	UObject *currentObj = (UObject *) this;
	currentObj->ProcessEvent(pFunc, &params);

	pFunc->FunctionFlags = flags;
}

// Function bp_lucky_unback.bp_lucky_unback_C.EventLuckyUnbackShowSurprise_NoFetch
// (BlueprintCallable, BlueprintEvent)

void Abp_lucky_unback_C::EventLuckyUnbackShowSurprise_NoFetch()
{
	static UFunction *pFunc = 0;
	if (!pFunc)
		pFunc = UObject::FindObject<UFunction>("Function bp_lucky_unback.bp_lucky_unback_C.EventLuckyUnbackShowSurprise_NoFetch");

	Abp_lucky_unback_C_EventLuckyUnbackShowSurprise_NoFetch_Params params;

	auto flags = pFunc->FunctionFlags;

	UObject *currentObj = (UObject *) this;
	currentObj->ProcessEvent(pFunc, &params);

	pFunc->FunctionFlags = flags;
}

// Function bp_lucky_unback.bp_lucky_unback_C.EventLuckyUnbackShowSurprise
// (BlueprintCallable, BlueprintEvent)

void Abp_lucky_unback_C::EventLuckyUnbackShowSurprise()
{
	static UFunction *pFunc = 0;
	if (!pFunc)
		pFunc = UObject::FindObject<UFunction>("Function bp_lucky_unback.bp_lucky_unback_C.EventLuckyUnbackShowSurprise");

	Abp_lucky_unback_C_EventLuckyUnbackShowSurprise_Params params;

	auto flags = pFunc->FunctionFlags;

	UObject *currentObj = (UObject *) this;
	currentObj->ProcessEvent(pFunc, &params);

	pFunc->FunctionFlags = flags;
}

// Function bp_lucky_unback.bp_lucky_unback_C.EventLuckyUnbackClose_NoFetch
// (BlueprintCallable, BlueprintEvent)

void Abp_lucky_unback_C::EventLuckyUnbackClose_NoFetch()
{
	static UFunction *pFunc = 0;
	if (!pFunc)
		pFunc = UObject::FindObject<UFunction>("Function bp_lucky_unback.bp_lucky_unback_C.EventLuckyUnbackClose_NoFetch");

	Abp_lucky_unback_C_EventLuckyUnbackClose_NoFetch_Params params;

	auto flags = pFunc->FunctionFlags;

	UObject *currentObj = (UObject *) this;
	currentObj->ProcessEvent(pFunc, &params);

	pFunc->FunctionFlags = flags;
}

// Function bp_lucky_unback.bp_lucky_unback_C.EventLuckyUnbackClose
// (BlueprintCallable, BlueprintEvent)

void Abp_lucky_unback_C::EventLuckyUnbackClose()
{
	static UFunction *pFunc = 0;
	if (!pFunc)
		pFunc = UObject::FindObject<UFunction>("Function bp_lucky_unback.bp_lucky_unback_C.EventLuckyUnbackClose");

	Abp_lucky_unback_C_EventLuckyUnbackClose_Params params;

	auto flags = pFunc->FunctionFlags;

	UObject *currentObj = (UObject *) this;
	currentObj->ProcessEvent(pFunc, &params);

	pFunc->FunctionFlags = flags;
}

// Function bp_lucky_unback.bp_lucky_unback_C.EventLuckyUnbackShowRate_NoFetch
// (BlueprintCallable, BlueprintEvent)

void Abp_lucky_unback_C::EventLuckyUnbackShowRate_NoFetch()
{
	static UFunction *pFunc = 0;
	if (!pFunc)
		pFunc = UObject::FindObject<UFunction>("Function bp_lucky_unback.bp_lucky_unback_C.EventLuckyUnbackShowRate_NoFetch");

	Abp_lucky_unback_C_EventLuckyUnbackShowRate_NoFetch_Params params;

	auto flags = pFunc->FunctionFlags;

	UObject *currentObj = (UObject *) this;
	currentObj->ProcessEvent(pFunc, &params);

	pFunc->FunctionFlags = flags;
}

// Function bp_lucky_unback.bp_lucky_unback_C.EventLuckyUnbackShowRate
// (BlueprintCallable, BlueprintEvent)

void Abp_lucky_unback_C::EventLuckyUnbackShowRate()
{
	static UFunction *pFunc = 0;
	if (!pFunc)
		pFunc = UObject::FindObject<UFunction>("Function bp_lucky_unback.bp_lucky_unback_C.EventLuckyUnbackShowRate");

	Abp_lucky_unback_C_EventLuckyUnbackShowRate_Params params;

	auto flags = pFunc->FunctionFlags;

	UObject *currentObj = (UObject *) this;
	currentObj->ProcessEvent(pFunc, &params);

	pFunc->FunctionFlags = flags;
}

// Function bp_lucky_unback.bp_lucky_unback_C.EventLuckyUnbackExchangeClick_NoFetch
// (BlueprintCallable, BlueprintEvent)

void Abp_lucky_unback_C::EventLuckyUnbackExchangeClick_NoFetch()
{
	static UFunction *pFunc = 0;
	if (!pFunc)
		pFunc = UObject::FindObject<UFunction>("Function bp_lucky_unback.bp_lucky_unback_C.EventLuckyUnbackExchangeClick_NoFetch");

	Abp_lucky_unback_C_EventLuckyUnbackExchangeClick_NoFetch_Params params;

	auto flags = pFunc->FunctionFlags;

	UObject *currentObj = (UObject *) this;
	currentObj->ProcessEvent(pFunc, &params);

	pFunc->FunctionFlags = flags;
}

// Function bp_lucky_unback.bp_lucky_unback_C.EventLuckyUnbackExchangeClick
// (BlueprintCallable, BlueprintEvent)

void Abp_lucky_unback_C::EventLuckyUnbackExchangeClick()
{
	static UFunction *pFunc = 0;
	if (!pFunc)
		pFunc = UObject::FindObject<UFunction>("Function bp_lucky_unback.bp_lucky_unback_C.EventLuckyUnbackExchangeClick");

	Abp_lucky_unback_C_EventLuckyUnbackExchangeClick_Params params;

	auto flags = pFunc->FunctionFlags;

	UObject *currentObj = (UObject *) this;
	currentObj->ProcessEvent(pFunc, &params);

	pFunc->FunctionFlags = flags;
}

// Function bp_lucky_unback.bp_lucky_unback_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void Abp_lucky_unback_C::UserConstructionScript()
{
	static UFunction *pFunc = 0;
	if (!pFunc)
		pFunc = UObject::FindObject<UFunction>("Function bp_lucky_unback.bp_lucky_unback_C.UserConstructionScript");

	Abp_lucky_unback_C_UserConstructionScript_Params params;

	auto flags = pFunc->FunctionFlags;

	UObject *currentObj = (UObject *) this;
	currentObj->ProcessEvent(pFunc, &params);

	pFunc->FunctionFlags = flags;
}

}

