#pragma once

// PlayerUnknown's Battlegrounds (0.27.0) SDK Generated By @IDRAGONCHEATS
namespace SDK
{
//---------------------------------------------------------------------------
//Script Structs
//---------------------------------------------------------------------------

// UserDefinedStruct BP_STRUCT_RADAR.BP_STRUCT_RADAR
// 0x00A0
struct FBP_STRUCT_RADAR
{
	struct FString                                     HurtScore_s_0_C8663AFA442DFA6D8AA13388C1C55A0C;           // 0x0000(0x000C) (Edit, BlueprintVisible, ZeroConstructor)
	float                                              KillScore_f_1_37CE787D429CD88433879EA2CD7452E9;           // 0x000C(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	int                                                KillScore_2_3DE6CB244A13B693BA715FAF9A164A5D;             // 0x0010(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	int                                                HurtScore_3_B58A1965434B582FB7F70F8272DC4F24;             // 0x0014(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	float                                              SupportScore_f_4_6025AD594F590D4C08FD19AF140195A9;        // 0x0018(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	struct FString                                     SupportScore_s_5_846B96624E6248D1986C81A21A454012;        // 0x001C(0x000C) (Edit, BlueprintVisible, ZeroConstructor)
	struct FString                                     KillScore_s_6_1F09B75C49829431658E5692025DFF05;           // 0x0028(0x000C) (Edit, BlueprintVisible, ZeroConstructor)
	float                                              HurtScore_f_7_41CA91F84AF8492A8E10EE987189E51B;           // 0x0034(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	struct FString                                     SupplyScore_s_8_80DA3D8A473E51C7D8B6E08FC1DA2DAF;         // 0x0038(0x000C) (Edit, BlueprintVisible, ZeroConstructor)
	int                                                SupplyScore_9_ACE09E574E567E59B849DDB2389C4A67;           // 0x0044(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	struct FString                                     SurviveScore_s_10_75CA592D4A358A6834C7C396AE33B5C3;       // 0x0048(0x000C) (Edit, BlueprintVisible, ZeroConstructor)
	int                                                SurviveScore_11_EC99DC8F4225291789D8D8B8051AAE47;         // 0x0054(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	int                                                SupportScore_12_B0470C484AF0DDE4396E8297B89F2367;         // 0x0058(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	float                                              SupplyScore_f_13_0E7D68A04133FFDFA4E6D8A84E9DF371;        // 0x005C(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	float                                              SurviveScore_f_14_9FF7DA184864ED54B14581A20BE48DB3;       // 0x0060(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	int                                                MonsterHeadShotScore_15_53B214C03A9272856EE0DFCA0C1C3AE5; // 0x0064(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	int                                                MonsterDamageScore_16_6994A0802279027C70E75E2A0817D7D5;   // 0x0068(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	int                                                MonsterKillScore_17_515033C07651DA917CFD2768013C6355;     // 0x006C(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	float                                              MonsterKillScore_f_18_7CB9C50019E225AE31B15ECB0C635C66;   // 0x0070(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	float                                              MonsterHeadShotScore_f_19_3D9AA6006FDE193A55DFE9070C3AE746;// 0x0074(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	struct FString                                     MonsterDamageScore_s_20_7A6675005287F9984B0BD29007D7D373; // 0x0078(0x000C) (Edit, BlueprintVisible, ZeroConstructor)
	float                                              MonsterDamageScore_f_21_7A5971C05287F98B4B0BD28507D7D346; // 0x0084(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	struct FString                                     MonsterHeadShotScore_s_22_3DA7A9406FDE194755DFE9320C3AE773;// 0x0088(0x000C) (Edit, BlueprintVisible, ZeroConstructor)
	struct FString                                     MonsterKillScore_s_23_7CC6C84019E225BB31B15EF60C635C53;   // 0x0094(0x000C) (Edit, BlueprintVisible, ZeroConstructor)
};

}

