#pragma once

// PlayerUnknown's Battlegrounds (0.27.0) SDK Generated By @IDRAGONCHEATS
namespace SDK
{
//---------------------------------------------------------------------------
//Script Structs
//---------------------------------------------------------------------------

// UserDefinedStruct BP_STRUCT_BattleText_type.BP_STRUCT_BattleText_type
// 0x0010
struct FBP_STRUCT_BattleText_type
{
	struct FString                                     BattleTextValue_0_C862B6A74DAE6AFFE016F7A75B08BB2E;       // 0x0000(0x000C) (Edit, BlueprintVisible, ZeroConstructor)
	int                                                BattleTextId_1_B87A149F450B53DA84777BAED491366B;          // 0x000C(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
};

}

