#pragma once

// PlayerUnknown's Battlegrounds (0.26.0) SDK Generated By @IDRAGONCHEATS
#include "../SDK.hpp"

namespace SDK
{
//---------------------------------------------------------------------------
//Parameters
//---------------------------------------------------------------------------

// Function LobbySaveGame.LobbySaveGame_C.LoadData
struct ULobbySaveGame_C_LoadData_Params
{
	class USaveGame*                                   ReturnValue;                                              // (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData)
};

// Function LobbySaveGame.LobbySaveGame_C.SaveData
struct ULobbySaveGame_C_SaveData_Params
{
	bool                                               SaveDataState;                                            // (Parm, OutParm, ZeroConstructor, IsPlainOldData)
};

}

