#pragma once

// PlayerUnknown's Battlegrounds (0.27.0) SDK Generated By @IDRAGONCHEATS
namespace SDK
{
//---------------------------------------------------------------------------
//Script Structs
//---------------------------------------------------------------------------

// UserDefinedStruct BP_STRUCT_GroupType.BP_STRUCT_GroupType
// 0x0010
struct FBP_STRUCT_GroupType
{
	int                                                Type_0_CBFD22254E63190A4C378883A34F578A;                  // 0x0000(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	struct FString                                     GroupName_1_BE8E18014255CDFD210E869660F8D850;             // 0x0004(0x000C) (Edit, BlueprintVisible, ZeroConstructor)
};

}

