#pragma once

// PlayerUnknown's Battlegrounds (0.27.0) SDK Generated By @IDRAGONCHEATS
#include "../SDK.hpp"

namespace SDK
{
//---------------------------------------------------------------------------
//Parameters
//---------------------------------------------------------------------------

// Function bp_corps_base.bp_corps_base_C.EventOnSelectIndex_NoFetch
struct Abp_corps_base_C_EventOnSelectIndex_NoFetch_Params
{
};

// Function bp_corps_base.bp_corps_base_C.EventOnSelectIndex
struct Abp_corps_base_C_EventOnSelectIndex_Params
{
};

// Function bp_corps_base.bp_corps_base_C.EventCorpsClose_NoFetch
struct Abp_corps_base_C_EventCorpsClose_NoFetch_Params
{
};

// Function bp_corps_base.bp_corps_base_C.EventCorpsClose
struct Abp_corps_base_C_EventCorpsClose_Params
{
};

// Function bp_corps_base.bp_corps_base_C.EventOnAfterHide_NoFetch
struct Abp_corps_base_C_EventOnAfterHide_NoFetch_Params
{
};

// Function bp_corps_base.bp_corps_base_C.EventOnAfterHide
struct Abp_corps_base_C_EventOnAfterHide_Params
{
};

// Function bp_corps_base.bp_corps_base_C.EventCorpsOnAfterShow_NoFetch
struct Abp_corps_base_C_EventCorpsOnAfterShow_NoFetch_Params
{
};

// Function bp_corps_base.bp_corps_base_C.EventCorpsOnAfterShow
struct Abp_corps_base_C_EventCorpsOnAfterShow_Params
{
};

// Function bp_corps_base.bp_corps_base_C.UserConstructionScript
struct Abp_corps_base_C_UserConstructionScript_Params
{
};

}

