#pragma once

// PlayerUnknown's Battlegrounds (0.27.0) SDK Generated By @IDRAGONCHEATS
#include "../SDK.hpp"

namespace SDK
{
//---------------------------------------------------------------------------
//Parameters
//---------------------------------------------------------------------------

// Function bp_lucky_unback.bp_lucky_unback_C.EventLuckyUnbackEnterFromLobby_NoFetch
struct Abp_lucky_unback_C_EventLuckyUnbackEnterFromLobby_NoFetch_Params
{
};

// Function bp_lucky_unback.bp_lucky_unback_C.EventLuckyUnbackEnterFromLobby
struct Abp_lucky_unback_C_EventLuckyUnbackEnterFromLobby_Params
{
};

// Function bp_lucky_unback.bp_lucky_unback_C.EventLuckyUnbackSwicthRound_NoFetch
struct Abp_lucky_unback_C_EventLuckyUnbackSwicthRound_NoFetch_Params
{
};

// Function bp_lucky_unback.bp_lucky_unback_C.EventLuckyUnbackSwicthRound
struct Abp_lucky_unback_C_EventLuckyUnbackSwicthRound_Params
{
};

// Function bp_lucky_unback.bp_lucky_unback_C.EventLuckyUnbackShowRule_NoFetch
struct Abp_lucky_unback_C_EventLuckyUnbackShowRule_NoFetch_Params
{
};

// Function bp_lucky_unback.bp_lucky_unback_C.EventLuckyUnbackShowRule
struct Abp_lucky_unback_C_EventLuckyUnbackShowRule_Params
{
};

// Function bp_lucky_unback.bp_lucky_unback_C.EventLuckyUnbackHideBubble_NoFetch
struct Abp_lucky_unback_C_EventLuckyUnbackHideBubble_NoFetch_Params
{
};

// Function bp_lucky_unback.bp_lucky_unback_C.EventLuckyUnbackHideBubble
struct Abp_lucky_unback_C_EventLuckyUnbackHideBubble_Params
{
};

// Function bp_lucky_unback.bp_lucky_unback_C.EventLuckyUnbackShowGet_NoFetch
struct Abp_lucky_unback_C_EventLuckyUnbackShowGet_NoFetch_Params
{
};

// Function bp_lucky_unback.bp_lucky_unback_C.EventLuckyUnbackShowGet
struct Abp_lucky_unback_C_EventLuckyUnbackShowGet_Params
{
};

// Function bp_lucky_unback.bp_lucky_unback_C.EventLuckyUnbackShowSurprise_NoFetch
struct Abp_lucky_unback_C_EventLuckyUnbackShowSurprise_NoFetch_Params
{
};

// Function bp_lucky_unback.bp_lucky_unback_C.EventLuckyUnbackShowSurprise
struct Abp_lucky_unback_C_EventLuckyUnbackShowSurprise_Params
{
};

// Function bp_lucky_unback.bp_lucky_unback_C.EventLuckyUnbackClose_NoFetch
struct Abp_lucky_unback_C_EventLuckyUnbackClose_NoFetch_Params
{
};

// Function bp_lucky_unback.bp_lucky_unback_C.EventLuckyUnbackClose
struct Abp_lucky_unback_C_EventLuckyUnbackClose_Params
{
};

// Function bp_lucky_unback.bp_lucky_unback_C.EventLuckyUnbackShowRate_NoFetch
struct Abp_lucky_unback_C_EventLuckyUnbackShowRate_NoFetch_Params
{
};

// Function bp_lucky_unback.bp_lucky_unback_C.EventLuckyUnbackShowRate
struct Abp_lucky_unback_C_EventLuckyUnbackShowRate_Params
{
};

// Function bp_lucky_unback.bp_lucky_unback_C.EventLuckyUnbackExchangeClick_NoFetch
struct Abp_lucky_unback_C_EventLuckyUnbackExchangeClick_NoFetch_Params
{
};

// Function bp_lucky_unback.bp_lucky_unback_C.EventLuckyUnbackExchangeClick
struct Abp_lucky_unback_C_EventLuckyUnbackExchangeClick_Params
{
};

// Function bp_lucky_unback.bp_lucky_unback_C.UserConstructionScript
struct Abp_lucky_unback_C_UserConstructionScript_Params
{
};

}

