#pragma once

// PlayerUnknown's Battlegrounds (0.27.0) SDK Generated By @IDRAGONCHEATS
namespace SDK
{
//---------------------------------------------------------------------------
//Classes
//---------------------------------------------------------------------------

// Class ReplicationGraph.ReplicationGraph
// 0x0230 (0x0250 - 0x0020)
class UReplicationGraph : public UReplicationDriver
{
public:
	class UNetDriver*                                  NetDriver;                                                // 0x0020(0x0004) (ZeroConstructor, IsPlainOldData)
	TArray<class UNetReplicationGraphConnection*>      Connections;                                              // 0x0024(0x000C) (ZeroConstructor)
	TArray<class UNetReplicationGraphConnection*>      PendingConnections;                                       // 0x0030(0x000C) (ZeroConstructor)
	unsigned char                                      UnknownData00[0x30];                                      // 0x003C(0x0030) MISSED OFFSET
	TArray<class UReplicationGraphNode*>               GlobalGraphNodes;                                         // 0x006C(0x000C) (ZeroConstructor)
	TArray<class UReplicationGraphNode*>               PrepareForReplicationNodes;                               // 0x0078(0x000C) (ZeroConstructor)
	unsigned char                                      UnknownData01[0x1CC];                                     // 0x0084(0x01CC) MISSED OFFSET

	static UClass* StaticClass()
	{
		static UClass *pStaticClass = 0;
		if (!pStaticClass)
			 pStaticClass = UObject::FindClass("Class ReplicationGraph.ReplicationGraph");
		return pStaticClass;
	}

};


// Class ReplicationGraph.ReplicationGraphNode
// 0x001C (0x0038 - 0x001C)
class UReplicationGraphNode : public UObject
{
public:
	unsigned char                                      UnknownData00[0x1C];                                      // 0x001C(0x001C) MISSED OFFSET

	static UClass* StaticClass()
	{
		static UClass *pStaticClass = 0;
		if (!pStaticClass)
			 pStaticClass = UObject::FindClass("Class ReplicationGraph.ReplicationGraphNode");
		return pStaticClass;
	}

};


// Class ReplicationGraph.ReplicationGraphNode_ActorList
// 0x0080 (0x00B8 - 0x0038)
class UReplicationGraphNode_ActorList : public UReplicationGraphNode
{
public:
	unsigned char                                      UnknownData00[0x80];                                      // 0x0038(0x0080) MISSED OFFSET

	static UClass* StaticClass()
	{
		static UClass *pStaticClass = 0;
		if (!pStaticClass)
			 pStaticClass = UObject::FindClass("Class ReplicationGraph.ReplicationGraphNode_ActorList");
		return pStaticClass;
	}

};


// Class ReplicationGraph.ReplicationGraphNode_AlwaysRelevant_ForConnection
// 0x0028 (0x00E0 - 0x00B8)
class UReplicationGraphNode_AlwaysRelevant_ForConnection : public UReplicationGraphNode_ActorList
{
public:
	unsigned char                                      UnknownData00[0x10];                                      // 0x00B8(0x0010) MISSED OFFSET
	TArray<struct FAlwaysRelevantActorInfo>            PastRelevantActors;                                       // 0x00C8(0x000C) (ZeroConstructor)
	class AActor*                                      LastViewer;                                               // 0x00D4(0x0004) (ZeroConstructor, IsPlainOldData)
	class AActor*                                      LastViewTarget;                                           // 0x00D8(0x0004) (ZeroConstructor, IsPlainOldData)
	unsigned char                                      UnknownData01[0x4];                                       // 0x00DC(0x0004) MISSED OFFSET

	static UClass* StaticClass()
	{
		static UClass *pStaticClass = 0;
		if (!pStaticClass)
			 pStaticClass = UObject::FindClass("Class ReplicationGraph.ReplicationGraphNode_AlwaysRelevant_ForConnection");
		return pStaticClass;
	}

};


// Class ReplicationGraph.BasicReplicationGraph
// 0x0020 (0x0270 - 0x0250)
class UBasicReplicationGraph : public UReplicationGraph
{
public:
	class UReplicationGraphNode_GridSpatialization2D*  GridNode;                                                 // 0x0250(0x0004) (ZeroConstructor, IsPlainOldData)
	class UReplicationGraphNode_ActorList*             AlwaysRelevantNode;                                       // 0x0254(0x0004) (ZeroConstructor, IsPlainOldData)
	TArray<struct FConnectionAlwaysRelevantNodePair>   AlwaysRelevantForConnectionList;                          // 0x0258(0x000C) (ZeroConstructor)
	TArray<class AActor*>                              ActorsWithoutNetConnection;                               // 0x0264(0x000C) (ZeroConstructor)

	static UClass* StaticClass()
	{
		static UClass *pStaticClass = 0;
		if (!pStaticClass)
			 pStaticClass = UObject::FindClass("Class ReplicationGraph.BasicReplicationGraph");
		return pStaticClass;
	}

};


// Class ReplicationGraph.ReplicationGraphNode_ActorListFrequencyBuckets
// 0x00A8 (0x00E0 - 0x0038)
class UReplicationGraphNode_ActorListFrequencyBuckets : public UReplicationGraphNode
{
public:
	unsigned char                                      UnknownData00[0xA8];                                      // 0x0038(0x00A8) MISSED OFFSET

	static UClass* StaticClass()
	{
		static UClass *pStaticClass = 0;
		if (!pStaticClass)
			 pStaticClass = UObject::FindClass("Class ReplicationGraph.ReplicationGraphNode_ActorListFrequencyBuckets");
		return pStaticClass;
	}

};


// Class ReplicationGraph.ReplicationGraphNode_ConnectionDormanyNode
// 0x0078 (0x0130 - 0x00B8)
class UReplicationGraphNode_ConnectionDormanyNode : public UReplicationGraphNode_ActorList
{
public:
	unsigned char                                      UnknownData00[0x78];                                      // 0x00B8(0x0078) MISSED OFFSET

	static UClass* StaticClass()
	{
		static UClass *pStaticClass = 0;
		if (!pStaticClass)
			 pStaticClass = UObject::FindClass("Class ReplicationGraph.ReplicationGraphNode_ConnectionDormanyNode");
		return pStaticClass;
	}

};


// Class ReplicationGraph.ReplicationGraphNode_DormancyNode
// 0x0040 (0x00F8 - 0x00B8)
class UReplicationGraphNode_DormancyNode : public UReplicationGraphNode_ActorList
{
public:
	unsigned char                                      UnknownData00[0x40];                                      // 0x00B8(0x0040) MISSED OFFSET

	static UClass* StaticClass()
	{
		static UClass *pStaticClass = 0;
		if (!pStaticClass)
			 pStaticClass = UObject::FindClass("Class ReplicationGraph.ReplicationGraphNode_DormancyNode");
		return pStaticClass;
	}

};


// Class ReplicationGraph.ReplicationGraphNode_GridCell
// 0x0068 (0x0120 - 0x00B8)
class UReplicationGraphNode_GridCell : public UReplicationGraphNode_ActorList
{
public:
	unsigned char                                      UnknownData00[0x58];                                      // 0x00B8(0x0058) MISSED OFFSET
	class UReplicationGraphNode*                       DynamicNode;                                              // 0x0110(0x0004) (ZeroConstructor, IsPlainOldData)
	class UReplicationGraphNode_DormancyNode*          DormancyNode;                                             // 0x0114(0x0004) (ZeroConstructor, IsPlainOldData)
	unsigned char                                      UnknownData01[0x8];                                       // 0x0118(0x0008) MISSED OFFSET

	static UClass* StaticClass()
	{
		static UClass *pStaticClass = 0;
		if (!pStaticClass)
			 pStaticClass = UObject::FindClass("Class ReplicationGraph.ReplicationGraphNode_GridCell");
		return pStaticClass;
	}

};


// Class ReplicationGraph.ReplicationGraphNode_GridSpatialization2D
// 0x0138 (0x0170 - 0x0038)
class UReplicationGraphNode_GridSpatialization2D : public UReplicationGraphNode
{
public:
	unsigned char                                      UnknownData00[0x138];                                     // 0x0038(0x0138) MISSED OFFSET

	static UClass* StaticClass()
	{
		static UClass *pStaticClass = 0;
		if (!pStaticClass)
			 pStaticClass = UObject::FindClass("Class ReplicationGraph.ReplicationGraphNode_GridSpatialization2D");
		return pStaticClass;
	}

};


// Class ReplicationGraph.ReplicationGraphNode_AlwaysRelevant
// 0x0010 (0x0048 - 0x0038)
class UReplicationGraphNode_AlwaysRelevant : public UReplicationGraphNode
{
public:
	unsigned char                                      UnknownData00[0x10];                                      // 0x0038(0x0010) MISSED OFFSET

	static UClass* StaticClass()
	{
		static UClass *pStaticClass = 0;
		if (!pStaticClass)
			 pStaticClass = UObject::FindClass("Class ReplicationGraph.ReplicationGraphNode_AlwaysRelevant");
		return pStaticClass;
	}

};


// Class ReplicationGraph.ReplicationGraphNode_TearOff_ForConnection
// 0x0018 (0x0050 - 0x0038)
class UReplicationGraphNode_TearOff_ForConnection : public UReplicationGraphNode
{
public:
	unsigned char                                      UnknownData00[0x18];                                      // 0x0038(0x0018) MISSED OFFSET

	static UClass* StaticClass()
	{
		static UClass *pStaticClass = 0;
		if (!pStaticClass)
			 pStaticClass = UObject::FindClass("Class ReplicationGraph.ReplicationGraphNode_TearOff_ForConnection");
		return pStaticClass;
	}

};


// Class ReplicationGraph.NetReplicationGraphConnection
// 0x0138 (0x0158 - 0x0020)
class UNetReplicationGraphConnection : public UReplicationConnectionDriver
{
public:
	unsigned char                                      UnknownData00[0x10C];                                     // 0x0020(0x010C) MISSED OFFSET
	class AReplicationGraphDebugActor*                 DebugActor;                                               // 0x012C(0x0004) (ZeroConstructor, IsPlainOldData)
	unsigned char                                      UnknownData01[0x8];                                       // 0x0130(0x0008) MISSED OFFSET
	TArray<class UReplicationGraphNode*>               ConnectionGraphNodes;                                     // 0x0138(0x000C) (ZeroConstructor)
	class UReplicationGraphNode_TearOff_ForConnection* TearOffNode;                                              // 0x0144(0x0004) (ZeroConstructor, IsPlainOldData)
	unsigned char                                      UnknownData02[0x10];                                      // 0x0148(0x0010) MISSED OFFSET

	static UClass* StaticClass()
	{
		static UClass *pStaticClass = 0;
		if (!pStaticClass)
			 pStaticClass = UObject::FindClass("Class ReplicationGraph.NetReplicationGraphConnection");
		return pStaticClass;
	}

};


// Class ReplicationGraph.ReplicationGraphDebugActor
// 0x0008 (0x02D0 - 0x02C8)
class AReplicationGraphDebugActor : public AActor
{
public:
	class UReplicationGraph*                           ReplicationGraph;                                         // 0x02C8(0x0004) (ZeroConstructor, IsPlainOldData)
	class UNetReplicationGraphConnection*              ConnectionManager;                                        // 0x02CC(0x0004) (ZeroConstructor, IsPlainOldData)

	static UClass* StaticClass()
	{
		static UClass *pStaticClass = 0;
		if (!pStaticClass)
			 pStaticClass = UObject::FindClass("Class ReplicationGraph.ReplicationGraphDebugActor");
		return pStaticClass;
	}


	void ServerStopDebugging();
	void ServerStartDebugging();
	void ServerSetPeriodFrameForClass(class UClass* Class, int PeriodFrame);
	void ServerSetCullDistanceForClass(class UClass* Class, float CullDistance);
	void ServerPrintAllActorInfo(const struct FString& str);
	void ServerCellInfo();
	void ClientCellInfo(const struct FVector& CellLocation, const struct FVector& CellExtent, TArray<class AActor*> Actors);
};


}

