#pragma once

// PlayerUnknown's Battlegrounds (0.27.0) SDK Generated By @IDRAGONCHEATS
namespace SDK
{
//---------------------------------------------------------------------------
//Script Structs
//---------------------------------------------------------------------------

// UserDefinedStruct BP_STRUCT_LoginTypeListCfg_type.BP_STRUCT_LoginTypeListCfg_type
// 0x0034
struct FBP_STRUCT_LoginTypeListCfg_type
{
	int                                                facebook_0_6B5EE5C01DC298954FEE67540DD47E2B;              // 0x0000(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	int                                                vk_1_4D150F800FF7457E47A4BBF80A4FE97B;                    // 0x0004(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	struct FString                                     ID_2_09129A803217EE9447A481C60A4FEA64;                    // 0x0008(0x000C) (Edit, BlueprintVisible, ZeroConstructor)
	struct FString                                     Language_3_6FFD20403D96047D07ADE9370E015C45;              // 0x0014(0x000C) (Edit, BlueprintVisible, ZeroConstructor)
	int                                                wechat_4_18F496407DA5B99D75445A810961D164;                // 0x0020(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	int                                                twitter_5_799D3C006ADF4D8C6E24EE0600844452;               // 0x0024(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	int                                                gpgc_6_7B1D3F8001ADAE6A15FF865F0FE85C93;                  // 0x0028(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	int                                                line_7_2BC341400AC147413DEA00130FE99605;                  // 0x002C(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	int                                                guest_8_1C3541407226F6AB70CC647C0E851854;                 // 0x0030(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
};

}

