#pragma once

// PlayerUnknown's Battlegrounds (0.27.0) SDK Generated By @IDRAGONCHEATS
namespace SDK
{
//---------------------------------------------------------------------------
//Script Structs
//---------------------------------------------------------------------------

// UserDefinedStruct BP_STRUCT_UnknowPass_Award_Jump_Info.BP_STRUCT_UnknowPass_Award_Jump_Info
// 0x000C
struct FBP_STRUCT_UnknowPass_Award_Jump_Info
{
	int                                                Idx_0_44EA99C02EF8BF2770843FE50D9EC2C8;                   // 0x0000(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	bool                                               IsElite_1_74445C40190C0851423FEA950D07CE75;               // 0x0004(0x0001) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	unsigned char                                      UnknownData00[0x3];                                       // 0x0005(0x0003) MISSED OFFSET
	int                                                EliteIdx_2_7FA9F680142D326E3FC9743906D373C8;              // 0x0008(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
};

}

