#pragma once

// PlayerUnknown's Battlegrounds (0.27.0) SDK Generated By @IDRAGONCHEATS
namespace SDK
{
//---------------------------------------------------------------------------
//Enums
//---------------------------------------------------------------------------

// Enum Client.FCDNDownloaderStateEnum
enum class EFCDNDownloaderStateEnum : uint8_t
{
	FCDNDownloaderStateEnum__CDNDownloaderEnum_LoadSuccess = 0,
	FCDNDownloaderStateEnum__CDNDownloaderEnum_LoadProgress = 1,
	FCDNDownloaderStateEnum__CDNDownloaderEnum_MAX = 2
};


// Enum Client.FDownloaderStateEnum
enum class EFDownloaderStateEnum : uint8_t
{
	FDownloaderStateEnum__CDNDownloaderEnum_LoadSuccess = 0,
	FDownloaderStateEnum__CDNDownloaderEnum_LoadProgress = 1,
	FDownloaderStateEnum__CDNDownloaderEnum_MAX = 2
};


// Enum Client.FCDNDownloaderTypeEnum
enum class EFCDNDownloaderTypeEnum : uint8_t
{
	FCDNDownloaderTypeEnum__FCDNDownloaderTypeEnum_Config = 0,
	FCDNDownloaderTypeEnum__FCDNDownloaderTypeEnum_Patch = 1,
	FCDNDownloaderTypeEnum__FCDNDownloaderTypeEnum_WhiteList = 2,
	FCDNDownloaderTypeEnum__FCDNDownloaderTypeEnum_MAX = 3
};


// Enum Client.FDownloaderTypeEnum
enum class EFDownloaderTypeEnum : uint8_t
{
	FDownloaderTypeEnum__FDownloaderTypeEnum_Config = 0,
	FDownloaderTypeEnum__FDownloaderTypeEnum_Patch = 1,
	FDownloaderTypeEnum__FDownloaderTypeEnum_WhiteList = 2,
	FDownloaderTypeEnum__FDownloaderTypeEnum_ConfigInMemory = 3,
	FDownloaderTypeEnum__FDownloaderTypeEnum_MAX = 4
};


// Enum Client.EIMSDKScreenDir
enum class EIMSDKScreenDir : uint8_t
{
	EIMSDKScreenDir__kScreenDirSensor = 0,
	EIMSDKScreenDir__kScreenDirPortrait = 1,
	EIMSDKScreenDir__kScreenDirLandscape = 2,
	EIMSDKScreenDir__EIMSDKScreenDir_MAX = 3
};


// Enum Client.EIMSDKContentType
enum class EIMSDKContentType : uint8_t
{
	EIMSDKContentType__kContentTypeText = 0,
	EIMSDKContentType__kContentTypeImage = 1,
	EIMSDKContentType__kContentTypeWeb = 2,
	EIMSDKContentType__EIMSDKContentType_MAX = 3
};


// Enum Client.EIMSDKNoticeType
enum class EIMSDKNoticeType : uint8_t
{
	EIMSDKNoticeType__kNoticeTypeAlert = 0,
	EIMSDKNoticeType__kNoticeTypeScroll = 1,
	EIMSDKNoticeType__kNoticeTypeAll = 2,
	EIMSDKNoticeType__EIMSDKNoticeType_MAX = 3
};


// Enum Client.EScreenDir
enum class EScreenDir : uint8_t
{
	EScreenDir__kScreenDirSensor   = 0,
	EScreenDir__kScreenDirPortrait = 1,
	EScreenDir__kScreenDirLandscape = 2,
	EScreenDir__EScreenDir_MAX     = 3
};


// Enum Client.EContentType
enum class EContentType : uint8_t
{
	EContentType__kContentTypeText = 0,
	EContentType__kContentTypeImage = 1,
	EContentType__kContentTypeWeb  = 2,
	EContentType__EContentType_MAX = 3
};


// Enum Client.ENoticeType
enum class ENoticeType : uint8_t
{
	ENoticeType__kNoticeTypeAlert  = 0,
	ENoticeType__kNoticeTypeScroll = 1,
	ENoticeType__kNoticeTypeAll    = 2,
	ENoticeType__ENoticeType_MAX   = 3
};


// Enum Client.EMidasPackType
enum class EMidasPackType : uint8_t
{
	EMidasPackType__kMidasPackNone = 0,
	EMidasPackType__kMidasPackInit = 1,
	EMidasPackType__kMidasPackPayNeedLogin = 2,
	EMidasPackType__kMidasPackPay  = 3,
	EMidasPackType__kMidasPackGetMP = 4,
	EMidasPackType__kMidasPackGetProductInfo = 5,
	EMidasPackType__kMidasPackReprovide = 6,
	EMidasPackType__kMidasPackGetIntroPrice = 7,
	EMidasPackType__EMidasPackType_MAX = 8
};


// Enum Client.EMidasMultiPayChannelSwitch
enum class EMidasMultiPayChannelSwitch : uint8_t
{
	EMidasMultiPayChannelSwitch__kMidasPayChannelMain = 0,
	EMidasMultiPayChannelSwitch__kMidasPayChannelH5 = 1,
	EMidasMultiPayChannelSwitch__EMidasMultiPayChannelSwitch_MAX = 2
};


// Enum Client.EButtonClickSoundTypes
enum class EButtonClickSoundTypes : uint8_t
{
	EButtonClickSoundTypes__None   = 0,
	EButtonClickSoundTypes__Play_UI_Bnt_Confirm = 1,
	EButtonClickSoundTypes__Play_UI_Bnt_Click = 2,
	EButtonClickSoundTypes__Play_UI_Bnt_Tab = 3,
	EButtonClickSoundTypes__Play_UI_Bnt_Select = 4,
	EButtonClickSoundTypes__Play_UI_Bnt_Close = 5,
	EButtonClickSoundTypes__Play_UI_Bnt_MainMenu = 6,
	EButtonClickSoundTypes__Play_UI_Bnt_MenuOpen = 7,
	EButtonClickSoundTypes__Play_UI_Bnt_MenuClose = 8,
	EButtonClickSoundTypes__Play_UI_Bnt_StartGame = 9,
	EButtonClickSoundTypes__Play_UI_Bnt_Turn = 10,
	EButtonClickSoundTypes__Play_UI_Bnt_Set = 11,
	EButtonClickSoundTypes__EButtonClickSoundTypes_MAX = 12
};



//---------------------------------------------------------------------------
//Script Structs
//---------------------------------------------------------------------------

// ScriptStruct Client.CDNDownloaderInfo
// 0x0024
struct FCDNDownloaderInfo
{
	EFCDNDownloaderStateEnum                           State;                                                    // 0x0000(0x0001) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	unsigned char                                      UnknownData00[0x3];                                       // 0x0001(0x0003) MISSED OFFSET
	struct FString                                     FileSavePath;                                             // 0x0004(0x000C) (Edit, BlueprintVisible, ZeroConstructor)
	bool                                               Result;                                                   // 0x0010(0x0001) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	unsigned char                                      UnknownData01[0x3];                                       // 0x0011(0x0003) MISSED OFFSET
	int                                                BytesSent;                                                // 0x0014(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	int                                                BytesReceived;                                            // 0x0018(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	int                                                ContentType;                                              // 0x001C(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	int                                                ResponseCode;                                             // 0x0020(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
};

// ScriptStruct Client.GameWidgetConfig
// 0x0020
struct FGameWidgetConfig
{
	struct FString                                     Path;                                                     // 0x0000(0x000C) (ZeroConstructor)
	struct FString                                     Container;                                                // 0x000C(0x000C) (ZeroConstructor)
	int                                                ZOrder;                                                   // 0x0018(0x0004) (ZeroConstructor, IsPlainOldData)
	class UClass*                                      WidgetClass;                                              // 0x001C(0x0004) (ZeroConstructor, IsPlainOldData)
};

// ScriptStruct Client.CustomSettingSaveGame
// 0x0010
struct FCustomSettingSaveGame
{
	struct FString                                     LayoutSlotName;                                           // 0x0000(0x000C) (ZeroConstructor)
	class USaveGame*                                   SaveGame;                                                 // 0x000C(0x0004) (ZeroConstructor, IsPlainOldData)
};

// ScriptStruct Client.NativeHUDTickContainer
// 0x000C
struct FNativeHUDTickContainer
{
	int                                                WidgetIndex;                                              // 0x0000(0x0004) (ZeroConstructor, IsPlainOldData)
	TWeakObjectPtr<class UUAEUserWidget>               pWidget;                                                  // 0x0004(0x0008) (ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData)
};

// ScriptStruct Client.WebviewInfoWrapper
// 0x0024
struct FWebviewInfoWrapper
{
	int                                                ErrorCode;                                                // 0x0000(0x0004) (ZeroConstructor, IsPlainOldData)
	struct FString                                     Reason;                                                   // 0x0004(0x000C) (ZeroConstructor)
	int                                                Extend;                                                   // 0x0010(0x0004) (ZeroConstructor, IsPlainOldData)
	int                                                Extend2;                                                  // 0x0014(0x0004) (ZeroConstructor, IsPlainOldData)
	struct FString                                     MsgData;                                                  // 0x0018(0x000C) (ZeroConstructor)
};

// ScriptStruct Client.WakeupInfoWrapper
// 0x003C
struct FWakeupInfoWrapper
{
	unsigned char                                      UnknownData00[0x3C];                                      // 0x0000(0x003C) MISSED OFFSET
};

// ScriptStruct Client.PlatformFriendInfoMap
// 0x0040
struct FPlatformFriendInfoMap
{
	int                                                page;                                                     // 0x0000(0x0004) (ZeroConstructor, IsPlainOldData)
	TMap<struct FString, struct FString>               friendsInfo;                                              // 0x0004(0x003C) (ZeroConstructor)
};

// ScriptStruct Client.LocationInfoWrapper
// 0x0018
struct FLocationInfoWrapper
{
	int                                                ErrorCode;                                                // 0x0000(0x0004) (ZeroConstructor, IsPlainOldData)
	unsigned char                                      UnknownData00[0x4];                                       // 0x0004(0x0004) MISSED OFFSET
	double                                             Longitude;                                                // 0x0008(0x0008) (ZeroConstructor, IsPlainOldData)
	double                                             Latitude;                                                 // 0x0010(0x0008) (ZeroConstructor, IsPlainOldData)
};

// ScriptStruct Client.WechatGroupInfomation
// 0x0024
struct FWechatGroupInfomation
{
	struct FString                                     OpenIdList;                                               // 0x0000(0x000C) (ZeroConstructor)
	struct FString                                     MemberNum;                                                // 0x000C(0x000C) (ZeroConstructor)
	struct FString                                     ChatRoomURL;                                              // 0x0018(0x000C) (ZeroConstructor)
};

// ScriptStruct Client.GroupInfoWrapper
// 0x0040
struct FGroupInfoWrapper
{
	int                                                SnsAction;                                                // 0x0000(0x0004) (ZeroConstructor, IsPlainOldData)
	int                                                Flag;                                                     // 0x0004(0x0004) (ZeroConstructor, IsPlainOldData)
	int                                                ErrorCode;                                                // 0x0008(0x0004) (ZeroConstructor, IsPlainOldData)
	int                                                platform;                                                 // 0x000C(0x0004) (ZeroConstructor, IsPlainOldData)
	struct FString                                     Desc;                                                     // 0x0010(0x000C) (ZeroConstructor)
	struct FWechatGroupInfomation                      wechatGroupInfo;                                          // 0x001C(0x0024)
};

// ScriptStruct Client.DownloaderInfo
// 0x0030
struct FDownloaderInfo
{
	EFDownloaderStateEnum                              State;                                                    // 0x0000(0x0001) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	unsigned char                                      UnknownData00[0x3];                                       // 0x0001(0x0003) MISSED OFFSET
	struct FString                                     FileSavePath;                                             // 0x0004(0x000C) (Edit, BlueprintVisible, ZeroConstructor)
	bool                                               Result;                                                   // 0x0010(0x0001) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	unsigned char                                      UnknownData01[0x3];                                       // 0x0011(0x0003) MISSED OFFSET
	int                                                BytesSent;                                                // 0x0014(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	int                                                BytesReceived;                                            // 0x0018(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	int                                                ContentType;                                              // 0x001C(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	int                                                ResponseCode;                                             // 0x0020(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	struct FString                                     StringContent;                                            // 0x0024(0x000C) (Edit, BlueprintVisible, ZeroConstructor)
};

// ScriptStruct Client.PictureInfomation
// 0x001C
struct FPictureInfomation
{
	EScreenDir                                         PicScreenDir;                                             // 0x0000(0x0001) (Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData)
	unsigned char                                      UnknownData00[0x3];                                       // 0x0001(0x0003) MISSED OFFSET
	struct FString                                     PicPath;                                                  // 0x0004(0x000C) (Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor)
	struct FString                                     HashValue;                                                // 0x0010(0x000C) (Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor)
};

// ScriptStruct Client.NoticeInfo
// 0x0098
struct FNoticeInfo
{
	struct FString                                     msgID;                                                    // 0x0000(0x000C) (Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor)
	struct FString                                     OpenID;                                                   // 0x000C(0x000C) (Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor)
	struct FString                                     MsgUrl;                                                   // 0x0018(0x000C) (Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor)
	ENoticeType                                        MsgType;                                                  // 0x0024(0x0001) (Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData)
	unsigned char                                      UnknownData00[0x3];                                       // 0x0025(0x0003) MISSED OFFSET
	struct FString                                     MsgScene;                                                 // 0x0028(0x000C) (Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor)
	struct FString                                     StartTime;                                                // 0x0034(0x000C) (Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor)
	struct FString                                     endTime;                                                  // 0x0040(0x000C) (Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor)
	EContentType                                       MsgContentType;                                           // 0x004C(0x0001) (Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData)
	unsigned char                                      UnknownData01[0x3];                                       // 0x004D(0x0003) MISSED OFFSET
	struct FString                                     MsgOrder;                                                 // 0x0050(0x000C) (Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor)
	struct FString                                     ContentUrl;                                               // 0x005C(0x000C) (Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor)
	TArray<struct FPictureInfomation>                  PicArray;                                                 // 0x0068(0x000C) (Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor)
	struct FString                                     MsgTitle;                                                 // 0x0074(0x000C) (Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor)
	struct FString                                     msgContent;                                               // 0x0080(0x000C) (Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor)
	struct FString                                     MsgEditCond;                                              // 0x008C(0x000C) (Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor)
};

// ScriptStruct Client.IMSDKPictureInfomation
// 0x0028
struct FIMSDKPictureInfomation
{
	EIMSDKScreenDir                                    PicScreenDir;                                             // 0x0000(0x0001) (Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData)
	unsigned char                                      UnknownData00[0x3];                                       // 0x0001(0x0003) MISSED OFFSET
	struct FString                                     PicPath;                                                  // 0x0004(0x000C) (Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor)
	struct FString                                     HashValue;                                                // 0x0010(0x000C) (Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor)
	struct FString                                     PicTitle;                                                 // 0x001C(0x000C) (Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor)
};

// ScriptStruct Client.IMSDKNoticeInfo
// 0x00A4
struct FIMSDKNoticeInfo
{
	struct FString                                     msgID;                                                    // 0x0000(0x000C) (Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor)
	struct FString                                     OpenID;                                                   // 0x000C(0x000C) (Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor)
	struct FString                                     MsgUrl;                                                   // 0x0018(0x000C) (Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor)
	EIMSDKNoticeType                                   MsgType;                                                  // 0x0024(0x0001) (Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData)
	unsigned char                                      UnknownData00[0x3];                                       // 0x0025(0x0003) MISSED OFFSET
	struct FString                                     MsgScene;                                                 // 0x0028(0x000C) (Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor)
	struct FString                                     StartTime;                                                // 0x0034(0x000C) (Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor)
	struct FString                                     endTime;                                                  // 0x0040(0x000C) (Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor)
	EIMSDKContentType                                  MsgContentType;                                           // 0x004C(0x0001) (Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData)
	unsigned char                                      UnknownData01[0x3];                                       // 0x004D(0x0003) MISSED OFFSET
	struct FString                                     MsgOrder;                                                 // 0x0050(0x000C) (Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor)
	struct FString                                     ContentUrl;                                               // 0x005C(0x000C) (Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor)
	TArray<struct FIMSDKPictureInfomation>             PicArray;                                                 // 0x0068(0x000C) (Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor)
	struct FString                                     MsgTitle;                                                 // 0x0074(0x000C) (Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor)
	struct FString                                     msgContent;                                               // 0x0080(0x000C) (Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor)
	struct FString                                     MsgEditCond;                                              // 0x008C(0x000C) (Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor)
	struct FString                                     LoginTimes;                                               // 0x0098(0x000C) (Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor)
};

// ScriptStruct Client.LuaBPVar
// 0x0010
struct FLuaBPVar
{
	unsigned char                                      UnknownData00[0x10];                                      // 0x0000(0x0010) MISSED OFFSET
};

// ScriptStruct Client.FightFriendChat
// 0x0028
struct FFightFriendChat
{
	struct FString                                     Uid;                                                      // 0x0000(0x000C) (ZeroConstructor)
	struct FString                                     Name;                                                     // 0x000C(0x000C) (ZeroConstructor)
	struct FString                                     Msg;                                                      // 0x0018(0x000C) (ZeroConstructor)
	bool                                               selfMsg;                                                  // 0x0024(0x0001) (ZeroConstructor, IsPlainOldData)
	unsigned char                                      UnknownData00[0x3];                                       // 0x0025(0x0003) MISSED OFFSET
};

// ScriptStruct Client.PlayerFinishedGuide
// 0x0008
struct FPlayerFinishedGuide
{
	int                                                guideID;                                                  // 0x0000(0x0004) (ZeroConstructor, IsPlainOldData)
	int                                                FinishedCounts;                                           // 0x0004(0x0004) (ZeroConstructor, IsPlainOldData)
};

// ScriptStruct Client.TimeStamp
// 0x0018
struct FTimeStamp
{
	struct FString                                     Title;                                                    // 0x0000(0x000C) (Edit, BlueprintVisible, ZeroConstructor)
	int                                                Priority;                                                 // 0x000C(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	int                                                StartTime;                                                // 0x0010(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	int                                                endTime;                                                  // 0x0014(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
};

// ScriptStruct Client.PingServerInfo
// 0x002C
struct FPingServerInfo
{
	unsigned char                                      UnknownData00[0x2C];                                      // 0x0000(0x002C) MISSED OFFSET
};

// ScriptStruct Client.NearByPersonInfo
// 0x0020
struct FNearByPersonInfo
{
	struct FString                                     OpenID;                                                   // 0x0000(0x000C) (ZeroConstructor)
	struct FString                                     gender;                                                   // 0x000C(0x000C) (ZeroConstructor)
	bool                                               IsFriend;                                                 // 0x0018(0x0001) (ZeroConstructor, IsPlainOldData)
	unsigned char                                      UnknownData00[0x3];                                       // 0x0019(0x0003) MISSED OFFSET
	int                                                Distance;                                                 // 0x001C(0x0004) (ZeroConstructor, IsPlainOldData)
};

// ScriptStruct Client.GameMasterInfoWrapper
// 0x0010
struct FGameMasterInfoWrapper
{
	struct FString                                     EventName;                                                // 0x0000(0x000C) (ZeroConstructor)
	int                                                Result;                                                   // 0x000C(0x0004) (ZeroConstructor, IsPlainOldData)
};

// ScriptStruct Client.LoadTaskCfg
// 0x0010
struct FLoadTaskCfg
{
	struct FString                                     ObjectPath;                                               // 0x0000(0x000C) (ZeroConstructor)
	int                                                LoadPriority;                                             // 0x000C(0x0004) (ZeroConstructor, IsPlainOldData)
};

// ScriptStruct Client.VersionConfig
// 0x00C4
struct FVersionConfig
{
	unsigned char                                      UnknownData00[0xC4];                                      // 0x0000(0x00C4) MISSED OFFSET
};

// ScriptStruct Client.Version
// 0x0070
struct FVersion
{
	unsigned char                                      UnknownData00[0x70];                                      // 0x0000(0x0070) MISSED OFFSET
};

// ScriptStruct Client.PatchConfig
// 0x005C
struct FPatchConfig
{
	unsigned char                                      UnknownData00[0x5C];                                      // 0x0000(0x005C) MISSED OFFSET
};

// ScriptStruct Client.PatchURL
// 0x001C
struct FPatchURL
{
	unsigned char                                      UnknownData00[0x1C];                                      // 0x0000(0x001C) MISSED OFFSET
};

// ScriptStruct Client.WebviewActionInfo
// 0x000C
struct FWebviewActionInfo
{
	struct FString                                     URL;                                                      // 0x0000(0x000C) (ZeroConstructor)
};

// ScriptStruct Client.PlatformFriendInfo
// 0x0030
struct FPlatformFriendInfo
{
	struct FString                                     userID;                                                   // 0x0000(0x000C) (ZeroConstructor)
	struct FString                                     UserName;                                                 // 0x000C(0x000C) (ZeroConstructor)
	struct FString                                     headportraitURL;                                          // 0x0018(0x000C) (ZeroConstructor)
	struct FString                                     OpenID;                                                   // 0x0024(0x000C) (ZeroConstructor)
};

// ScriptStruct Client.IMSDKNoticeInfos
// 0x000C
struct FIMSDKNoticeInfos
{
	TArray<struct FIMSDKNoticeInfo>                    Infos;                                                    // 0x0000(0x000C) (Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor)
};

// ScriptStruct Client.NoticeInfos
// 0x000C
struct FNoticeInfos
{
	TArray<struct FNoticeInfo>                         Infos;                                                    // 0x0000(0x000C) (Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor)
};

// ScriptStruct Client.PufferDownloadLastTaskStatus
// 0x0018
struct FPufferDownloadLastTaskStatus
{
	struct FDateTime                                   Time;                                                     // 0x0000(0x0008)
	unsigned char                                      UnknownData00[0x10];                                      // 0x0008(0x0010) MISSED OFFSET
};

// ScriptStruct Client.PufferDownloadStates
// 0x0028
struct FPufferDownloadStates
{
	TArray<double>                                     speeds;                                                   // 0x0000(0x000C) (ZeroConstructor)
	struct FString                                     Filename;                                                 // 0x000C(0x000C) (ZeroConstructor)
	unsigned char                                      UnknownData00[0x10];                                      // 0x0018(0x0010) MISSED OFFSET
};

// ScriptStruct Client.ArrayLuaBPVar
// 0x0010
struct FArrayLuaBPVar
{
	unsigned char                                      UnknownData00[0x10];                                      // 0x0000(0x0010) MISSED OFFSET
};

// ScriptStruct Client.MapLuaBPVar
// 0x0010
struct FMapLuaBPVar
{
	unsigned char                                      UnknownData00[0x10];                                      // 0x0000(0x0010) MISSED OFFSET
};

// ScriptStruct Client.MidasPack
// 0x0044
struct FMidasPack
{
	unsigned char                                      UnknownData00[0x44];                                      // 0x0000(0x0044) MISSED OFFSET
};

}

