#pragma once

// PlayerUnknown's Battlegrounds (0.27.0) SDK Generated By @IDRAGONCHEATS
namespace SDK
{
//---------------------------------------------------------------------------
//Script Structs
//---------------------------------------------------------------------------

// UserDefinedStruct BP_STRUCT_VehicleRefitPatternTable_type.BP_STRUCT_VehicleRefitPatternTable_type
// 0x003C
struct FBP_STRUCT_VehicleRefitPatternTable_type
{
	struct FString                                     PatternBPPath_0_4B5944C06FBA413D7EB727A808597AD8;         // 0x0000(0x000C) (Edit, BlueprintVisible, ZeroConstructor)
	int                                                ID_1_3B4768C07AEB475737EB9B560A7BEF14;                    // 0x000C(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	struct FString                                     IconOffset_2_59F5A18037D665B02424026A0AB3EDF4;            // 0x0010(0x000C) (Edit, BlueprintVisible, ZeroConstructor)
	struct FString                                     IconPath2_3_024EF7804CE8216627C3CAFF038879F2;             // 0x001C(0x000C) (Edit, BlueprintVisible, ZeroConstructor)
	struct FString                                     IconPath1_4_024DF7404CE8216527C3CAFC038879F1;             // 0x0028(0x000C) (Edit, BlueprintVisible, ZeroConstructor)
	int                                                IconScale1_5_46562E0071F9B3283BE305F8087656B1;            // 0x0034(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	int                                                IconScale2_6_46572E4071F9B3293BE305FF087656B2;            // 0x0038(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
};

}

