#pragma once

// PlayerUnknown's Battlegrounds (0.27.0) SDK Generated By @IDRAGONCHEATS
#include "../SDK.hpp"

namespace SDK
{
//---------------------------------------------------------------------------
//Parameters
//---------------------------------------------------------------------------

// Function bp_corps.bp_corps_C.EventOnCorpsClose_NoFetch
struct Abp_corps_C_EventOnCorpsClose_NoFetch_Params
{
};

// Function bp_corps.bp_corps_C.EventOnCorpsClose
struct Abp_corps_C_EventOnCorpsClose_Params
{
};

// Function bp_corps.bp_corps_C.EventClickToggle_Push_NoFetch
struct Abp_corps_C_EventClickToggle_Push_NoFetch_Params
{
};

// Function bp_corps.bp_corps_C.EventClickToggle_Push
struct Abp_corps_C_EventClickToggle_Push_Params
{
};

// Function bp_corps.bp_corps_C.UserConstructionScript
struct Abp_corps_C_UserConstructionScript_Params
{
};

}

