#pragma once

// PlayerUnknown's Battlegrounds (0.26.0) SDK Generated By @IDRAGONCHEATS
namespace SDK
{
//---------------------------------------------------------------------------
//Classes
//---------------------------------------------------------------------------

// WidgetBlueprintGeneratedClass Common_MessageBox_Panel_BP.Common_MessageBox_Panel_BP_C
// 0x0028 (0x0318 - 0x02F0)
class UCommon_MessageBox_Panel_BP_C : public UUAEUserWidget
{
public:
	struct FPointerToUberGraphFrame                    UberGraphFrame;                                           // 0x02F0(0x0004) (Transient, DuplicateTransient)
	class UCommon_MessageBox_UIBP_C*                   Common_MessageBox_UIBP;                                   // 0x02F4(0x0004) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, RepNotify, Interp, NonTransactional, EditorOnly, NoDestructor, AutoWeak, ContainsInstancedReference, AssetRegistrySearchable, SimpleDisplay, AdvancedDisplay, Protected, BlueprintCallable, BlueprintAuthorityOnly, TextExportTransient, NonPIEDuplicateTransient, ExposeOnSpawn, PersistentInstance, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic, NativeAccessSpecifierProtected, NativeAccessSpecifierPrivate)
	class UButton*                                     Button_OK;                                                // 0x02F8(0x0004) (Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData)
	class UButton*                                     Button_Cancel;                                            // 0x02FC(0x0004) (Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData)
	class UTextBlock*                                  text_Title;                                               // 0x0300(0x0004) (Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData)
	class UUTRichTextBlock*                            text_Msg;                                                 // 0x0304(0x0004) (Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData)
	class Abp_common_messagebox_panel_C*               bp_viewController;                                        // 0x0308(0x0004) (Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData)
	class UTextBlock*                                  text_ok;                                                  // 0x030C(0x0004) (Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData)
	class UTextBlock*                                  Text_cancel;                                              // 0x0310(0x0004) (Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData)
	class UButton*                                     button_Close;                                             // 0x0314(0x0004) (Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData)

	static UClass* StaticClass()
	{
		static UClass *pStaticClass = 0;
		if (!pStaticClass)
			 pStaticClass = UObject::FindClass("WidgetBlueprintGeneratedClass Common_MessageBox_Panel_BP.Common_MessageBox_Panel_BP_C");
		return pStaticClass;
	}


	void UpdateMsg();
	void DeleteTimerInvoke();
	void TimerInvoke();
	void StartTimerInvoke();
	void InitView();
	void UIHide();
	void UIShow();
	void Construct();
	void OnClickOK();
	void OnClickCancel();
	void AutoClick();
	void ExecuteUbergraph_Common_MessageBox_Panel_BP(int EntryPoint);
};


}

