#pragma once

// PlayerUnknown's Battlegrounds (0.27.0) SDK Generated By @IDRAGONCHEATS
namespace SDK
{
//---------------------------------------------------------------------------
//Script Structs
//---------------------------------------------------------------------------

// UserDefinedStruct BP_STRUCT_SeasonMissionBPTable_type.BP_STRUCT_SeasonMissionBPTable_type
// 0x001C
struct FBP_STRUCT_SeasonMissionBPTable_type
{
	struct FString                                     Path_0_746EFA0071EA42DC1C74470F02D39998;                  // 0x0000(0x000C) (Edit, BlueprintVisible, ZeroConstructor)
	int                                                ID_1_73B51A0066811C521281291A0132D224;                    // 0x000C(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	struct FString                                     CName_2_3B02C7C021A8868F32F1BA220D295515;                 // 0x0010(0x000C) (Edit, BlueprintVisible, ZeroConstructor)
};

}

