#pragma once

// PlayerUnknown's Battlegrounds (0.27.0) SDK Generated By @IDRAGONCHEATS
#include "../SDK.hpp"

namespace SDK
{
//---------------------------------------------------------------------------
//Parameters
//---------------------------------------------------------------------------

// Function bp_faceteam.bp_faceteam_C.EventFaceteamUIRelease_NoFetch
struct Abp_faceteam_C_EventFaceteamUIRelease_NoFetch_Params
{
};

// Function bp_faceteam.bp_faceteam_C.EventFaceteamUIRelease
struct Abp_faceteam_C_EventFaceteamUIRelease_Params
{
};

// Function bp_faceteam.bp_faceteam_C.EventOpenAddFaceTeamCodePanel_NoFetch
struct Abp_faceteam_C_EventOpenAddFaceTeamCodePanel_NoFetch_Params
{
};

// Function bp_faceteam.bp_faceteam_C.EventOpenAddFaceTeamCodePanel
struct Abp_faceteam_C_EventOpenAddFaceTeamCodePanel_Params
{
};

// Function bp_faceteam.bp_faceteam_C.EventFetchInfo_NoFetch
struct Abp_faceteam_C_EventFetchInfo_NoFetch_Params
{
};

// Function bp_faceteam.bp_faceteam_C.EventFetchInfo
struct Abp_faceteam_C_EventFetchInfo_Params
{
};

// Function bp_faceteam.bp_faceteam_C.EventCreateFaceTeamCode_NoFetch
struct Abp_faceteam_C_EventCreateFaceTeamCode_NoFetch_Params
{
};

// Function bp_faceteam.bp_faceteam_C.EventCreateFaceTeamCode
struct Abp_faceteam_C_EventCreateFaceTeamCode_Params
{
};

// Function bp_faceteam.bp_faceteam_C.EventEnsureAddCodeTeam_NoFetch
struct Abp_faceteam_C_EventEnsureAddCodeTeam_NoFetch_Params
{
};

// Function bp_faceteam.bp_faceteam_C.EventEnsureAddCodeTeam
struct Abp_faceteam_C_EventEnsureAddCodeTeam_Params
{
};

// Function bp_faceteam.bp_faceteam_C.UserConstructionScript
struct Abp_faceteam_C_UserConstructionScript_Params
{
};

}

