#pragma once

// PlayerUnknown's Battlegrounds (0.27.0) SDK Generated By @IDRAGONCHEATS
namespace SDK
{
//---------------------------------------------------------------------------
//Script Structs
//---------------------------------------------------------------------------

// UserDefinedStruct BP_STRUCT_Achievement_FloatTip_Awards.BP_STRUCT_Achievement_FloatTip_Awards
// 0x0014
struct FBP_STRUCT_Achievement_FloatTip_Awards
{
	int                                                score_0_13DAEF40717FF7DB434EDAC40D31F595;                 // 0x0000(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	int                                                count0_3_41593E8017A157FC534DED73022194A0;                // 0x0004(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	int                                                id0_4_3101C7806CA7BDF07194AFBB031D2700;                   // 0x0008(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	int                                                count1_5_415A3EC017A157FD534DED70022194A1;                // 0x000C(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	int                                                id1_6_3102C7C06CA7BDF17194AFB4031D2701;                   // 0x0010(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
};

}

