#pragma once

// PlayerUnknown's Battlegrounds (0.27.0) SDK Generated By @IDRAGONCHEATS
namespace SDK
{
//---------------------------------------------------------------------------
//Classes
//---------------------------------------------------------------------------

// ScriptBlueprintGeneratedClass bp_corps_base.bp_corps_base_C
// 0x0024 (0x0324 - 0x0300)
class Abp_corps_base_C : public ALuaClassObj
{
public:
	class UScriptContextComponent*                     Generated_ScriptContext;                                  // 0x0300(0x0004) (BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData)
	TArray<bool>                                       BP_Array_CorpsBaseUI_RedPoint;                            // 0x0304(0x000C) (Edit, BlueprintVisible, ZeroConstructor)
	TArray<bool>                                       BP_Array_CorpsBaseUI_ShowTab;                             // 0x0310(0x000C) (Edit, BlueprintVisible, ZeroConstructor)
	int                                                BP_CorpsBase_SelectedIndex;                               // 0x031C(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	class USceneComponent*                             DefaultSceneRoot;                                         // 0x0320(0x0004) (BlueprintVisible, ZeroConstructor, IsPlainOldData)

	static UClass* StaticClass()
	{
		static UClass *pStaticClass = 0;
		if (!pStaticClass)
			 pStaticClass = UObject::FindClass("ScriptBlueprintGeneratedClass bp_corps_base.bp_corps_base_C");
		return pStaticClass;
	}


	void EventOnSelectIndex_NoFetch();
	void EventOnSelectIndex();
	void EventCorpsClose_NoFetch();
	void EventCorpsClose();
	void EventOnAfterHide_NoFetch();
	void EventOnAfterHide();
	void EventCorpsOnAfterShow_NoFetch();
	void EventCorpsOnAfterShow();
	void UserConstructionScript();
};


}

