#pragma once

// PlayerUnknown's Battlegrounds (0.27.0) SDK Generated By @IDRAGONCHEATS
#include "../SDK.hpp"

namespace SDK
{
//---------------------------------------------------------------------------
//Parameters
//---------------------------------------------------------------------------

// Function Login_Update_UIBP.Login_Update_UIBP_C.UpdateStartShaderPreCompile
struct ULogin_Update_UIBP_C_UpdateStartShaderPreCompile_Params
{
};

// Function Login_Update_UIBP.Login_Update_UIBP_C.UpdateProgressShaderPreCompile
struct ULogin_Update_UIBP_C_UpdateProgressShaderPreCompile_Params
{
};

// Function Login_Update_UIBP.Login_Update_UIBP_C.OnShaderPreCompileTimer
struct ULogin_Update_UIBP_C_OnShaderPreCompileTimer_Params
{
};

// Function Login_Update_UIBP.Login_Update_UIBP_C.StopShaderPreCompileTimer
struct ULogin_Update_UIBP_C_StopShaderPreCompileTimer_Params
{
};

// Function Login_Update_UIBP.Login_Update_UIBP_C.StartDownloadCDNContent
struct ULogin_Update_UIBP_C_StartDownloadCDNContent_Params
{
};

// Function Login_Update_UIBP.Login_Update_UIBP_C.GrayShowWaiting
struct ULogin_Update_UIBP_C_GrayShowWaiting_Params
{
};

// Function Login_Update_UIBP.Login_Update_UIBP_C.RetryDownload
struct ULogin_Update_UIBP_C_RetryDownload_Params
{
};

// Function Login_Update_UIBP.Login_Update_UIBP_C.NoWifiStartUpdate
struct ULogin_Update_UIBP_C_NoWifiStartUpdate_Params
{
};

// Function Login_Update_UIBP.Login_Update_UIBP_C.ShowWaiting
struct ULogin_Update_UIBP_C_ShowWaiting_Params
{
};

// Function Login_Update_UIBP.Login_Update_UIBP_C.OnFinished
struct ULogin_Update_UIBP_C_OnFinished_Params
{
};

// Function Login_Update_UIBP.Login_Update_UIBP_C.onShow
struct ULogin_Update_UIBP_C_onShow_Params
{
};

// Function Login_Update_UIBP.Login_Update_UIBP_C.ShowUpdateUI
struct ULogin_Update_UIBP_C_ShowUpdateUI_Params
{
};

// Function Login_Update_UIBP.Login_Update_UIBP_C.UpdateFinish
struct ULogin_Update_UIBP_C_UpdateFinish_Params
{
};

// Function Login_Update_UIBP.Login_Update_UIBP_C.StartUpdate
struct ULogin_Update_UIBP_C_StartUpdate_Params
{
};

// Function Login_Update_UIBP.Login_Update_UIBP_C.CancelUpdate
struct ULogin_Update_UIBP_C_CancelUpdate_Params
{
};

// Function Login_Update_UIBP.Login_Update_UIBP_C.NoticeUpdate
struct ULogin_Update_UIBP_C_NoticeUpdate_Params
{
};

// Function Login_Update_UIBP.Login_Update_UIBP_C.SetCurStage
struct ULogin_Update_UIBP_C_SetCurStage_Params
{
	struct FString                                     Stage;                                                    // (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor)
};

// Function Login_Update_UIBP.Login_Update_UIBP_C.RefreshProgress
struct ULogin_Update_UIBP_C_RefreshProgress_Params
{
};

// Function Login_Update_UIBP.Login_Update_UIBP_C.onRequestHandler_5B5DFD874209B365CDBEF886B12FAA9F
struct ULogin_Update_UIBP_C_onRequestHandler_5B5DFD874209B365CDBEF886B12FAA9F_Params
{
	struct FCDNDownloaderInfo                          Info;                                                     // (BlueprintVisible, BlueprintReadOnly, Parm)
};

// Function Login_Update_UIBP.Login_Update_UIBP_C.Construct
struct ULogin_Update_UIBP_C_Construct_Params
{
};

// Function Login_Update_UIBP.Login_Update_UIBP_C.BndEvt__Button_Cancel_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature
struct ULogin_Update_UIBP_C_BndEvt__Button_Cancel_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature_Params
{
};

// Function Login_Update_UIBP.Login_Update_UIBP_C.BndEvt__Button_Updated_K2Node_ComponentBoundEvent_21_OnButtonClickedEvent__DelegateSignature
struct ULogin_Update_UIBP_C_BndEvt__Button_Updated_K2Node_ComponentBoundEvent_21_OnButtonClickedEvent__DelegateSignature_Params
{
};

// Function Login_Update_UIBP.Login_Update_UIBP_C.DownloadCDNContent
struct ULogin_Update_UIBP_C_DownloadCDNContent_Params
{
	struct FString                                     URL;                                                      // (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor)
	int                                                loaderType;                                               // (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData)
	struct FString                                     savedDir;                                                 // (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor)
	bool                                               CDNNeedBreakpointContinualTransfer;                       // (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData)
};

// Function Login_Update_UIBP.Login_Update_UIBP_C.ExecuteUbergraph_Login_Update_UIBP
struct ULogin_Update_UIBP_C_ExecuteUbergraph_Login_Update_UIBP_Params
{
	int                                                EntryPoint;                                               // (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData)
};

}

