#pragma once

// PlayerUnknown's Battlegrounds (0.27.0) SDK Generated By @IDRAGONCHEATS
namespace SDK
{
//---------------------------------------------------------------------------
//Script Structs
//---------------------------------------------------------------------------

// UserDefinedStruct BP_STRUCT_GOLD_DETAIL.BP_STRUCT_GOLD_DETAIL
// 0x0034
struct FBP_STRUCT_GOLD_DETAIL
{
	int                                                watch_gold_0_F37BAECB4BE18121879A369012417798;            // 0x0000(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	int                                                sm_add_1_B806DCAE4AD52645B0E7599E3536794A;                // 0x0004(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	int                                                kill_gold_2_C74730E5494C322B1295DDBE1E835CDA;             // 0x0008(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	int                                                gold_card_add_3_568ADAC24B89208B92F70A9AFF57CCFA;         // 0x000C(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	int                                                rank_gold_4_01978BAE4138E4B71D2A91941568F3B3;             // 0x0010(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	int                                                team_add_6_718848B1446775E1A8CDF3A13A9151DF;              // 0x0014(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	int                                                hurt_gold_7_DED9144E40A08CEBF689F78C75FA3A4D;             // 0x0018(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	int                                                famous_master_add_8_5BD3A16344202B9A40049DB04126E67E;     // 0x001C(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	int                                                limitact_double_gold_rate_9_01E69B800A2A9F340760F92E085106A5;// 0x0020(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	int                                                up_limit_10_3059040007BE36A434846FFD0DF43854;             // 0x0024(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	int                                                kill_monster_gold_13_1CA2B1407DAD882B1977B88C052C0604;    // 0x0028(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	int                                                survived_gold_14_267C6A80192BC04807B2A67B08D779A4;        // 0x002C(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	int                                                survive_gold_15_33EAF1801D206D5A2606AAF708A10FF4;         // 0x0030(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
};

}

