#pragma once

// PlayerUnknown's Battlegrounds (0.27.0) SDK Generated By @IDRAGONCHEATS
#include "../SDK.hpp"

namespace SDK
{
//---------------------------------------------------------------------------
//Parameters
//---------------------------------------------------------------------------

// Function GlobalUIEventDispatcher_BP.GlobalUIEventDispatcher_BP_C.WardrobePutDownEvent__DelegateSignature
struct UGlobalUIEventDispatcher_BP_C_WardrobePutDownEvent__DelegateSignature_Params
{
	int                                                PutonID;                                                  // (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData)
	int                                                resID;                                                    // (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData)
};

}

