#pragma once

// PlayerUnknown's Battlegrounds (0.27.0) SDK Generated By @IDRAGONCHEATS
namespace SDK
{
//---------------------------------------------------------------------------
//Script Structs
//---------------------------------------------------------------------------

// UserDefinedStruct BP_STRUCT_RecordDataTLogUpload.BP_STRUCT_RecordDataTLogUpload
// 0x0018
struct FBP_STRUCT_RecordDataTLogUpload
{
	struct FString                                     device_type_0_6D784E806481468467186E040D35AE05;           // 0x0000(0x000C) (Edit, BlueprintVisible, ZeroConstructor)
	struct FString                                     share_channel_1_775B1D0060F2978A4693005209EE6B7C;         // 0x000C(0x000C) (Edit, BlueprintVisible, ZeroConstructor)
};

}

