#pragma once

// PlayerUnknown's Battlegrounds (0.26.0) SDK Generated By @IDRAGONCHEATS
#include "../SDK.hpp"

namespace SDK
{
//---------------------------------------------------------------------------
//Parameters
//---------------------------------------------------------------------------

// Function Login_SelectedPufferItem_UIBP.Login_SelectedPufferItem_UIBP_C.UpdateSelected
struct ULogin_SelectedPufferItem_UIBP_C_UpdateSelected_Params
{
};

// Function Login_SelectedPufferItem_UIBP.Login_SelectedPufferItem_UIBP_C.SetPufferData
struct ULogin_SelectedPufferItem_UIBP_C_SetPufferData_Params
{
	struct FBP_STRUCT_PufferInfo                       pufferinfo;                                               // (BlueprintVisible, BlueprintReadOnly, Parm)
	int                                                Index;                                                    // (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData)
};

// Function Login_SelectedPufferItem_UIBP.Login_SelectedPufferItem_UIBP_C.Construct
struct ULogin_SelectedPufferItem_UIBP_C_Construct_Params
{
};

// Function Login_SelectedPufferItem_UIBP.Login_SelectedPufferItem_UIBP_C.BndEvt__Button_0_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature
struct ULogin_SelectedPufferItem_UIBP_C_BndEvt__Button_0_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature_Params
{
};

// Function Login_SelectedPufferItem_UIBP.Login_SelectedPufferItem_UIBP_C.updatepuffer
struct ULogin_SelectedPufferItem_UIBP_C_updatepuffer_Params
{
};

// Function Login_SelectedPufferItem_UIBP.Login_SelectedPufferItem_UIBP_C.ExecuteUbergraph_Login_SelectedPufferItem_UIBP
struct ULogin_SelectedPufferItem_UIBP_C_ExecuteUbergraph_Login_SelectedPufferItem_UIBP_Params
{
	int                                                EntryPoint;                                               // (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData)
};

}

