#pragma once

// PlayerUnknown's Battlegrounds (0.27.0) SDK Generated By @IDRAGONCHEATS
namespace SDK
{
//---------------------------------------------------------------------------
//Classes
//---------------------------------------------------------------------------

// BlueprintGeneratedClass GlobalUIFunctionLibrary.GlobalUIFunctionLibrary_C
// 0x0000 (0x0020 - 0x0020)
class UGlobalUIFunctionLibrary_C : public UBlueprintFunctionLibrary
{
public:

	static UClass* StaticClass()
	{
		static UClass *pStaticClass = 0;
		if (!pStaticClass)
			 pStaticClass = UObject::FindClass("BlueprintGeneratedClass GlobalUIFunctionLibrary.GlobalUIFunctionLibrary_C");
		return pStaticClass;
	}


	static void IsConfigGameModeType(EGameModeType InGameModeType, class UObject* Context, class UObject* __WorldContext, bool* res);
	static void PlayModelSequence(const struct FString& Path, class UObject* __WorldContext, class ULevelSequencePlayer** playingsequence);
	static void GetPingColor(float ms, class UObject* __WorldContext, struct FLinearColor* Color);
	static void InitAmmoDropBox(class UMeshComponent* MeshComponent, int LOD, class UObject* __WorldContext);
	static void LoadSprite(class UImage* Image, const struct FString& IconPath, class UObject* __WorldContext);
	static void GetGlobalLuaUI(class UObject* WorldContextObject, class UObject* __WorldContext, class UGlobalLuaWidget_C** AsGlobal_Lua_Widget);
	static void SetArenaWeaponLightProperty(class UObject* __WorldContext);
	static void GetXieQualityPath(int quality, class UObject* __WorldContext, struct FString* Path);
	static void SetCornerQuality(class UImage* Image, int quality, class UObject* __WorldContext);
	static void SetIconQuality(class UImage* Image, int quality, class UObject* __WorldContext);
	static struct FString GetRankIntegralSmallIcon(const struct FString& Icon, class UObject* __WorldContext);
	static void SetRankInteral(const struct FBP_STRUCT_RankIntegralLevel_type& RankIntegralLevelInfo, class UImage* ImageIcon, class UTextBlock* TextBlock_Rank, class UCanvasPanel* Canvas_Panel_Star, class UImage* Image_Star, class UTextBlock* TextBlock_Star, class UObject* __WorldContext);
	static void ShowUIOnCheckIOS(class UWidget* UIWidget, bool bShow, class UObject* __WorldContext);
	static void RefreshCurrentFPS(class UObject* __WorldContext);
	static void SetFpsByIndex(int Index, class UObject* __WorldContext);
	static void SetAndroidKeyIsValid(bool Valid, class UObject* __WorldContext);
	static void GetCurrentCamera(class UObject* __WorldContext, class ACameraActor** Result);
	static void UpdateMPCLightDirection(class UObject* __WorldContext);
	static void GetAlphaSperateMatPathByImagePath(const struct FString& imgPath, class UObject* __WorldContext, struct FString* MatPath);
	static void SetImgWithPath(class UImage* ImgRef, const struct FString& imgPath, bool IsMatchSize, class UObject* __WorldContext);
	static void GetBgQualityPath(int quality, class UObject* __WorldContext, struct FString* Path);
	static void GetLobbyCorpsIcon(int IconID, class UObject* __WorldContext, class UTexture2D** Value);
	static void CloseHelpTips(class UObject* __WorldContext);
	static void ShowHelpTipsByButton(int StrID, class UButton* Button, class UObject* __WorldContext);
	static void GetBrushFromSprite(const struct FSlateBrush& Brush, const struct FString& Path, class UObject* __WorldContext, struct FSlateBrush* Result);
	static void IdToColor(int ID, class UObject* __WorldContext, struct FColor* Color);
	static void SetCorpsLevelLimit(class UTextBlock* textWidget, int Level, class UObject* __WorldContext);
	static void SetCorpsSegmentLimit(class UCommon_RankIntegralLevel_Style_Small_UIBP_C* segmentWidget, class UTextBlock* textWidget, int LevelId, class UObject* __WorldContext);
	static void SetMoneyIconByType(class UImage* img, int Type, class UObject* __WorldContext);
	static void GetSmallItemIconByID(int ItemID, class UObject* __WorldContext, struct FString* Path);
	static void SetImageFromPath(class UImage* Image, const struct FString& IconPath, class UObject* __WorldContext, bool* IsOK);
	static void GetLangueTable(class UObject* __WorldContext, class UUAEDataTable** NewParam);
	static void GetAlphaTexturePathByImgPath(const struct FString& imagepath, class UObject* __WorldContext, struct FString* AlphaImagePath);
	static void SetDXUIMaterialParam(const struct FString& indexString, const struct FString& imgPath, class UMaterialInstanceDynamic* MaterialInst, class UObject* __WorldContext);
	static void GetAlpahTextureByImgPath(const struct FString& imgPath, class UObject* __WorldContext, class UTexture2D** AlphaTexture);
	static void numToTimeStrFormat(int timeNum, class UObject* __WorldContext, struct FString* TimeStr);
	static void SetCharacterImage(const struct FString& imgPath, class UImage* imageItem, class UObject* __WorldContext);
	static void numToTimeStr(int timeNum, class UObject* __WorldContext, struct FString* TimeStr);
	static void UseSperateAlphaMaterialByImgPath(class UImage* img, const struct FString& imgPath, class UObject* __WorldContext, bool* Success);
	static void GetItemName(const struct FString& Name_, int length_, bool chineseSensity, class UObject* __WorldContext, struct FString* OutName);
	static void GetQualityPath(int quality, class UObject* __WorldContext, struct FString* Path);
	static void GetServerCurrentTime(class UObject* __WorldContext, struct FDateTime* Time);
	static void Global_SpawnNewbieTips(class UCanvasPanel* ParentWidget, class UWidget* GuidWidget, class UObject* __WorldContext, int ShapeType, bool ShowSpreadEffect, bool IsOneLine, float LineHorLength, float LineVertLength, struct FString* TipTxt, class UNewbieTips_Auto_C** NewBieTip);
	static void ChangeBrushColor(const struct FSlateBrush& Brush, const struct FLinearColor& Color, class UObject* __WorldContext, struct FSlateBrush* NewBrush);
	static void UpdateImageTint(class UImage* Image, const struct FLinearColor& Color, class UObject* __WorldContext);
	static void UpdateNationImage(class UImage* Image, const struct FString& RoleNation, class UObject* __WorldContext);
	static void UpdateImageByPath(class UImage* Image, const struct FString& Path, class UObject* __WorldContext);
	static void ShowItemTipsByWidget(int ItemID, class UWidget* Widget, const struct FVector2D& LocalCoordinate, bool IsLimit, const struct FString& Times, int ColorID, int PatternID, int ItemCount, class UObject* __WorldContext);
	static void SetHumanLightProperty(class UObject* __WorldContext);
	static void SetWeaponLightProperty(class UObject* __WorldContext);
	static void GetCameraMod(class UObject* __WorldContext, int* mod);
	static void IsJapanOrKorea(class UObject* __WorldContext, bool* Result);
	static void GetLobbyRankTexture(int rankIntegral, class UObject* __WorldContext, class UTexture2D** Output);
	static void GetGameGender(class UObject* __WorldContext, int* gender);
	static void SwitchSceneCameraByIndex(int idx, float blendTime, bool skipNotify, class UObject* __WorldContext);
	static void SetItemQuality(int ItemQuality, class UImage* imageres, class UObject* __WorldContext);
	static void SetSceneSkyLightProperty(const struct FString& lightName, const struct FTransform& Trans, float Intensity, const struct FLinearColor& Color, class UObject* __WorldContext);
	static void SetLobbyDefaultLightProperty(class UObject* __WorldContext);
	static void SetScenePointLightProperty(const struct FString& lightName, const struct FTransform& targetTrans, float Intensity, const struct FLinearColor& Color, int inverseSquareFalloff, float Radius, class UObject* __WorldContext);
	static void SetSceneDirectionalLightProperty(const struct FString& lightName, const struct FTransform& targetTrans, float Intensity, const struct FLinearColor& Color, class UObject* __WorldContext);
	static void SwitchLobbyCameraByIndex(int Index, float blendTime, class UObject* __WorldContext, bool* Success);
	static void SwitchLobbyMeshBg(int BgIdx, class UObject* __WorldContext);
	static void GetPlatfromDisplayName(const struct FString& strChannel, class UObject* __WorldContext, struct FString* showChannel);
	static void GetPlayerPrefs(class UObject* __WorldContext, class UPlayerPrefs_C** bp_playerprefs);
	static void ShowLobbyMenuEnterAnimation(class UObject* __WorldContext);
	static void NoReferenceAssetContainer(class UObject* __WorldContext, TArray<class UParticleSystem*>* Ret);
	static void GetLobbyGlobalBp(class UObject* __WorldContext, class UGlobal_Bp_C** AsGlobal_Bp);
	static void GetLobbyFrameTexture(int frameLevel, class UObject* __WorldContext, class UTexture2D** Output);
	static void InvoleBpFunctionNoFetch(const struct FString& InName, const struct FString& InFunname, class UObject* __WorldContext);
	static void CheckChatPrivacyAcceptStatus(class UObject* __WorldContext, bool* ChatPrivacyAcceptStatus);
	static void GetGVoiceInterface(class UObject* __WorldContext, class UGVoiceInterface** outputObj);
	static void OpenUseItemUI(const struct FString& itemInsID, class UObject* __WorldContext);
	static void ConvertURLByLanguage(const struct FString& URL, class UObject* __WorldContext, struct FString* convertedURL);
	static void isChineseSymbol(const struct FString& Text, class UObject* __WorldContext, bool* Result);
	static void isSpace(const struct FString& Text, class UObject* __WorldContext, bool* Result);
	static void GetNationInfo(const struct FString& NationCode, class UObject* __WorldContext, struct FBP_STRUCT_RegionConfig_type* NationInfo);
	static void SetImageWithSpriteRes(const struct FString& ResPath, class UImage* Image, class UObject* __WorldContext);
	static void GetNationSwitch(const struct FString& Name, class UObject* __WorldContext, bool* Ret);
	static void GetBpLuaObject(const struct FString& bp_name, class UObject* __WorldContext, class ALuaClassObj** Lua_obj);
	static void CheckIfMenuOpen(int MenuId, class UObject* __WorldContext, bool* Ret);
	static void GetValidStringAll(const struct FString& Text, bool CanBeEnglish, bool CanBeNumber, bool CanBeWhiteSpace, bool CanBeChinese, bool CanBeSpace, bool CanBeChineseSymbol, class UObject* __WorldContext, struct FString* validText);
	static void UpdateLobbyRedpointStatus(bool IsShow, int ModeId, class UObject* __WorldContext);
	static void GetItemTimeS_Server(int expire_ts, int valid_hours, class UObject* __WorldContext, struct FString* time_s, bool* is_have_limit);
	static void GetItemTimeS(int res_id, int FirstTimeNum, class UObject* __WorldContext, struct FString* time_s, bool* is_have_limit);
	static void TimeNumToTimeS(int time_num, class UObject* __WorldContext, struct FString* time_s);
	static void ShowItemTipsWithItemInfo(class UWidget* Button, const struct FBP_STRUCT_CommonItemData& item_info, class UObject* __WorldContext);
	static void ShowItemTipsByButton(int ItemID, class UButton* Button, int ColorID, int PatternID, bool ShowLimitIcon, class UObject* __WorldContext);
	static void CloseItemTips(class UObject* __WorldContext);
	static void ShowItemTipsByPos(int ItemID, const struct FVector2D& Pos, class UObject* __WorldContext);
	static void CreateUAEUserWidget(class UClass* Class, class UUAEUserWidget* Parent, class UObject* __WorldContext, class UUAEUserWidget** Widget);
	static void PlaySoundCloseButton(class UObject* __WorldContext);
	static void ShowEffect(bool IsShow, class UObject* __WorldContext, TArray<class UWidget*>* Widget);
	static void IsWidgetVisible(class UWidget* Widget, class UObject* __WorldContext, bool* visible);
	static void PlaySoundClickButton(class UObject* __WorldContext);
	static void IsChinese(const struct FString& Text, class UObject* __WorldContext, bool* Result);
	static void SendBAReport(int ButtonType, int Reason, class UObject* __WorldContext);
	static void IsValidChar(const struct FString& Text, bool CanBeEnglish, bool CanBeNumber, bool CanBeWhiteSpace, bool CanBeChinese, bool CanBeSpace, bool CanBeChineseSymbol, class UObject* __WorldContext, bool* Result);
	static void IsNumber(const struct FString& Text, class UObject* __WorldContext, bool* Result);
	static void IsWhiteSpace(const struct FString& Text, class UObject* __WorldContext, bool* Result);
	static void GetTextLength(const struct FString& Text, bool chineseSensity, class UObject* __WorldContext, int* Length);
	static void BoolToVisible(bool visible, bool collapse, bool isButton, class UObject* __WorldContext, ESlateVisibility* Visibility);
	static void GetValidString(int maxLength, const struct FString& Text, bool CanBeEnglish, bool CanBeNumber, bool CanBeSpace, bool CanBeChinese, bool chineseSensity, class UObject* __WorldContext, struct FString* validText);
	static void IsEnglish(const struct FString& Text, class UObject* __WorldContext, bool* IsEnglish);
	static void OpenURL(const struct FString& URL, class UObject* __WorldContext);
	static void UpdateRankName(class UTextBlock* Text, int Level, class UObject* __WorldContext);
	static void UpdateRankIcon(class UImage* imageObj, int Level, class UObject* __WorldContext);
	static void GetGlobalData(class UObject* __WorldContext, class Abp_global_C** globalObj);
	static void InvoleBpFunction(const struct FString& bp_name, const struct FString& func_name, class UObject* __WorldContext);
	static void GetLocalizeString(int ID, const struct FString& string1, const struct FString& string2, const struct FString& string3, class UObject* __WorldContext, struct FString* TextValue);
	static void GetGlobalUIEventDispatcher(class UFrontendHUD* FrontendHUD, class UObject* __WorldContext, class UGlobalUIEventDispatcher_BP_C** NewParam);
};


}

