#pragma once

// PlayerUnknown's Battlegrounds (0.27.0) SDK Generated By @IDRAGONCHEATS
namespace SDK
{
//---------------------------------------------------------------------------
//Classes
//---------------------------------------------------------------------------

// Class Basic.UAENetActor
// 0x0010 (0x02D8 - 0x02C8)
class AUAENetActor : public AActor
{
public:
	unsigned char                                      UnknownData00[0x4];                                       // 0x02C8(0x0004) MISSED OFFSET
	int                                                iRegionActor;                                             // 0x02CC(0x0004) (ZeroConstructor, Config, IsPlainOldData)
	unsigned char                                      UnknownData01[0x8];                                       // 0x02D0(0x0008) MISSED OFFSET

	static UClass* StaticClass()
	{
		static UClass *pStaticClass = 0;
		if (!pStaticClass)
			 pStaticClass = UObject::FindClass("Class Basic.UAENetActor");
		return pStaticClass;
	}

};


// Class Basic.ItemHandleBase
// 0x006C (0x0088 - 0x001C)
class UItemHandleBase : public UObject
{
public:
	unsigned char                                      UnknownData00[0x4];                                       // 0x001C(0x0004) MISSED OFFSET
	int                                                MaxCount;                                                 // 0x0020(0x0004) (BlueprintVisible, ZeroConstructor, IsPlainOldData)
	bool                                               bUnique;                                                  // 0x0024(0x0001) (BlueprintVisible, ZeroConstructor, IsPlainOldData)
	bool                                               bStackable;                                               // 0x0025(0x0001) (BlueprintVisible, ZeroConstructor, IsPlainOldData)
	unsigned char                                      UnknownData01[0x2];                                       // 0x0026(0x0002) MISSED OFFSET
	TMap<struct FName, struct FItemAssociation>        AssociationMap;                                           // 0x0028(0x003C) (ZeroConstructor)
	unsigned char                                      UnknownData02[0x4];                                       // 0x0064(0x0004) MISSED OFFSET
	struct FItemDefineID                               DefineID;                                                 // 0x0068(0x0018)
	unsigned char                                      UnknownData03[0x8];                                       // 0x0080(0x0008) MISSED OFFSET

	static UClass* StaticClass()
	{
		static UClass *pStaticClass = 0;
		if (!pStaticClass)
			 pStaticClass = UObject::FindClass("Class Basic.ItemHandleBase");
		return pStaticClass;
	}


	void SetAssociation(const struct FName& Name, const struct FItemAssociation& Association);
	void RemoveAssociation(const struct FName& Name);
	void Init(const struct FItemDefineID& InDefineID);
	struct FItemDefineID GetDefineID();
	TMap<struct FName, struct FItemAssociation> GetAssociationMap();
	TArray<struct FItemAssociation> GetAssociationListByTargetType(int Type);
	struct FItemAssociation GetAssociationByTargetDefineID(const struct FItemDefineID& TargetDefineID);
	struct FItemAssociation GetAssociation(const struct FName& Name);
	void AddAssociation(const struct FName& Name, const struct FItemAssociation& Association);
};


// Class Basic.BattleItemHandleBase
// 0x0018 (0x00A0 - 0x0088)
class UBattleItemHandleBase : public UItemHandleBase
{
public:
	TArray<struct FBattleItemAdditionalData>           AdditionalData;                                           // 0x0088(0x000C) (BlueprintVisible, ZeroConstructor)
	float                                              UnitWeight;                                               // 0x0094(0x0004) (BlueprintVisible, ZeroConstructor, IsPlainOldData)
	bool                                               bEquippable;                                              // 0x0098(0x0001) (BlueprintVisible, ZeroConstructor, IsPlainOldData)
	bool                                               bConsumable;                                              // 0x0099(0x0001) (BlueprintVisible, ZeroConstructor, IsPlainOldData)
	bool                                               bAutoEquipAndDrop;                                        // 0x009A(0x0001) (BlueprintVisible, ZeroConstructor, IsPlainOldData)
	unsigned char                                      UnknownData00[0x5];                                       // 0x009B(0x0005) MISSED OFFSET

	static UClass* StaticClass()
	{
		static UClass *pStaticClass = 0;
		if (!pStaticClass)
			 pStaticClass = UObject::FindClass("Class Basic.BattleItemHandleBase");
		return pStaticClass;
	}


	bool HandleUse(const struct FBattleItemUseTarget& Target, EBattleItemUseReason Reason);
	bool HandlePickup(const TScriptInterface<class UItemContainerInterface>& ItemContainer, const struct FBattleItemPickupInfo& pickupInfo, EBattleItemPickupReason Reason);
	bool HandleEnable(bool bEnable);
	bool HandleDrop(int InCount, EBattleItemDropReason Reason);
	bool HandleDisuse(EBattleItemDisuseReason Reason);
	class UWorld* GetWorldInternal();
	struct FBattleItemData ExtractItemData();
};


// Class Basic.STBuffAction
// 0x001C (0x0038 - 0x001C)
class USTBuffAction : public UObject
{
public:
	unsigned char                                      UnknownData00[0x4];                                       // 0x001C(0x0004) MISSED OFFSET
	TWeakObjectPtr<class USTBuff>                      OwnerBuff;                                                // 0x0020(0x0008) (ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData)
	int                                                ArrayIndex;                                               // 0x0028(0x0004) (ZeroConstructor, IsPlainOldData)
	unsigned char                                      UnknownData01[0xC];                                       // 0x002C(0x000C) MISSED OFFSET

	static UClass* StaticClass()
	{
		static UClass *pStaticClass = 0;
		if (!pStaticClass)
			 pStaticClass = UObject::FindClass("Class Basic.STBuffAction");
		return pStaticClass;
	}


	void Tick(float DetalTime);
	void SetEnabled(bool Enabled);
	void ResetExecute(bool IgnoreEnd);
	void OnTick(float DetalTime);
	void OnInitialize();
	void OnExecute();
	void OnEnd();
	void OnDestroy();
	void OnChangeNotify();
	void Initialize();
	class USTBuff* GetOwnerBuff();
	class AActor* GetOwner();
	bool GetIsExecute();
	class AActor* GetCauser();
	void End();
	void Destroy();
	class USTBuffAction* CopyAction(class UObject* Outer);
	void ChangeNotify();
};


// Class Basic.STBuffCondition
// 0x0014 (0x0030 - 0x001C)
class USTBuffCondition : public UObject
{
public:
	unsigned char                                      UnknownData00[0x4];                                       // 0x001C(0x0004) MISSED OFFSET
	class USTBuffAction*                               OwnerAction;                                              // 0x0020(0x0004) (ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData)
	class USTBuff*                                     OwnerBuff;                                                // 0x0024(0x0004) (ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData)
	unsigned char                                      UnknownData01[0x8];                                       // 0x0028(0x0008) MISSED OFFSET

	static UClass* StaticClass()
	{
		static UClass *pStaticClass = 0;
		if (!pStaticClass)
			 pStaticClass = UObject::FindClass("Class Basic.STBuffCondition");
		return pStaticClass;
	}


	void OnInitialize();
	void OnDestroy();
	class USTBuffCondition* Copy(class UObject* Outer);
	bool CheckIsTrue();
};


// Class Basic.STBaseBuffStatusType
// 0x0004 (0x0020 - 0x001C)
class USTBaseBuffStatusType : public UObject
{
public:
	unsigned char                                      UnknownData00[0x4];                                       // 0x001C(0x0004) MISSED OFFSET

	static UClass* StaticClass()
	{
		static UClass *pStaticClass = 0;
		if (!pStaticClass)
			 pStaticClass = UObject::FindClass("Class Basic.STBaseBuffStatusType");
		return pStaticClass;
	}

};


// Class Basic.STBaseBuffSystemComponent
// 0x00A8 (0x0168 - 0x00C0)
class USTBaseBuffSystemComponent : public UActorComponent
{
public:
	unsigned char                                      UnknownData00[0x8];                                       // 0x00C0(0x0008) MISSED OFFSET
	struct FScriptMulticastDelegate                    OnBuffAttached;                                           // 0x00C8(0x000C) (ZeroConstructor, InstancedReference, BlueprintAssignable)
	struct FScriptMulticastDelegate                    OnBuffDetached;                                           // 0x00D4(0x000C) (ZeroConstructor, InstancedReference, BlueprintAssignable)
	unsigned char                                      UnknownData01[0x40];                                      // 0x00E0(0x0040) MISSED OFFSET
	TArray<struct FUTBuffSynData>                      BuffSyncList;                                             // 0x0120(0x000C) (BlueprintVisible, BlueprintReadOnly, Net, ZeroConstructor)
	struct FString                                     ServerBuffString;                                         // 0x012C(0x000C) (BlueprintVisible, BlueprintReadOnly, Net, ZeroConstructor)
	float                                              BuffSyncRemainingPeriod;                                  // 0x0138(0x0004) (Edit, ZeroConstructor, IsPlainOldData)
	TArray<struct FBuffInstancedItem>                  AllBuffs;                                                 // 0x013C(0x000C) (ZeroConstructor)
	unsigned char                                      UnknownData02[0x8];                                       // 0x0148(0x0008) MISSED OFFSET
	bool                                               isNeedCheckValidation;                                    // 0x0150(0x0001) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	unsigned char                                      UnknownData03[0x17];                                      // 0x0151(0x0017) MISSED OFFSET

	static UClass* StaticClass()
	{
		static UClass *pStaticClass = 0;
		if (!pStaticClass)
			 pStaticClass = UObject::FindClass("Class Basic.STBaseBuffSystemComponent");
		return pStaticClass;
	}


	bool SetBuffExpiry(const struct FName& BuffName, float ExpirySeconds);
	void ResetForDeath();
	void RepBuffSyncList();
	bool RemoveBuffWithCauser(const struct FName& BuffName, bool RemoveLayerOnly, class AController* pCauser);
	bool RemoveBuffByID(int BuffID, bool RemoveLayerOnly, class AController* pCauser, class AActor* BuffApplierActor);
	bool RemoveBuff(const struct FName& BuffName, bool RemoveLayerOnly, class AActor* BuffApplierActor);
	void RefreshAllBuffs();
	bool IsBufferMutexed(const struct FName& NewBuffName);
	bool HasBuffID(int BuffID);
	bool HasBuff(const struct FName& BuffName);
	class APawn* GetPawnOwner();
	struct FName GetBuffName(int BuffID);
	int GetBuffID(const struct FName& BuffName);
	float GetBuffExpiry(const struct FName& BuffName);
	class USTBaseBuff* GetBuffByName(const struct FName& BuffName);
	class AActor* GetActorOwner();
	void ClientSimulateRemoveBuff(const struct FName& BuffName, bool RemoveLayerOnly, class AActor* BuffApplierActor);
	void ClientSimulateAddBuff(const struct FName& BuffName, class AController* BuffCauser, int LayerCount, class AActor* BuffApplierActor);
	void ClientMulticastSimulateRemoveBuff(const struct FName& BuffName, bool RemoveLayerOnly, class AActor* BuffApplierActor);
	void ClientMulticastSimulateAddBuff(const struct FName& BuffName, class AController* BuffCauser, int LayerCount, class AActor* BuffApplierActor);
	void ClientMulticastSetBuffExpiry(const struct FName& BuffName, float LeftSecondsAfterNow);
	void ClearBuff(bool bDebuff, bool bGainBuff);
	bool CheckBuffStatus(class UClass* Status, bool* Value);
	void BuffDetached__DelegateSignature(const struct FName& BuffName);
	void BuffAttached__DelegateSignature(const struct FName& BuffName);
	bool AddBuffLayer(const struct FName& BuffName, int layerNum);
	bool AddBuffExpiry(const struct FName& BuffName, float ExpirySeconds);
	int AddBuffByID(int BuffID, class AController* BuffCauser, int LayerCount, class AActor* BuffApplierActor);
	int AddBuff(const struct FName& BuffName, class AController* BuffCauser, int LayerCount, class AActor* BuffApplierActor, class AActor* CauserActor);
};


// Class Basic.UAEGameInstance
// 0x0110 (0x0298 - 0x0188)
class UUAEGameInstance : public UGameInstance
{
public:
	struct FClientBaseInfo                             ClientBaseInfo;                                           // 0x0188(0x00D8)
	struct FScriptMulticastDelegate                    EnginePreTick;                                            // 0x0260(0x000C) (ZeroConstructor, InstancedReference)
	unsigned char                                      UnknownData00[0x18];                                      // 0x026C(0x0018) MISSED OFFSET
	class UActionQueueManager*                         ActionQueueManager;                                       // 0x0284(0x0004) (ZeroConstructor, IsPlainOldData)
	unsigned char                                      UnknownData01[0x4];                                       // 0x0288(0x0004) MISSED OFFSET
	class UFrontendHUD*                                AssociatedFrontendHUD;                                    // 0x028C(0x0004) (ZeroConstructor, IsPlainOldData)
	unsigned char                                      UnknownData02[0x4];                                       // 0x0290(0x0004) MISSED OFFSET
	class UUIMsgBus*                                   AssociatedUIMsgBus;                                       // 0x0294(0x0004) (ZeroConstructor, IsPlainOldData)

	static UClass* StaticClass()
	{
		static UClass *pStaticClass = 0;
		if (!pStaticClass)
			 pStaticClass = UObject::FindClass("Class Basic.UAEGameInstance");
		return pStaticClass;
	}


	void TestExec();
	void LuaLeakDetect();
	void LuaDoString(const struct FString& LuaString);
	float GetWeatherTime();
	int GetWeatherID();
	class UUIMsgBus* GetUIMsgBus();
	int GetDeviceLevel();
	static class UUAEDataTable* GetDataTableFromCurentGI(const struct FString& tableName);
	class UUAEDataTable* GetDataTable(const struct FString& tableName);
	class UFrontendHUD* GetAssociatedFrontendHUD();
};


// Class Basic.UAEAnimListComponentBase
// 0x0090 (0x0150 - 0x00C0)
class UUAEAnimListComponentBase : public UActorComponent
{
public:
	unsigned char                                      UnknownData00[0x38];                                      // 0x00C0(0x0038) MISSED OFFSET
	TMap<int, struct FAnimListMapValueData>            AnimListMap;                                              // 0x00F8(0x003C) (ZeroConstructor, Transient)
	TArray<class UAnimationAsset*>                     AnimationCatcheList;                                      // 0x0134(0x000C) (ZeroConstructor, Transient)
	TArray<struct FSoftObjectPath>                     AnimationLoadingPendingList;                              // 0x0140(0x000C) (ZeroConstructor, Transient)
	unsigned char                                      UnknownData01[0x4];                                       // 0x014C(0x0004) MISSED OFFSET

	static UClass* StaticClass()
	{
		static UClass *pStaticClass = 0;
		if (!pStaticClass)
			 pStaticClass = UObject::FindClass("Class Basic.UAEAnimListComponentBase");
		return pStaticClass;
	}

};


// Class Basic.UAEBaseSkillCondition
// 0x0008 (0x00E8 - 0x00E0)
class UUAEBaseSkillCondition : public UUTSkillCondition
{
public:
	unsigned char                                      UnknownData00[0x4];                                       // 0x00E0(0x0004) MISSED OFFSET
	class APawn*                                       OwnerPawnForBuff;                                         // 0x00E4(0x0004) (ZeroConstructor, IsPlainOldData)

	static UClass* StaticClass()
	{
		static UClass *pStaticClass = 0;
		if (!pStaticClass)
			 pStaticClass = UObject::FindClass("Class Basic.UAEBaseSkillCondition");
		return pStaticClass;
	}

};


// Class Basic.ActionQueueManager
// 0x0084 (0x00A0 - 0x001C)
class UActionQueueManager : public UObject
{
public:
	unsigned char                                      UnknownData00[0x84];                                      // 0x001C(0x0084) MISSED OFFSET

	static UClass* StaticClass()
	{
		static UClass *pStaticClass = 0;
		if (!pStaticClass)
			 pStaticClass = UObject::FindClass("Class Basic.ActionQueueManager");
		return pStaticClass;
	}


	class UActionQueueObject* GetQueueObject(const struct FString& Name);
};


// Class Basic.ActionQueueObject
// 0x0004 (0x0020 - 0x001C)
class UActionQueueObject : public UObject
{
public:
	unsigned char                                      UnknownData00[0x4];                                       // 0x001C(0x0004) MISSED OFFSET

	static UClass* StaticClass()
	{
		static UClass *pStaticClass = 0;
		if (!pStaticClass)
			 pStaticClass = UObject::FindClass("Class Basic.ActionQueueObject");
		return pStaticClass;
	}


	static class UActionQueueObject* Create(class UObject* Outer);
	void Clear();
	void ArrayIndexAddQueue(const struct FScriptDelegate& Delegate, int first, int End);
};


// Class Basic.AttrModifyComponent
// 0x01E8 (0x02A8 - 0x00C0)
class UAttrModifyComponent : public UActorComponent
{
public:
	struct FScriptMulticastDelegate                    OnAttrModified;                                           // 0x00C0(0x000C) (ZeroConstructor, InstancedReference, BlueprintAssignable)
	int                                                AttrGroup;                                                // 0x00CC(0x0004) (BlueprintVisible, ZeroConstructor, IsPlainOldData)
	TArray<struct FAttrModifyItem>                     ConfigAttrModifyList;                                     // 0x00D0(0x000C) (Edit, ZeroConstructor, DisableEditOnInstance)
	TArray<struct FAttrModifyGroupItem>                ConfigAttrModifyGroupList;                                // 0x00DC(0x000C) (Edit, ZeroConstructor, DisableEditOnInstance)
	unsigned char                                      UnknownData00[0xB8];                                      // 0x00E8(0x00B8) MISSED OFFSET
	uint32_t                                           AttrModifyStateList;                                      // 0x01A0(0x0004) (Net, ZeroConstructor, Transient, IsPlainOldData)
	TArray<bool>                                       AttrModifyGroupStateList;                                 // 0x01A4(0x000C) (ZeroConstructor, Transient)
	TArray<struct FAttrModifyItem>                     DynamicModifierRepList;                                   // 0x01B0(0x000C) (Net, ZeroConstructor, Transient)
	unsigned char                                      UnknownData01[0x20];                                      // 0x01BC(0x0020) MISSED OFFSET
	int                                                AttrModifyStateListNum;                                   // 0x01DC(0x0004) (ZeroConstructor, IsPlainOldData)
	TArray<struct FAttributeExpand>                    AttributeExpands;                                         // 0x01E0(0x000C) (Edit, ZeroConstructor, DisableEditOnInstance)
	struct FAttrDynamicModifier                        DynamicModifier;                                          // 0x01EC(0x007C)
	TMap<struct FString, struct FRelateAttributeGroup> RelateAttributeGroup;                                     // 0x0268(0x003C) (ZeroConstructor)
	unsigned char                                      UnknownData02[0x4];                                       // 0x02A4(0x0004) MISSED OFFSET

	static UClass* StaticClass()
	{
		static UClass *pStaticClass = 0;
		if (!pStaticClass)
			 pStaticClass = UObject::FindClass("Class Basic.AttrModifyComponent");
		return pStaticClass;
	}


	void SetAttrModifyStateValue(int Index, bool Value);
	bool RegisterModifyAbleAttr(TArray<struct FAttrRegisterItem> AttrRegists, bool bSetAttrByOrigin);
	void OnRep_DynamicModifierList();
	void OnRep_AttrModifyStateList();
	void OnRep_AttrModifyGroupStateList();
	void OnAttrModifiedEvent__DelegateSignature(TArray<struct FAttrAffected> AffectedAttrS);
	bool IsAttrModifyStateValidIndex(int Index);
	bool GetAttrModifyStateValue(int Index);
	int GetAttrModifyStateNum();
	struct FAttrModifyItem GetAttrModifyItemByItemName(const struct FString& ItemName);
	bool EnableAttrModifier(const struct FString& AttrModifyItemName);
	bool EnableAllAttrModifier();
	bool DisableModifierToActor(class AActor* TargetActor);
	bool DisableAttrModifier(const struct FString& AttrModifyItemName);
	bool DisableAllAttrModifier();
	void AddDynamicModifier(struct FAttrModifyItem* AttrModifyItem);
};


// Class Basic.AttrModifyInterface
// 0x0000 (0x0020 - 0x0020)
class UAttrModifyInterface : public UInterface
{
public:

	static UClass* StaticClass()
	{
		static UClass *pStaticClass = 0;
		if (!pStaticClass)
			 pStaticClass = UObject::FindClass("Class Basic.AttrModifyInterface");
		return pStaticClass;
	}


	void SetAttrValue(const struct FString& AttrName, float NewVal, int Reason);
	void RegisterModifiedAttributes();
	TArray<class AActor*> GetAttrModifyRelevantActors();
	class UAttrModifyComponent* GetAttrModifyComponent();
	float GetAttributeValue(const struct FString& AttrName);
	void AddAttrValue(const struct FString& AttrName, float AddVal, int Reason);
};


// Class Basic.BlueprintFunctionOverride
// 0x0010 (0x0030 - 0x0020)
class UBlueprintFunctionOverride : public UBlueprintFunctionLibrary
{
public:
	struct FString                                     LuaFilePath;                                              // 0x0020(0x000C) (Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor)
	unsigned char                                      UnknownData00[0x4];                                       // 0x002C(0x0004) MISSED OFFSET

	static UClass* StaticClass()
	{
		static UClass *pStaticClass = 0;
		if (!pStaticClass)
			 pStaticClass = UObject::FindClass("Class Basic.BlueprintFunctionOverride");
		return pStaticClass;
	}

};


// Class Basic.BPClassManager
// 0x0090 (0x00B0 - 0x0020)
class UBPClassManager : public UDataAsset
{
public:
	TArray<struct FBPClassItem>                        BPClassList;                                              // 0x0020(0x000C) (Edit, ZeroConstructor, DisableEditOnInstance)
	unsigned char                                      UnknownData00[0x3C];                                      // 0x002C(0x003C) UNKNOWN PROPERTY: MapProperty Basic.BPClassManager.BPClassLookUp
	unsigned char                                      UnknownData01[0x3C];                                      // 0x0068(0x003C) UNKNOWN PROPERTY: MapProperty Basic.BPClassManager.BPClassNameLookUp
	struct FString                                     BPClassManagerPath;                                       // 0x00A4(0x000C) (ZeroConstructor, Config)

	static UClass* StaticClass()
	{
		static UClass *pStaticClass = 0;
		if (!pStaticClass)
			 pStaticClass = UObject::FindClass("Class Basic.BPClassManager");
		return pStaticClass;
	}


	class UClass* GetUClass(int KeyIndex);
	class UClass* GetBPClassOverrideByName(const struct FString& ClassTagName);
	class UClass* GetBPClassOverride(class UClass* InNativeClass);
	static class UBPClassManager* Get();
};


// Class Basic.FeatureSetDefine
// 0x0004 (0x0020 - 0x001C)
class UFeatureSetDefine : public UObject
{
public:
	unsigned char                                      UnknownData00[0x4];                                       // 0x001C(0x0004) MISSED OFFSET

	static UClass* StaticClass()
	{
		static UClass *pStaticClass = 0;
		if (!pStaticClass)
			 pStaticClass = UObject::FindClass("Class Basic.FeatureSetDefine");
		return pStaticClass;
	}

};


// Class Basic.CustomGameMsg
// 0x0004 (0x0020 - 0x001C)
class UCustomGameMsg : public UObject
{
public:
	unsigned char                                      UnknownData00[0x4];                                       // 0x001C(0x0004) MISSED OFFSET

	static UClass* StaticClass()
	{
		static UClass *pStaticClass = 0;
		if (!pStaticClass)
			 pStaticClass = UObject::FindClass("Class Basic.CustomGameMsg");
		return pStaticClass;
	}


	static class UCustomGameMsg* MakeGameMsg(class UObject* UIMsgMaker, class UClass* CustomMsgClass);
};


// Class Basic.CustomGameMsgGroup
// 0x001C (0x0038 - 0x001C)
class UCustomGameMsgGroup : public UObject
{
public:
	unsigned char                                      UnknownData00[0xC];                                       // 0x001C(0x000C) MISSED OFFSET
	TArray<TWeakObjectPtr<class UObject>>              MsgListenerGroup;                                         // 0x0028(0x000C) (ZeroConstructor)
	unsigned char                                      UnknownData01[0x4];                                       // 0x0034(0x0004) MISSED OFFSET

	static UClass* StaticClass()
	{
		static UClass *pStaticClass = 0;
		if (!pStaticClass)
			 pStaticClass = UObject::FindClass("Class Basic.CustomGameMsgGroup");
		return pStaticClass;
	}

};


// Class Basic.CustomTaggedGameMsgGroup
// 0x0018 (0x0050 - 0x0038)
class UCustomTaggedGameMsgGroup : public UCustomGameMsgGroup
{
public:
	unsigned char                                      UnknownData00[0x8];                                       // 0x0038(0x0008) MISSED OFFSET
	TArray<struct FGameMsgCache>                       CachedMsgList;                                            // 0x0040(0x000C) (ZeroConstructor)
	unsigned char                                      UnknownData01[0x4];                                       // 0x004C(0x0004) MISSED OFFSET

	static UClass* StaticClass()
	{
		static UClass *pStaticClass = 0;
		if (!pStaticClass)
			 pStaticClass = UObject::FindClass("Class Basic.CustomTaggedGameMsgGroup");
		return pStaticClass;
	}

};


// Class Basic.CustomMsgBus
// 0x0078 (0x0098 - 0x0020)
class UCustomMsgBus : public UBlueprintFunctionLibrary
{
public:
	unsigned char                                      UnknownData00[0x38];                                      // 0x0020(0x0038) MISSED OFFSET
	TMap<struct FString, class UCustomTaggedGameMsgGroup*> TaggedMsgListenerGroupMap;                                // 0x0058(0x003C) (ZeroConstructor)
	unsigned char                                      UnknownData01[0x4];                                       // 0x0094(0x0004) MISSED OFFSET

	static UClass* StaticClass()
	{
		static UClass *pStaticClass = 0;
		if (!pStaticClass)
			 pStaticClass = UObject::FindClass("Class Basic.CustomMsgBus");
		return pStaticClass;
	}


	void UnRegistTaggedMsgListener(const struct FString& InMsgName, const struct FString& InMsgTagName, class UObject* InMsgLisenter);
	void UnRegistMsgListener(const struct FString& InMsgName, class UObject* InMsgLisenter);
	void RegistTaggedMsgListener(const struct FString& InMsgName, const struct FString& InMsgTagName, class UObject* InMsgLisenter);
	void RegistMsgListener(const struct FString& InMsgName, class UObject* InMsgLisenter);
	void PushTaggedMsg(const struct FString& InMsgName, const struct FString& InMsgTagName, class UCustomGameMsg* InTargetMsg, int TaggedMsgMaxProcessCount);
	void PushMsg(const struct FString& InMsgName, class UCustomGameMsg* InTargetMsg);
};


// Class Basic.UIMsgBus
// 0x0000 (0x0098 - 0x0098)
class UUIMsgBus : public UCustomMsgBus
{
public:

	static UClass* StaticClass()
	{
		static UClass *pStaticClass = 0;
		if (!pStaticClass)
			 pStaticClass = UObject::FindClass("Class Basic.UIMsgBus");
		return pStaticClass;
	}


	static class UUIMsgBus* GetUIMsgBus(class UObject* WorldContextObj);
};


// Class Basic.ItemContainerInterface
// 0x0000 (0x0020 - 0x0020)
class UItemContainerInterface : public UInterface
{
public:

	static UClass* StaticClass()
	{
		static UClass *pStaticClass = 0;
		if (!pStaticClass)
			 pStaticClass = UObject::FindClass("Class Basic.ItemContainerInterface");
		return pStaticClass;
	}


	class UObject* GetOwningObject();
	TArray<class UItemHandleBase*> GetItemHandleListByDefineID(const struct FItemDefineID& DefineID);
	class UItemHandleBase* GetItemHandleByDefineID(const struct FItemDefineID& DefineID);
	TArray<struct FItemDefineID> GetItemDefineIDList();
};


// Class Basic.ItemFactoryInterface
// 0x0000 (0x0020 - 0x0020)
class UItemFactoryInterface : public UInterface
{
public:

	static UClass* StaticClass()
	{
		static UClass *pStaticClass = 0;
		if (!pStaticClass)
			 pStaticClass = UObject::FindClass("Class Basic.ItemFactoryInterface");
		return pStaticClass;
	}

};


// Class Basic.LuaEventBridgeFunction
// 0x0000 (0x0020 - 0x0020)
class ULuaEventBridgeFunction : public UBlueprintFunctionLibrary
{
public:

	static UClass* StaticClass()
	{
		static UClass *pStaticClass = 0;
		if (!pStaticClass)
			 pStaticClass = UObject::FindClass("Class Basic.LuaEventBridgeFunction");
		return pStaticClass;
	}


	static void UnRegisterEventByTarget(class UObject* ObjContext);
	static void UnRegisterEvent(const struct FString& FEventType, const struct FString& EventID, class UObject* ObjContext);
	static void RegistEvent(const struct FString& EventType, const struct FString& EventID, class UObject* ObjContext, const struct FString& FunctionName);
};


// Class Basic.LuaEventBridge
// 0x00E4 (0x0100 - 0x001C)
class ULuaEventBridge : public UObject
{
public:
	unsigned char                                      UnknownData00[0xC];                                       // 0x001C(0x000C) MISSED OFFSET
	TMap<struct FString, struct FEventTypeContainer>   RegisterEventMap;                                         // 0x0028(0x003C) (ZeroConstructor)
	TMap<struct FString, struct FLuaEventTypeContainer> LuaRegisterEventMap;                                      // 0x0064(0x003C) (ZeroConstructor)
	TMap<uint32_t, struct FLuaEventTypeToIDSet>        FilterKeyRegisterMap;                                     // 0x00A0(0x003C) (ZeroConstructor)
	TArray<class ULuaTemBPData*>                       CurrentParamArray;                                        // 0x00DC(0x000C) (ZeroConstructor)
	TArray<class UProperty*>                           Params;                                                   // 0x00E8(0x000C) (ZeroConstructor)
	unsigned char                                      UnknownData01[0xC];                                       // 0x00F4(0x000C) MISSED OFFSET

	static UClass* StaticClass()
	{
		static UClass *pStaticClass = 0;
		if (!pStaticClass)
			 pStaticClass = UObject::FindClass("Class Basic.LuaEventBridge");
		return pStaticClass;
	}


	void SyncLuaRegisterEventNum(const struct FString& EventType, const struct FString& EventID, int Number);
	TArray<class ULuaTemBPData*> GetCurrentParam();
	void DeactivateEventsByFilterKey(uint32_t FilterKey);
	void ActiveEventByFilterKey(uint32_t FilterKey, const struct FString& EventType, const struct FString& EventID);
};


// Class Basic.NetRelevancyGroup
// 0x0024 (0x0040 - 0x001C)
class UNetRelevancyGroup : public UObject
{
public:
	unsigned char                                      UnknownData00[0x4];                                       // 0x001C(0x0004) MISSED OFFSET
	TArray<class UUAENetConnection*>                   Connections;                                              // 0x0020(0x000C) (ZeroConstructor)
	unsigned char                                      UnknownData01[0x14];                                      // 0x002C(0x0014) MISSED OFFSET

	static UClass* StaticClass()
	{
		static UClass *pStaticClass = 0;
		if (!pStaticClass)
			 pStaticClass = UObject::FindClass("Class Basic.NetRelevancyGroup");
		return pStaticClass;
	}

};


// Class Basic.OwnerRelevancyDependencyInterface
// 0x0000 (0x0020 - 0x0020)
class UOwnerRelevancyDependencyInterface : public UInterface
{
public:

	static UClass* StaticClass()
	{
		static UClass *pStaticClass = 0;
		if (!pStaticClass)
			 pStaticClass = UObject::FindClass("Class Basic.OwnerRelevancyDependencyInterface");
		return pStaticClass;
	}

};


// Class Basic.PackTool
// 0x000C (0x0028 - 0x001C)
class UPackTool : public UObject
{
public:
	unsigned char                                      UnknownData00[0xC];                                       // 0x001C(0x000C) MISSED OFFSET

	static UClass* StaticClass()
	{
		static UClass *pStaticClass = 0;
		if (!pStaticClass)
			 pStaticClass = UObject::FindClass("Class Basic.PackTool");
		return pStaticClass;
	}


	void CookResBySelection();
};


// Class Basic.STBaseBuff
// 0x00F4 (0x0110 - 0x001C)
class USTBaseBuff : public UObject
{
public:
	unsigned char                                      UnknownData00[0x4];                                       // 0x001C(0x0004) MISSED OFFSET
	struct FString                                     BuffName;                                                 // 0x0020(0x000C) (ZeroConstructor, Transient)
	struct FString                                     DisplayName;                                              // 0x002C(0x000C) (Edit, BlueprintVisible, ZeroConstructor)
	struct FString                                     Message;                                                  // 0x0038(0x000C) (Edit, BlueprintVisible, ZeroConstructor)
	class UTexture2D*                                  Icon;                                                     // 0x0044(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	class USoundBase*                                  SoundData;                                                // 0x0048(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	bool                                               IsDeBuff;                                                 // 0x004C(0x0001) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	bool                                               IgnoreMagicalImmunity;                                    // 0x004D(0x0001) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	bool                                               bAllowOtherPawnRefreshBuff;                               // 0x004E(0x0001) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	bool                                               Layerable;                                                // 0x004F(0x0001) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	bool                                               NeedDetachAndAttachForReplaceExit;                        // 0x0050(0x0001) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	bool                                               NeedDetachAndAttachForAddLayer;                           // 0x0051(0x0001) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	bool                                               ReplaceExsist;                                            // 0x0052(0x0001) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	bool                                               StaysOnDeath;                                             // 0x0053(0x0001) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	int                                                LayerMax;                                                 // 0x0054(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	int                                                InitialLayerCount;                                        // 0x0058(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	int                                                LayerCount;                                               // 0x005C(0x0004) (Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, EditConst, IsPlainOldData)
	float                                              ValidityTime;                                             // 0x0060(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	float                                              Internal;                                                 // 0x0064(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	TArray<class UUTSkillCondition*>                   BuffConditions;                                           // 0x0068(0x000C) (Edit, BlueprintVisible, ExportObject, ZeroConstructor)
	float                                              Expiry;                                                   // 0x0074(0x0004) (ZeroConstructor, IsPlainOldData)
	TArray<struct FStatusChange>                       StatusChanges;                                            // 0x0078(0x000C) (Edit, BlueprintVisible, ZeroConstructor)
	bool                                               NeedSimulateToClientMulticast;                            // 0x0084(0x0001) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	bool                                               NeedSimulateToClient;                                     // 0x0085(0x0001) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	TEnumAsByte<ESimulateAddBuffRole>                  SimulateAddBuffRole;                                      // 0x0086(0x0001) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	unsigned char                                      UnknownData01[0x1];                                       // 0x0087(0x0001) MISSED OFFSET
	TArray<struct FName>                               MutexBuffers;                                             // 0x0088(0x000C) (Edit, BlueprintVisible, ZeroConstructor)
	TArray<struct FBuffActionItem>                     BuffActions;                                              // 0x0094(0x000C) (Edit, BlueprintVisible, ZeroConstructor)
	TArray<struct FBuffEventActionItem>                EventBuffActions;                                         // 0x00A0(0x000C) (Edit, BlueprintVisible, ZeroConstructor)
	float                                              fADScale;                                                 // 0x00AC(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	float                                              fAPScale;                                                 // 0x00B0(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	bool                                               IsAlwaysExists;                                           // 0x00B4(0x0001) (Edit, ZeroConstructor, IsPlainOldData)
	unsigned char                                      UnknownData02[0x3];                                       // 0x00B5(0x0003) MISSED OFFSET
	class AController*                                 CauserPawnController;                                     // 0x00B8(0x0004) (ZeroConstructor, IsPlainOldData)
	class AActor*                                      CauserPawnActor;                                          // 0x00BC(0x0004) (ZeroConstructor, IsPlainOldData)
	unsigned char                                      UnknownData03[0xC];                                       // 0x00C0(0x000C) MISSED OFFSET
	class AActor*                                      BuffApplier;                                              // 0x00CC(0x0004) (ZeroConstructor, IsPlainOldData)
	TMap<class UObject*, int>                          InstancedNodeNameToMemoryMap;                             // 0x00D0(0x003C) (ZeroConstructor)
	int                                                InstancedNodesTotalSize;                                  // 0x010C(0x0004) (ZeroConstructor, IsPlainOldData)

	static UClass* StaticClass()
	{
		static UClass *pStaticClass = 0;
		if (!pStaticClass)
			 pStaticClass = UObject::FindClass("Class Basic.STBaseBuff");
		return pStaticClass;
	}

};


// Class Basic.STBaseBuffCarrierInterface
// 0x0000 (0x0020 - 0x0020)
class USTBaseBuffCarrierInterface : public UInterface
{
public:

	static UClass* StaticClass()
	{
		static UClass *pStaticClass = 0;
		if (!pStaticClass)
			 pStaticClass = UObject::FindClass("Class Basic.STBaseBuffCarrierInterface");
		return pStaticClass;
	}


	void SyncInvincibleData(float TotalTime);
	bool SetBuffExpiry(const struct FName& BuffName, float ExpirySecondsFromNow);
	bool RemoveBuffBySkill(int SkillID, int LayerCount, class AActor* Causer);
	bool RemoveBuffByID(int BuffID, class AActor* Causer, int LayerCount, int CauseSkillID);
	bool RemoveBuff(const struct FName& BuffName, bool RemoveLayerOnly, class AActor* BuffApplierActor);
	bool IsSameTeamWithFirstPC();
	bool HasBuffID(int BuffID);
	bool HasBuff(const struct FName& BuffName);
	float GetBuffExpiry(const struct FName& BuffName);
	class USTBaseBuff* GetBuffByName(const struct FName& BuffName);
	bool AddBuffLayer(const struct FName& BuffName, int layerNum);
	bool AddBuffExpiry(const struct FName& BuffName, float ExpirySeconds);
	bool AddBuffBySkill(int SkillID, int LayerCount, class AActor* Causer);
	bool AddBuffByID(int BuffID, class AActor* Causer, int LayerCount, int CauseSkillID);
	int AddBuff(const struct FName& BuffName, class AController* SkillActor, int LayerCount, class AActor* BuffApplierActor, class AActor* CauserActor);
};


// Class Basic.STBaseBuffConditionBase
// 0x0008 (0x00C8 - 0x00C0)
class USTBaseBuffConditionBase : public UActorComponent
{
public:
	unsigned char                                      UnknownData00[0x8];                                       // 0x00C0(0x0008) MISSED OFFSET

	static UClass* StaticClass()
	{
		static UClass *pStaticClass = 0;
		if (!pStaticClass)
			 pStaticClass = UObject::FindClass("Class Basic.STBaseBuffConditionBase");
		return pStaticClass;
	}

};


// Class Basic.STBaseBuffEventType
// 0x0004 (0x0020 - 0x001C)
class USTBaseBuffEventType : public UObject
{
public:
	unsigned char                                      UnknownData00[0x4];                                       // 0x001C(0x0004) MISSED OFFSET

	static UClass* StaticClass()
	{
		static UClass *pStaticClass = 0;
		if (!pStaticClass)
			 pStaticClass = UObject::FindClass("Class Basic.STBaseBuffEventType");
		return pStaticClass;
	}

};


// Class Basic.STBaseBuffEventType_LayerMax
// 0x0000 (0x0020 - 0x0020)
class USTBaseBuffEventType_LayerMax : public USTBaseBuffEventType
{
public:

	static UClass* StaticClass()
	{
		static UClass *pStaticClass = 0;
		if (!pStaticClass)
			 pStaticClass = UObject::FindClass("Class Basic.STBaseBuffEventType_LayerMax");
		return pStaticClass;
	}

};


// Class Basic.STBaseBuffEventType_LayerSpecific
// 0x0008 (0x0028 - 0x0020)
class USTBaseBuffEventType_LayerSpecific : public USTBaseBuffEventType
{
public:
	int                                                LayerCountParam;                                          // 0x0020(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	unsigned char                                      UnknownData00[0x4];                                       // 0x0024(0x0004) MISSED OFFSET

	static UClass* StaticClass()
	{
		static UClass *pStaticClass = 0;
		if (!pStaticClass)
			 pStaticClass = UObject::FindClass("Class Basic.STBaseBuffEventType_LayerSpecific");
		return pStaticClass;
	}

};


// Class Basic.STBaseBuffEventType_Removed
// 0x0000 (0x0020 - 0x0020)
class USTBaseBuffEventType_Removed : public USTBaseBuffEventType
{
public:

	static UClass* StaticClass()
	{
		static UClass *pStaticClass = 0;
		if (!pStaticClass)
			 pStaticClass = UObject::FindClass("Class Basic.STBaseBuffEventType_Removed");
		return pStaticClass;
	}

};


// Class Basic.STBaseBuffEventType_TakeBuffDamage
// 0x0000 (0x0020 - 0x0020)
class USTBaseBuffEventType_TakeBuffDamage : public USTBaseBuffEventType
{
public:

	static UClass* StaticClass()
	{
		static UClass *pStaticClass = 0;
		if (!pStaticClass)
			 pStaticClass = UObject::FindClass("Class Basic.STBaseBuffEventType_TakeBuffDamage");
		return pStaticClass;
	}

};


// Class Basic.STBaseBuffEventType_OnAttach
// 0x0000 (0x0020 - 0x0020)
class USTBaseBuffEventType_OnAttach : public USTBaseBuffEventType
{
public:

	static UClass* StaticClass()
	{
		static UClass *pStaticClass = 0;
		if (!pStaticClass)
			 pStaticClass = UObject::FindClass("Class Basic.STBaseBuffEventType_OnAttach");
		return pStaticClass;
	}

};


// Class Basic.STBaseBuffEventType_ConditionNotMatch
// 0x0000 (0x0020 - 0x0020)
class USTBaseBuffEventType_ConditionNotMatch : public USTBaseBuffEventType
{
public:

	static UClass* StaticClass()
	{
		static UClass *pStaticClass = 0;
		if (!pStaticClass)
			 pStaticClass = UObject::FindClass("Class Basic.STBaseBuffEventType_ConditionNotMatch");
		return pStaticClass;
	}

};


// Class Basic.STBaseBuffEventType_Resurrection
// 0x0000 (0x0020 - 0x0020)
class USTBaseBuffEventType_Resurrection : public USTBaseBuffEventType
{
public:

	static UClass* StaticClass()
	{
		static UClass *pStaticClass = 0;
		if (!pStaticClass)
			 pStaticClass = UObject::FindClass("Class Basic.STBaseBuffEventType_Resurrection");
		return pStaticClass;
	}

};


// Class Basic.STBaseBuffEventType_WeaponAttack
// 0x0010 (0x0030 - 0x0020)
class USTBaseBuffEventType_WeaponAttack : public USTBaseBuffEventType
{
public:
	unsigned char                                      UnknownData00[0x8];                                       // 0x0020(0x0008) MISSED OFFSET
	int                                                HitCount;                                                 // 0x0028(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	unsigned char                                      UnknownData01[0x4];                                       // 0x002C(0x0004) MISSED OFFSET

	static UClass* StaticClass()
	{
		static UClass *pStaticClass = 0;
		if (!pStaticClass)
			 pStaticClass = UObject::FindClass("Class Basic.STBaseBuffEventType_WeaponAttack");
		return pStaticClass;
	}

};


// Class Basic.STBaseBuffList
// 0x001C (0x0038 - 0x001C)
class USTBaseBuffList : public UObject
{
public:
	unsigned char                                      UnknownData00[0xC];                                       // 0x001C(0x000C) MISSED OFFSET
	TArray<struct FSTBaseBuffTemplateItem>             BuffList;                                                 // 0x0028(0x000C) (Edit, BlueprintVisible, ZeroConstructor)
	unsigned char                                      UnknownData01[0x4];                                       // 0x0034(0x0004) MISSED OFFSET

	static UClass* StaticClass()
	{
		static UClass *pStaticClass = 0;
		if (!pStaticClass)
			 pStaticClass = UObject::FindClass("Class Basic.STBaseBuffList");
		return pStaticClass;
	}

};


// Class Basic.BuffManagerPathClass
// 0x0010 (0x02D8 - 0x02C8)
class ABuffManagerPathClass : public AActor
{
public:
	struct FString                                     BuffManagerBlueprintPath;                                 // 0x02C8(0x000C) (ZeroConstructor, Config)
	unsigned char                                      UnknownData00[0x4];                                       // 0x02D4(0x0004) MISSED OFFSET

	static UClass* StaticClass()
	{
		static UClass *pStaticClass = 0;
		if (!pStaticClass)
			 pStaticClass = UObject::FindClass("Class Basic.BuffManagerPathClass");
		return pStaticClass;
	}

};


// Class Basic.STBaseBuffManager
// 0x010C (0x0128 - 0x001C)
class USTBaseBuffManager : public UObject
{
public:
	unsigned char                                      UnknownData00[0xC];                                       // 0x001C(0x000C) MISSED OFFSET
	TArray<class UClass*>                              BuffListTemplates;                                        // 0x0028(0x000C) (Edit, BlueprintVisible, ZeroConstructor)
	TMap<int, class USTBaseBuff*>                      BuffInstancedTemplateMap;                                 // 0x0034(0x003C) (ExportObject, ZeroConstructor)
	unsigned char                                      UnknownData01[0xB8];                                      // 0x0070(0x00B8) MISSED OFFSET

	static UClass* StaticClass()
	{
		static UClass *pStaticClass = 0;
		if (!pStaticClass)
			 pStaticClass = UObject::FindClass("Class Basic.STBaseBuffManager");
		return pStaticClass;
	}

};


// Class Basic.STBaseBuffStatusType_ImmuneDebuff
// 0x0000 (0x0020 - 0x0020)
class USTBaseBuffStatusType_ImmuneDebuff : public USTBaseBuffStatusType
{
public:

	static UClass* StaticClass()
	{
		static UClass *pStaticClass = 0;
		if (!pStaticClass)
			 pStaticClass = UObject::FindClass("Class Basic.STBaseBuffStatusType_ImmuneDebuff");
		return pStaticClass;
	}

};


// Class Basic.STBuff
// 0x00BC (0x00D8 - 0x001C)
class USTBuff : public UObject
{
public:
	unsigned char                                      UnknownData00[0xC];                                       // 0x001C(0x000C) MISSED OFFSET
	struct FString                                     Desc;                                                     // 0x0028(0x000C) (Edit, BlueprintVisible, ZeroConstructor)
	class UTexture2D*                                  Icon;                                                     // 0x0034(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	int                                                LayerMax;                                                 // 0x0038(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	int                                                InitialLayerCount;                                        // 0x003C(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	float                                              Duration;                                                 // 0x0040(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	float                                              ClientSyncInterval;                                       // 0x0044(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	bool                                               IsClientSync;                                             // 0x0048(0x0001) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	EBuffTargetType                                    TargetType;                                               // 0x0049(0x0001) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	EBuffTargetSubType                                 TargetSubype;                                             // 0x004A(0x0001) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	EBuffRefreshType                                   RefreshType;                                              // 0x004B(0x0001) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	EBuffReActionType                                  ReActionType;                                             // 0x004C(0x0001) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	EMultiCauserHandleType                             MultiCauserHandleType;                                    // 0x004D(0x0001) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	EMultiSkillHandleType                              MultiSkillHandleType;                                     // 0x004E(0x0001) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	bool                                               IsExecuteOnece;                                           // 0x004F(0x0001) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	TArray<class USTBuffAction*>                       Actions;                                                  // 0x0050(0x000C) (Edit, BlueprintVisible, ExportObject, ZeroConstructor)
	int                                                InstID;                                                   // 0x005C(0x0004) (ZeroConstructor, IsPlainOldData)
	int                                                BuffID;                                                   // 0x0060(0x0004) (ZeroConstructor, IsPlainOldData)
	int                                                LayerCount;                                               // 0x0064(0x0004) (ZeroConstructor, IsPlainOldData)
	bool                                               PendingRemove;                                            // 0x0068(0x0001) (ZeroConstructor, IsPlainOldData)
	unsigned char                                      UnknownData01[0x3];                                       // 0x0069(0x0003) MISSED OFFSET
	float                                              endTime;                                                  // 0x006C(0x0004) (ZeroConstructor, IsPlainOldData)
	TWeakObjectPtr<class AActor>                       Causer;                                                   // 0x0070(0x0008) (ZeroConstructor, IsPlainOldData)
	TWeakObjectPtr<class AActor>                       Owner;                                                    // 0x0078(0x0008) (ZeroConstructor, IsPlainOldData)
	int                                                CauseSkillID;                                             // 0x0080(0x0004) (ZeroConstructor, IsPlainOldData)
	TWeakObjectPtr<class USTBuffSystemComponent>       OwnerSystem;                                              // 0x0084(0x0008) (ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData)
	bool                                               ExistForever;                                             // 0x008C(0x0001) (ZeroConstructor, IsPlainOldData)
	unsigned char                                      UnknownData02[0x3];                                       // 0x008D(0x0003) MISSED OFFSET
	float                                              PowerValue;                                               // 0x0090(0x0004) (ZeroConstructor, IsPlainOldData)
	float                                              LastSyncClientTime;                                       // 0x0094(0x0004) (ZeroConstructor, IsPlainOldData)
	bool                                               IsNeedSyncClient;                                         // 0x0098(0x0001) (ZeroConstructor, IsPlainOldData)
	unsigned char                                      UnknownData03[0x3F];                                      // 0x0099(0x003F) MISSED OFFSET

	static UClass* StaticClass()
	{
		static UClass *pStaticClass = 0;
		if (!pStaticClass)
			 pStaticClass = UObject::FindClass("Class Basic.STBuff");
		return pStaticClass;
	}


	void Tick(float DetalTime, float TimeSeconds);
	void ResetActionExecute();
	void RefreshEndTime();
	void Initialize();
	void End();
	void EnabledRemove();
	void Destroy();
	bool CopyActions();
	void CheckOnceBuffForClient();
	void ChangeNotify();
	void ChangeDuration(float NewDuration);
};


// Class Basic.STBuffConditionComplex
// 0x0008 (0x0038 - 0x0030)
class USTBuffConditionComplex : public USTBuffCondition
{
public:
	unsigned char                                      UnknownData00[0x8];                                       // 0x0030(0x0008) MISSED OFFSET

	static UClass* StaticClass()
	{
		static UClass *pStaticClass = 0;
		if (!pStaticClass)
			 pStaticClass = UObject::FindClass("Class Basic.STBuffConditionComplex");
		return pStaticClass;
	}


	void OnInitialize();
	void OnDestroy();
	class USTBuffCondition* Copy(class UObject* Outer);
	bool CheckIsTrue();
};


// Class Basic.STBuffConditionAction
// 0x0020 (0x0058 - 0x0038)
class USTBuffConditionAction : public USTBuffAction
{
public:
	float                                              Probality;                                                // 0x0038(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	EBuffConditionExecuteTimeType                      ExecuteTimeType;                                          // 0x003C(0x0001) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	bool                                               IsDoOnFalse;                                              // 0x003D(0x0001) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	bool                                               IsNeedTick;                                               // 0x003E(0x0001) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	unsigned char                                      UnknownData00[0x1];                                       // 0x003F(0x0001) MISSED OFFSET
	TArray<struct FBuffConditionActionItem>            LinkActions;                                              // 0x0040(0x000C) (Edit, BlueprintVisible, ZeroConstructor)
	unsigned char                                      UnknownData01[0xC];                                       // 0x004C(0x000C) MISSED OFFSET

	static UClass* StaticClass()
	{
		static UClass *pStaticClass = 0;
		if (!pStaticClass)
			 pStaticClass = UObject::FindClass("Class Basic.STBuffConditionAction");
		return pStaticClass;
	}


	void OnTick(float DetalTime);
	void OnInitialize();
	void OnDestroy();
	void OnConditionTrue();
	void OnConditionFalse();
	void OnChangeNotify();
	void CheckCondition();
};


// Class Basic.STBuffSystemComponent
// 0x01A8 (0x0268 - 0x00C0)
class USTBuffSystemComponent : public UActorComponent
{
public:
	struct FString                                     BuffTableName;                                            // 0x00C0(0x000C) (Edit, ZeroConstructor)
	struct FString                                     OneceBuffTableName;                                       // 0x00CC(0x000C) (Edit, ZeroConstructor)
	struct FString                                     ConditionBuffTableName;                                   // 0x00D8(0x000C) (Edit, ZeroConstructor)
	unsigned char                                      UnknownData00[0x8];                                       // 0x00E4(0x0008) MISSED OFFSET
	TArray<class USTBuff*>                             Buffs;                                                    // 0x00EC(0x000C) (ExportObject, ZeroConstructor)
	int                                                SyncBriefNum;                                             // 0x00F8(0x0004) (ZeroConstructor, IsPlainOldData)
	struct FClientSyncBrief                            SyncBriefs[0x6];                                          // 0x00FC(0x0018) (Net)
	struct FClientSyncBrief                            SyncRefBriefs[0x6];                                       // 0x018C(0x0018)
	TMap<int, class USTBuff*>                          MaxPowerBuffs;                                            // 0x021C(0x003C) (ExportObject, ZeroConstructor)
	unsigned char                                      UnknownData01[0x10];                                      // 0x0258(0x0010) MISSED OFFSET

	static UClass* StaticClass()
	{
		static UClass *pStaticClass = 0;
		if (!pStaticClass)
			 pStaticClass = UObject::FindClass("Class Basic.STBuffSystemComponent");
		return pStaticClass;
	}


	bool UpdateServerSyncBuff(class USTBuff* Buff);
	void UpdateClientBuff(int InstID, int BuffID, int LayerCount, int CauseSkillID);
	void RemoveClientBuff(int InstID);
	class USTBuff* RemoveBuffInner(int BuffID, int LayerCount, class AActor* Causer, int CauseSkillID);
	void RemoveBuff(int BuffID, int LayerCount, class AActor* Causer, int CauseSkillID);
	void RemoveAndFindMaxPowerBuff(class USTBuff* RemoveBuff);
	void OnRep_SyncBriefs();
	bool HasSkillID(int SkillID);
	bool HasBuff(int BuffID);
	void HandleCauserSkill(class USTBuff* Buff, int SkillID);
	bool HandleBuffTypeMutex(int BuffID);
	void HandleBuffLayer(class USTBuff* Buff, int AddLayerCount, bool IsNewBuff);
	TArray<class USTBuff*> GetBuffsByID(int BuffID);
	class USTBuff* CreateBuff(int BuffID, class AActor* Causer, int LayerCount, int CauseSkillID);
	void CompareBuffPower(class USTBuff* Buff);
	void ClearBuffs(bool IsClearAll);
	bool AddBuff(int BuffID, class AActor* Causer, int LayerCount, int CauseSkillID);
};


// Class Basic.UStringMap
// 0x003C (0x0058 - 0x001C)
class UUStringMap : public UObject
{
public:
	unsigned char                                      UnknownData00[0x3C];                                      // 0x001C(0x003C) MISSED OFFSET

	static UClass* StaticClass()
	{
		static UClass *pStaticClass = 0;
		if (!pStaticClass)
			 pStaticClass = UObject::FindClass("Class Basic.UStringMap");
		return pStaticClass;
	}

};


// Class Basic.UAEGameEngine
// 0x0040 (0x0AC8 - 0x0A88)
class UUAEGameEngine : public UGameEngine
{
public:
	unsigned char                                      UnknownData00[0xC];                                       // 0x0A88(0x000C) MISSED OFFSET
	class UBackendHUD*                                 AssociatedBackendHUD;                                     // 0x0A94(0x0004) (ZeroConstructor, IsPlainOldData)
	unsigned char                                      UnknownData01[0xC];                                       // 0x0A98(0x000C) MISSED OFFSET
	bool                                               bEnableAutoStat;                                          // 0x0AA4(0x0001) (ZeroConstructor, Config, IsPlainOldData)
	unsigned char                                      UnknownData02[0x3];                                       // 0x0AA5(0x0003) MISSED OFFSET
	float                                              StatCollection_AvgTickDeltaThreshold;                     // 0x0AA8(0x0004) (ZeroConstructor, Config, IsPlainOldData)
	float                                              AutoStat_AvgTickDeltaThreshold;                           // 0x0AAC(0x0004) (ZeroConstructor, Config, IsPlainOldData)
	float                                              AutoStat_StartTime;                                       // 0x0AB0(0x0004) (ZeroConstructor, Config, IsPlainOldData)
	unsigned char                                      UnknownData03[0x4];                                       // 0x0AB4(0x0004) MISSED OFFSET
	float                                              AutoStat_Duration_Engine;                                 // 0x0AB8(0x0004) (ZeroConstructor, Config, IsPlainOldData)
	float                                              AutoStat_Duration_PhysX;                                  // 0x0ABC(0x0004) (ZeroConstructor, Config, IsPlainOldData)
	unsigned char                                      UnknownData04[0x8];                                       // 0x0AC0(0x0008) MISSED OFFSET

	static UClass* StaticClass()
	{
		static UClass *pStaticClass = 0;
		if (!pStaticClass)
			 pStaticClass = UObject::FindClass("Class Basic.UAEGameEngine");
		return pStaticClass;
	}

};


// Class Basic.BPTable
// 0x004C (0x0068 - 0x001C)
class UBPTable : public UObject
{
public:
	unsigned char                                      UnknownData00[0xC];                                       // 0x001C(0x000C) MISSED OFFSET
	TMap<int, struct FBPTableItem>                     BPTableItemMap;                                           // 0x0028(0x003C) (BlueprintVisible, BlueprintReadOnly, ZeroConstructor)
	unsigned char                                      UnknownData01[0x4];                                       // 0x0064(0x0004) MISSED OFFSET

	static UClass* StaticClass()
	{
		static UClass *pStaticClass = 0;
		if (!pStaticClass)
			 pStaticClass = UObject::FindClass("Class Basic.BPTable");
		return pStaticClass;
	}


	struct FString GetWrapperPath(int ID);
	class UClass* GetWrapperClass(int ID);
	struct FString GetPath(int ID);
	class UObject* GetObject(int ID, class UObject* Outer);
	class UClass* GetCustom1Class(int ID);
	class UClass* GetClass(int ID);
};


// Class Basic.UAELoadedClassManager
// 0x0224 (0x0240 - 0x001C)
class UUAELoadedClassManager : public UObject
{
public:
	unsigned char                                      UnknownData00[0xC];                                       // 0x001C(0x000C) MISSED OFFSET
	TMap<uint32_t, class UClass*>                      m_CookClass;                                              // 0x0028(0x003C) (ZeroConstructor)
	unsigned char                                      UnknownData01[0x8];                                       // 0x0064(0x0008) MISSED OFFSET
	TMap<int, struct FUAEResList>                      m_ResTableData;                                           // 0x006C(0x003C) (Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance)
	TMap<struct FString, class UBPTable*>              BPTableMap;                                               // 0x00A8(0x003C) (BlueprintVisible, BlueprintReadOnly, ZeroConstructor)
	struct FString                                     LoadedClassManagerClassName;                              // 0x00E4(0x000C) (ZeroConstructor, Config)
	unsigned char                                      UnknownData02[0x150];                                     // 0x00F0(0x0150) MISSED OFFSET

	static UClass* StaticClass()
	{
		static UClass *pStaticClass = 0;
		if (!pStaticClass)
			 pStaticClass = UObject::FindClass("Class Basic.UAELoadedClassManager");
		return pStaticClass;
	}


	bool IsDedicatedServer();
	void InitTableData();
	void InitBPTableMap();
	void Init();
	struct FString GetWrapperPath(const struct FString& BPTableName, int ID);
	class UClass* GetWrapperClass(const struct FString& BPTableName, int ID);
	struct FString GetPath(const struct FString& BPTableName, int ID, bool IsLobby);
	class UObject* GetObject(const struct FString& BPTableName, int ID, class UObject* Outer);
	class UClass* GetCustom1Class(const struct FString& BPTableName, int ID);
	class UClass* GetClass(const struct FString& BPTableName, int ID, bool IsLobby);
	void GetAssetByAssetReferenceAsync(const struct FSoftObjectPath& AssetReference, const struct FScriptDelegate& AssetLoadSuccessDelegate, bool AtLeastNextFrame);
	static class UUAELoadedClassManager* Get();
	class UBPTable* CreateAndAddBPTable(const struct FString& BPTableName);
	void ClearAssetByAssetReferenceAsync(const struct FScriptDelegate& AssetLoadSuccessDelegate);
	void ClearAllData();
};


// Class Basic.UAEMeshComponent
// 0x0000 (0x09E0 - 0x09E0)
class UUAEMeshComponent : public USkeletalMeshComponent
{
public:

	static UClass* StaticClass()
	{
		static UClass *pStaticClass = 0;
		if (!pStaticClass)
			 pStaticClass = UObject::FindClass("Class Basic.UAEMeshComponent");
		return pStaticClass;
	}

};


// Class Basic.UAENetConnection
// 0x01D8 (0x297C8 - 0x295F0)
class UUAENetConnection : public UIpConnection
{
public:
	unsigned char                                      UnknownData00[0x78];                                      // 0x295F0(0x0078) MISSED OFFSET
	int                                                InitialHandshakeTimeoutNumThreshold;                      // 0x29668(0x0004) (ZeroConstructor, Config, IsPlainOldData)
	unsigned char                                      UnknownData01[0x4];                                       // 0x2966C(0x0004) MISSED OFFSET
	int                                                ActorChannelProcessBunchErrorNumThreshold_Server_Global;  // 0x29670(0x0004) (ZeroConstructor, Config, IsPlainOldData)
	int                                                ActorChannelProcessBunchErrorNumThreshold_Client_Global;  // 0x29674(0x0004) (ZeroConstructor, Config, IsPlainOldData)
	int                                                ActorChannelProcessBunchErrorNumThreshold_Client_PerActor;// 0x29678(0x0004) (ZeroConstructor, Config, IsPlainOldData)
	unsigned char                                      UnknownData02[0x3C];                                      // 0x2967C(0x003C) MISSED OFFSET
	bool                                               bEnableHTTPDNS;                                           // 0x296B8(0x0001) (ZeroConstructor, Config, IsPlainOldData)
	unsigned char                                      UnknownData03[0x3];                                       // 0x296B9(0x0003) MISSED OFFSET
	struct FString                                     HTTPDNSServerAddr;                                        // 0x296BC(0x000C) (ZeroConstructor, Config)
	float                                              HTTPDNSResponseTimeout;                                   // 0x296C8(0x0004) (ZeroConstructor, Config, IsPlainOldData)
	unsigned char                                      UnknownData04[0xC];                                       // 0x296CC(0x000C) MISSED OFFSET
	class UNetRelevancyGroup*                          RelevancyGroup;                                           // 0x296D8(0x0004) (ZeroConstructor, IsPlainOldData)
	unsigned char                                      UnknownData05[0x98];                                      // 0x296DC(0x0098) MISSED OFFSET
	TArray<struct FPendingRegionNetworkObject>         PendingRegionNetworkObjects;                              // 0x29774(0x000C) (ZeroConstructor)
	float                                              MinRegionActorTickDelta;                                  // 0x29780(0x0004) (ZeroConstructor, Config, IsPlainOldData)
	float                                              MaxRegionActorTickDelta;                                  // 0x29784(0x0004) (ZeroConstructor, Config, IsPlainOldData)
	unsigned char                                      UnknownData06[0xC];                                       // 0x29788(0x000C) MISSED OFFSET
	bool                                               EnableWeakNetUpdate;                                      // 0x29794(0x0001) (ZeroConstructor, Config, IsPlainOldData)
	unsigned char                                      UnknownData07[0x3];                                       // 0x29795(0x0003) MISSED OFFSET
	float                                              MinWeakNetUpdateDelay;                                    // 0x29798(0x0004) (ZeroConstructor, Config, IsPlainOldData)
	float                                              MaxWeakNetUpdateDelay;                                    // 0x2979C(0x0004) (ZeroConstructor, Config, IsPlainOldData)
	float                                              SquareSegmentSize;                                        // 0x297A0(0x0004) (ZeroConstructor, Config, IsPlainOldData)
	float                                              MaxSegmentDistance;                                       // 0x297A4(0x0004) (ZeroConstructor, Config, IsPlainOldData)
	int                                                MaxObjectNumInSegments;                                   // 0x297A8(0x0004) (ZeroConstructor, Config, IsPlainOldData)
	unsigned char                                      UnknownData08[0xD];                                       // 0x297AC(0x000D) MISSED OFFSET
	bool                                               bRecreateSocketOnLost;                                    // 0x297B9(0x0001) (ZeroConstructor, Config, IsPlainOldData)
	unsigned char                                      UnknownData09[0xE];                                       // 0x297BA(0x000E) MISSED OFFSET

	static UClass* StaticClass()
	{
		static UClass *pStaticClass = 0;
		if (!pStaticClass)
			 pStaticClass = UObject::FindClass("Class Basic.UAENetConnection");
		return pStaticClass;
	}

};


// Class Basic.UAENetDriver
// 0x00F0 (0x06B0 - 0x05C0)
class UUAENetDriver : public UIpNetDriver
{
public:
	float                                              NetCullChangeTime;                                        // 0x05C0(0x0004) (ZeroConstructor, Config, IsPlainOldData)
	unsigned char                                      UnknownData00[0xEC];                                      // 0x05C4(0x00EC) MISSED OFFSET

	static UClass* StaticClass()
	{
		static UClass *pStaticClass = 0;
		if (!pStaticClass)
			 pStaticClass = UObject::FindClass("Class Basic.UAENetDriver");
		return pStaticClass;
	}

};


// Class Basic.UAETableManager
// 0x011C (0x0138 - 0x001C)
class UUAETableManager : public UObject
{
public:
	unsigned char                                      UnknownData00[0xC];                                       // 0x001C(0x000C) MISSED OFFSET
	TArray<struct FName>                               TablesNeedReleasedInBattle;                               // 0x0028(0x000C) (ZeroConstructor, Config)
	unsigned char                                      UnknownData01[0x3C];                                      // 0x0034(0x003C) MISSED OFFSET
	TArray<class UUAEDataTable*>                       TableObjList;                                             // 0x0070(0x000C) (ZeroConstructor)
	class UWorld*                                      CurWorld;                                                 // 0x007C(0x0004) (ZeroConstructor, IsPlainOldData)
	TMap<struct FName, TWeakObjectPtr<class UUAEDataTable>> TableObjMap;                                              // 0x0080(0x003C) (ZeroConstructor)
	unsigned char                                      UnknownData02[0x7C];                                      // 0x00BC(0x007C) MISSED OFFSET

	static UClass* StaticClass()
	{
		static UClass *pStaticClass = 0;
		if (!pStaticClass)
			 pStaticClass = UObject::FindClass("Class Basic.UAETableManager");
		return pStaticClass;
	}


	void ReleaseTable(const struct FName& tableName);
	class UUAEDataTable* GetTablePtr(const struct FName& tableName);
	static struct FString GetStringFromTable(const struct FString& Table, const struct FString& Row, const struct FString& Tag);
	static int GetIntFromTable(const struct FString& Table, const struct FString& Row, const struct FString& Tag);
	static float GetFloatFromTable(const struct FString& Table, const struct FString& Row, const struct FString& Tag);
	static class UUAEDataTable* GetDataTableStatic(const struct FString& tableName);
	static bool GetBoolFromTable(const struct FString& Table, const struct FString& Row, const struct FString& Tag);
};


// Class Basic.UEMathUtilityMethods
// 0x0000 (0x0020 - 0x0020)
class UUEMathUtilityMethods : public UBlueprintFunctionLibrary
{
public:

	static UClass* StaticClass()
	{
		static UClass *pStaticClass = 0;
		if (!pStaticClass)
			 pStaticClass = UObject::FindClass("Class Basic.UEMathUtilityMethods");
		return pStaticClass;
	}


	static float CalculateAngleToTargetAngle(float startAngle, float targetAngle, float stepAngle, EAngleRotationDirectionType dir);
	static float AngleDis(float angleA, float angleB);
};


}

