#pragma once

// PlayerUnknown's Battlegrounds (0.27.0) SDK Generated By @IDRAGONCHEATS
#include "../SDK.hpp"

namespace SDK
{
//---------------------------------------------------------------------------
//Parameters
//---------------------------------------------------------------------------

// Function Login_SplashScreen.Login_SplashScreen_C.InitLoginUI
struct ULogin_SplashScreen_C_InitLoginUI_Params
{
};

// Function Login_SplashScreen.Login_SplashScreen_C.UIShow
struct ULogin_SplashScreen_C_UIShow_Params
{
};

// Function Login_SplashScreen.Login_SplashScreen_C.ShowUI
struct ULogin_SplashScreen_C_ShowUI_Params
{
};

// Function Login_SplashScreen.Login_SplashScreen_C.InitAuthorizationUI
struct ULogin_SplashScreen_C_InitAuthorizationUI_Params
{
};

// Function Login_SplashScreen.Login_SplashScreen_C.Construct
struct ULogin_SplashScreen_C_Construct_Params
{
};

// Function Login_SplashScreen.Login_SplashScreen_C.AnimationFinish
struct ULogin_SplashScreen_C_AnimationFinish_Params
{
};

// Function Login_SplashScreen.Login_SplashScreen_C.ExecuteUbergraph_Login_SplashScreen
struct ULogin_SplashScreen_C_ExecuteUbergraph_Login_SplashScreen_Params
{
	int                                                EntryPoint;                                               // (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData)
};

// Function Login_SplashScreen.Login_SplashScreen_C.startGameSounds__DelegateSignature
struct ULogin_SplashScreen_C_startGameSounds__DelegateSignature_Params
{
};

}

