#pragma once

// PlayerUnknown's Battlegrounds (0.27.0) SDK Generated By @IDRAGONCHEATS
namespace SDK
{
//---------------------------------------------------------------------------
//Script Structs
//---------------------------------------------------------------------------

// UserDefinedStruct BP_STRUCT_TeamUpRingsChange.BP_STRUCT_TeamUpRingsChange
// 0x0010
struct FBP_STRUCT_TeamUpRingsChange
{
	TArray<struct FString>                             BP_ARRAY_CurrentTeamMemberGidList_0_D2CDCC1D471B89B9F0AB7EA00B0FC54F;// 0x0000(0x000C) (Edit, BlueprintVisible, ZeroConstructor)
	int                                                teamMemberNum_1_77DA28B0499A92734B37ADB6DAF70618;         // 0x000C(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
};

}

