// PlayerUnknown's Battlegrounds (0.27.0) SDK Generated By @IDRAGONCHEATS
#include "../SDK.hpp"

namespace SDK
{
//---------------------------------------------------------------------------
//Functions
//---------------------------------------------------------------------------

// Function UAEOptimizeTools.UAEOTConsoleCommandObject.UOTStartReportSlatePaint
// (Final, Exec, Native, Private, BlueprintCallable, Const)

void UUAEOTConsoleCommandObject::UOTStartReportSlatePaint()
{
	static UFunction *pFunc = 0;
	if (!pFunc)
		pFunc = UObject::FindObject<UFunction>("Function UAEOptimizeTools.UAEOTConsoleCommandObject.UOTStartReportSlatePaint");

	UUAEOTConsoleCommandObject_UOTStartReportSlatePaint_Params params;

	auto flags = pFunc->FunctionFlags;
	pFunc->FunctionFlags |= 0x400;

	UObject *currentObj = (UObject *) this;
	currentObj->ProcessEvent(pFunc, &params);

	pFunc->FunctionFlags = flags;
}

// Function UAEOptimizeTools.UAEOTConsoleCommandObject.UOTReportUIObject
// (Final, Exec, Native, Private, BlueprintCallable, Const)
// Parameters:
// struct FString                 InFileName                     (Parm, ZeroConstructor)

void UUAEOTConsoleCommandObject::UOTReportUIObject(const struct FString& InFileName)
{
	static UFunction *pFunc = 0;
	if (!pFunc)
		pFunc = UObject::FindObject<UFunction>("Function UAEOptimizeTools.UAEOTConsoleCommandObject.UOTReportUIObject");

	UUAEOTConsoleCommandObject_UOTReportUIObject_Params params;
	params.InFileName = InFileName;

	auto flags = pFunc->FunctionFlags;
	pFunc->FunctionFlags |= 0x400;

	UObject *currentObj = (UObject *) this;
	currentObj->ProcessEvent(pFunc, &params);

	pFunc->FunctionFlags = flags;
}

// Function UAEOptimizeTools.UAEOTConsoleCommandObject.UOTReportObjectPath
// (Final, Exec, Native, Private, BlueprintCallable, Const)
// Parameters:
// struct FString                 InFileName                     (Parm, ZeroConstructor)

void UUAEOTConsoleCommandObject::UOTReportObjectPath(const struct FString& InFileName)
{
	static UFunction *pFunc = 0;
	if (!pFunc)
		pFunc = UObject::FindObject<UFunction>("Function UAEOptimizeTools.UAEOTConsoleCommandObject.UOTReportObjectPath");

	UUAEOTConsoleCommandObject_UOTReportObjectPath_Params params;
	params.InFileName = InFileName;

	auto flags = pFunc->FunctionFlags;
	pFunc->FunctionFlags |= 0x400;

	UObject *currentObj = (UObject *) this;
	currentObj->ProcessEvent(pFunc, &params);

	pFunc->FunctionFlags = flags;
}

// Function UAEOptimizeTools.UAEOTConsoleCommandObject.UOTReportObjectCount
// (Final, Exec, Native, Private, BlueprintCallable, Const)
// Parameters:
// struct FString                 InFileName                     (Parm, ZeroConstructor)

void UUAEOTConsoleCommandObject::UOTReportObjectCount(const struct FString& InFileName)
{
	static UFunction *pFunc = 0;
	if (!pFunc)
		pFunc = UObject::FindObject<UFunction>("Function UAEOptimizeTools.UAEOTConsoleCommandObject.UOTReportObjectCount");

	UUAEOTConsoleCommandObject_UOTReportObjectCount_Params params;
	params.InFileName = InFileName;

	auto flags = pFunc->FunctionFlags;
	pFunc->FunctionFlags |= 0x400;

	UObject *currentObj = (UObject *) this;
	currentObj->ProcessEvent(pFunc, &params);

	pFunc->FunctionFlags = flags;
}

// Function UAEOptimizeTools.UAEOTConsoleCommandObject.UOTReportObjectAll
// (Final, Exec, Native, Private, BlueprintCallable, Const)
// Parameters:
// struct FString                 InFileName                     (Parm, ZeroConstructor)

void UUAEOTConsoleCommandObject::UOTReportObjectAll(const struct FString& InFileName)
{
	static UFunction *pFunc = 0;
	if (!pFunc)
		pFunc = UObject::FindObject<UFunction>("Function UAEOptimizeTools.UAEOTConsoleCommandObject.UOTReportObjectAll");

	UUAEOTConsoleCommandObject_UOTReportObjectAll_Params params;
	params.InFileName = InFileName;

	auto flags = pFunc->FunctionFlags;
	pFunc->FunctionFlags |= 0x400;

	UObject *currentObj = (UObject *) this;
	currentObj->ProcessEvent(pFunc, &params);

	pFunc->FunctionFlags = flags;
}

// Function UAEOptimizeTools.UAEOTConsoleCommandObject.UOTReportActor
// (Final, Exec, Native, Private, BlueprintCallable, Const)
// Parameters:
// struct FString                 InFileName                     (Parm, ZeroConstructor)

void UUAEOTConsoleCommandObject::UOTReportActor(const struct FString& InFileName)
{
	static UFunction *pFunc = 0;
	if (!pFunc)
		pFunc = UObject::FindObject<UFunction>("Function UAEOptimizeTools.UAEOTConsoleCommandObject.UOTReportActor");

	UUAEOTConsoleCommandObject_UOTReportActor_Params params;
	params.InFileName = InFileName;

	auto flags = pFunc->FunctionFlags;
	pFunc->FunctionFlags |= 0x400;

	UObject *currentObj = (UObject *) this;
	currentObj->ProcessEvent(pFunc, &params);

	pFunc->FunctionFlags = flags;
}

// Function UAEOptimizeTools.UAEOTConsoleCommandObject.UOTObjectReports
// (Final, Exec, Native, Private, BlueprintCallable, Const)
// Parameters:
// struct FString                 InFileName                     (Parm, ZeroConstructor)

void UUAEOTConsoleCommandObject::UOTObjectReports(const struct FString& InFileName)
{
	static UFunction *pFunc = 0;
	if (!pFunc)
		pFunc = UObject::FindObject<UFunction>("Function UAEOptimizeTools.UAEOTConsoleCommandObject.UOTObjectReports");

	UUAEOTConsoleCommandObject_UOTObjectReports_Params params;
	params.InFileName = InFileName;

	auto flags = pFunc->FunctionFlags;
	pFunc->FunctionFlags |= 0x400;

	UObject *currentObj = (UObject *) this;
	currentObj->ProcessEvent(pFunc, &params);

	pFunc->FunctionFlags = flags;
}

// Function UAEOptimizeTools.UAEOTConsoleCommandObject.UOTEndReportSlatePaintEnd
// (Final, Exec, Native, Private, BlueprintCallable, Const)
// Parameters:
// int                            Filter                         (Parm, ZeroConstructor, IsPlainOldData)
// struct FString                 Filename                       (Parm, ZeroConstructor)

void UUAEOTConsoleCommandObject::UOTEndReportSlatePaintEnd(int Filter, const struct FString& Filename)
{
	static UFunction *pFunc = 0;
	if (!pFunc)
		pFunc = UObject::FindObject<UFunction>("Function UAEOptimizeTools.UAEOTConsoleCommandObject.UOTEndReportSlatePaintEnd");

	UUAEOTConsoleCommandObject_UOTEndReportSlatePaintEnd_Params params;
	params.Filter = Filter;
	params.Filename = Filename;

	auto flags = pFunc->FunctionFlags;
	pFunc->FunctionFlags |= 0x400;

	UObject *currentObj = (UObject *) this;
	currentObj->ProcessEvent(pFunc, &params);

	pFunc->FunctionFlags = flags;
}

// Function UAEOptimizeTools.UAEOTConsoleCommandObject.ReportClassObjectInfo
// (Final, Exec, Native, Private, Const)
// Parameters:
// struct FString                 ClassName                      (Parm, ZeroConstructor)

void UUAEOTConsoleCommandObject::ReportClassObjectInfo(const struct FString& ClassName)
{
	static UFunction *pFunc = 0;
	if (!pFunc)
		pFunc = UObject::FindObject<UFunction>("Function UAEOptimizeTools.UAEOTConsoleCommandObject.ReportClassObjectInfo");

	UUAEOTConsoleCommandObject_ReportClassObjectInfo_Params params;
	params.ClassName = ClassName;

	auto flags = pFunc->FunctionFlags;
	pFunc->FunctionFlags |= 0x400;

	UObject *currentObj = (UObject *) this;
	currentObj->ProcessEvent(pFunc, &params);

	pFunc->FunctionFlags = flags;
}

}

