#pragma once

// PlayerUnknown's Battlegrounds (0.27.0) SDK Generated By @IDRAGONCHEATS
namespace SDK
{
//---------------------------------------------------------------------------
//Classes
//---------------------------------------------------------------------------

// ScriptBlueprintGeneratedClass bp_lobby_friend.bp_lobby_friend_C
// 0x090C (0x0C0C - 0x0300)
class Abp_lobby_friend_C : public ALuaClassObj
{
public:
	class UScriptContextComponent*                     Generated_ScriptContext;                                  // 0x0300(0x0004) (BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData)
	TArray<struct FBP_STRUCT_FriendProfile>            BP_ARRAY_Recent_Like_Profile;                             // 0x0304(0x000C) (Edit, BlueprintVisible, ZeroConstructor)
	int                                                BP_Inner_Friend_Scroll_End;                               // 0x0310(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	struct FString                                     BP_Delete_Friend_Name;                                    // 0x0314(0x000C) (Edit, BlueprintVisible, ZeroConstructor)
	TArray<struct FBP_STRUCT_FriendLiteProfile>        BP_ARRAY_SendItem_Friend_Lite_Profile;                    // 0x0320(0x000C) (Edit, BlueprintVisible, ZeroConstructor)
	int                                                BP_Friend_Add_Index;                                      // 0x032C(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	struct FString                                     BP_DELETE_FRIEND_BLACK_NAME;                              // 0x0330(0x000C) (Edit, BlueprintVisible, ZeroConstructor)
	TArray<struct FBP_STRUCT_Lobby_Friend_Apply_Data>  BP_ARRAY_Apply_Friend_Detail_Profile;                     // 0x033C(0x000C) (Edit, BlueprintVisible, ZeroConstructor)
	int                                                BP_Verify_MaxWordCount;                                   // 0x0348(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	struct FString                                     BP_Friend_Intimacy_Gid;                                   // 0x034C(0x000C) (Edit, BlueprintVisible, ZeroConstructor)
	TArray<struct FBP_STRUCT_FriendLiteProfile>        BP_ARRAY_Inner_Friend_Lite_Profile;                       // 0x0358(0x000C) (Edit, BlueprintVisible, ZeroConstructor)
	TArray<struct FBP_STRUCT_FriendProfile>            BP_ARRAY_Inner_Friend_Detail_Profile;                     // 0x0364(0x000C) (Edit, BlueprintVisible, ZeroConstructor)
	int                                                BP_NearBy_Gender_Filter;                                  // 0x0370(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	TArray<struct FBP_STRUCT_FriendLiteProfile>        BP_ARRAY_Apply_Friend_Lite_Profile;                       // 0x0374(0x000C) (Edit, BlueprintVisible, ZeroConstructor)
	struct FString                                     BP_Friend_Search_Nation;                                  // 0x0380(0x000C) (Edit, BlueprintVisible, ZeroConstructor)
	TArray<struct FBP_STRUCT_FriendLiteProfile>        BP_ARRAY_Recent_Teammate_Lite_Profile;                    // 0x038C(0x000C) (Edit, BlueprintVisible, ZeroConstructor)
	int                                                BP_Friend_Search_Language;                                // 0x0398(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	struct FString                                     BP_FriendSystem_Present_Coin_Friend_ID;                   // 0x039C(0x000C) (Edit, BlueprintVisible, ZeroConstructor)
	TArray<struct FBP_STRUCT_FriendProfile>            BP_ARRAY_Plat_Friend_Detail_Profile;                      // 0x03A8(0x000C) (Edit, BlueprintVisible, ZeroConstructor)
	struct FString                                     BP_RSPAdd_Friend_ID;                                      // 0x03B4(0x000C) (Edit, BlueprintVisible, ZeroConstructor)
	TArray<struct FBP_STRUCT_FriendProfile>            BP_ARRAY_Recent_Teammate_Profile;                         // 0x03C0(0x000C) (Edit, BlueprintVisible, ZeroConstructor)
	int                                                BP_Friend_Search_PlayTime;                                // 0x03CC(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	struct FString                                     BP_Add_Friend_Verify;                                     // 0x03D0(0x000C) (Edit, BlueprintVisible, ZeroConstructor)
	bool                                               BP_Friend_Is_Show;                                        // 0x03DC(0x0001) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	unsigned char                                      UnknownData00[0x3];                                       // 0x03DD(0x0003) MISSED OFFSET
	struct FBP_STRUCT_Intimacy_Data                    BP_STRUCT_Intimacy_Data;                                  // 0x03E0(0x0094) (Edit, BlueprintVisible)
	struct FString                                     BP_RSPAdd_OP;                                             // 0x0474(0x000C) (Edit, BlueprintVisible, ZeroConstructor)
	struct FString                                     BP_Delete_Friend_ID;                                      // 0x0480(0x000C) (Edit, BlueprintVisible, ZeroConstructor)
	struct FBP_STRUCT_FriendProfile                    BP_STRUCT_FriendProfile;                                  // 0x048C(0x01C4) (Edit, BlueprintVisible)
	TArray<struct FBP_STRUCT_FriendLiteProfile>        BP_ARRAY_Search_Friend_Lite_Profile;                      // 0x0650(0x000C) (Edit, BlueprintVisible, ZeroConstructor)
	TArray<struct FBP_STRUCT_FriendLiteProfile>        BP_ARRAY_Blacklist_Friend_Lite_Profile;                   // 0x065C(0x000C) (Edit, BlueprintVisible, ZeroConstructor)
	struct FBP_STRUCT_FriendLiteProfile                BP_STRUCT_FriendLiteProfile;                              // 0x0668(0x000C) (Edit, BlueprintVisible)
	int                                                BP_Apply_Friend_Scroll_End;                               // 0x0674(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	TArray<struct FBP_STRUCT_Intimacy_Data>            BP_ARRAY_Intimacy_Data;                                   // 0x0678(0x000C) (Edit, BlueprintVisible, ZeroConstructor)
	TArray<struct FBP_STRUCT_Lobby_Friend_Search_Data> BP_ARRAY_Search_Friend_Detail_Profile;                    // 0x0684(0x000C) (Edit, BlueprintVisible, ZeroConstructor)
	int                                                BP_MaxDeleteFriendCount;                                  // 0x0690(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	bool                                               BP_IsInBatchDelete;                                       // 0x0694(0x0001) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	unsigned char                                      UnknownData01[0x3];                                       // 0x0695(0x0003) MISSED OFFSET
	TArray<struct FBP_STRUCT_FriendProfile>            BP_ARRAY_Apply_Friend_Profile;                            // 0x0698(0x000C) (Edit, BlueprintVisible, ZeroConstructor)
	struct FString                                     BP_Friend_SearchName;                                     // 0x06A4(0x000C) (Edit, BlueprintVisible, ZeroConstructor)
	int                                                BP_Friend_Search_Tendency;                                // 0x06B0(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	struct FString                                     BP_DELETE_FRIEND_BLACK_ID;                                // 0x06B4(0x000C) (Edit, BlueprintVisible, ZeroConstructor)
	int                                                BP_BlackList_Friend_Scroll_Start;                         // 0x06C0(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	int                                                BP_Recent_Teammate_ScrollEnd;                             // 0x06C4(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	struct FBP_STRUCT_Search_Data                      BP_STRUCT_Search_Data;                                    // 0x06C8(0x0014) (Edit, BlueprintVisible)
	int                                                BP_Friend_Intimacy_Delete_Relation;                       // 0x06DC(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	TArray<struct FBP_STRUCT_FriendProfile>            BP_ARRAY_Search_Friend_Profile;                           // 0x06E0(0x000C) (Edit, BlueprintVisible, ZeroConstructor)
	int                                                BP_Add_Friend_Gender;                                     // 0x06EC(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	TArray<struct FBP_STRUCT_FriendLiteProfile>        BP_ARRAY_Plat_Friend_Lite_Profile;                        // 0x06F0(0x000C) (Edit, BlueprintVisible, ZeroConstructor)
	struct FBP_STRUCT_EnumRecentLikeOp                 BP_STRUCT_EnumRecentLikeOp;                               // 0x06FC(0x000C) (Edit, BlueprintVisible)
	struct FString                                     BP_XY_API_URL;                                            // 0x0708(0x000C) (Edit, BlueprintVisible, ZeroConstructor)
	int                                                BP_Friend_Panel_Tab_Index;                                // 0x0714(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	int                                                BP_Friend_Search_PreServer;                               // 0x0718(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	bool                                               BP_Friend_Intimacy_Apply_Has_New;                         // 0x071C(0x0001) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	unsigned char                                      UnknownData02[0x3];                                       // 0x071D(0x0003) MISSED OFFSET
	int                                                BP_Friend_Search_PlayDate;                                // 0x0720(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	int                                                BP_Friend_Intimacy_Op;                                    // 0x0724(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	struct FString                                     BP_Friend_Intimacy_NickName;                              // 0x0728(0x000C) (Edit, BlueprintVisible, ZeroConstructor)
	struct FString                                     BP_Friend_Intimacy_Delete_Gid;                            // 0x0734(0x000C) (Edit, BlueprintVisible, ZeroConstructor)
	int                                                BP_Friend_UpdateInnerIndex;                               // 0x0740(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	struct FString                                     BP_Friend_Intimacy_Delete_NickName;                       // 0x0744(0x000C) (Edit, BlueprintVisible, ZeroConstructor)
	int                                                BP_Friend_Intimacy_Delete_State;                          // 0x0750(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	int                                                BP_SendItem_Friend_Scroll_Start;                          // 0x0754(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	TArray<struct FBP_STRUCT_FriendProfile>            BP_ARRAY_Plat_Friend_Profile;                             // 0x0758(0x000C) (Edit, BlueprintVisible, ZeroConstructor)
	int                                                BP_Search_Friend_Scroll_End;                              // 0x0764(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	int                                                BP_Friend_Intimacy_Relation;                              // 0x0768(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	bool                                               BP_Friend_Process_Add_Friend;                             // 0x076C(0x0001) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	unsigned char                                      UnknownData03[0x3];                                       // 0x076D(0x0003) MISSED OFFSET
	struct FString                                     BP_Friend_Send_Item_Friend_ID;                            // 0x0770(0x000C) (Edit, BlueprintVisible, ZeroConstructor)
	bool                                               BP_Friend_Search_Is_Same_City;                            // 0x077C(0x0001) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	unsigned char                                      UnknownData04[0x3];                                       // 0x077D(0x0003) MISSED OFFSET
	int                                                BP_Platform_Friend_Scroll_Start;                          // 0x0780(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	struct FBP_STRUCT_Lobby_Friend_Apply_Data          BP_STRUCT_Lobby_Friend_Apply_Data;                        // 0x0784(0x0118) (Edit, BlueprintVisible)
	struct FBP_STRUCT_Lobby_Friend_Common_Data         BP_STRUCT_Lobby_Friend_Common_Data;                       // 0x089C(0x00FC) (Edit, BlueprintVisible)
	TArray<struct FBP_STRUCT_FriendProfile>            BP_ARRAY_ALL_Friend_SendItem_Profile;                     // 0x0998(0x000C) (Edit, BlueprintVisible, ZeroConstructor)
	TArray<struct FBP_STRUCT_Intimacy_DetailData>      BP_Array_Intimacy_DetailData;                             // 0x09A4(0x000C) (Edit, BlueprintVisible, ZeroConstructor)
	int                                                BP_SelecterDeleteFriendCount;                             // 0x09B0(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	struct FString                                     BP_NearBy_SelfUID;                                        // 0x09B4(0x000C) (Edit, BlueprintVisible, ZeroConstructor)
	TArray<struct FBP_STRUCT_FriendProfile>            BP_ARRAY_SendItem_Friend_Detail_Profile;                  // 0x09C0(0x000C) (Edit, BlueprintVisible, ZeroConstructor)
	int                                                BP_Friend_Intimacy_Build_Relation;                        // 0x09CC(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	int                                                BP_Platform_Friend_Scroll_End;                            // 0x09D0(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	struct FString                                     BP_FriendSystem_SelectedFriendNickNameAddQQFriend;        // 0x09D4(0x000C) (Edit, BlueprintVisible, ZeroConstructor)
	bool                                               BP_FRIEND_IS_WATCHING_OPEN;                               // 0x09E0(0x0001) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	unsigned char                                      UnknownData05[0x3];                                       // 0x09E1(0x0003) MISSED OFFSET
	int                                                BP_SendItem_Friend_Scroll_End;                            // 0x09E4(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	bool                                               BP_Friend_Intimacy_Relation_Available;                    // 0x09E8(0x0001) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	unsigned char                                      UnknownData06[0x3];                                       // 0x09E9(0x0003) MISSED OFFSET
	int                                                BP_Friend_Send_Item_ResID;                                // 0x09EC(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	int                                                BP_Friend_Send_Item_Count;                                // 0x09F0(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	TArray<struct FBP_STRUCT_FriendProfile>            BP_ARRAY_Near_By_Profile;                                 // 0x09F4(0x000C) (Edit, BlueprintVisible, ZeroConstructor)
	int                                                BP_Friend_Send_Item_Expire;                               // 0x0A00(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	struct FString                                     BP_Friend_Intimacy_Build_Gid;                             // 0x0A04(0x000C) (Edit, BlueprintVisible, ZeroConstructor)
	struct FString                                     BP_FRIEND_WATCH_ID;                                       // 0x0A10(0x000C) (Edit, BlueprintVisible, ZeroConstructor)
	TArray<struct FBP_STRUCT_FriendProfile>            BP_ARRAY_Near_By_Gender_Filter_Profile;                   // 0x0A1C(0x000C) (Edit, BlueprintVisible, ZeroConstructor)
	TArray<struct FBP_STRUCT_FriendProfile>            BP_ARRAY_Recent_Teammate_Detail_Profile;                  // 0x0A28(0x000C) (Edit, BlueprintVisible, ZeroConstructor)
	int                                                BP_Friend_Search_Segment;                                 // 0x0A34(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	struct FString                                     BP_FRIEND_CHAT_ID;                                        // 0x0A38(0x000C) (Edit, BlueprintVisible, ZeroConstructor)
	struct FBP_STRUCT_Lobby_Friend_Search_Data         BP_STRUCT_Lobby_Friend_Search_Data;                       // 0x0A44(0x0114) (Edit, BlueprintVisible)
	TArray<struct FBP_STRUCT_FriendProfile>            BP_ARRAY_Inner_Friend_Profile;                            // 0x0B58(0x000C) (Edit, BlueprintVisible, ZeroConstructor)
	TArray<struct FBP_STRUCT_Search_Data>              BP_Array_Search_Data;                                     // 0x0B64(0x000C) (Edit, BlueprintVisible, ZeroConstructor)
	struct FBP_STRUCT_Intimacy_DetailData              BP_STRUCT_Intimacy_DetailData;                            // 0x0B70(0x0018) (Edit, BlueprintVisible)
	struct FString                                     BP_NearBy_Empty_Tips;                                     // 0x0B88(0x000C) (Edit, BlueprintVisible, ZeroConstructor)
	TArray<struct FBP_STRUCT_FriendProfile>            BP_ARRAY_Blacklist_Friend_Detail_Profile;                 // 0x0B94(0x000C) (Edit, BlueprintVisible, ZeroConstructor)
	bool                                               BP_LobbyFriend_Master_RedPoint;                           // 0x0BA0(0x0001) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	unsigned char                                      UnknownData07[0x3];                                       // 0x0BA1(0x0003) MISSED OFFSET
	int                                                BP_Friend_Search_Gender;                                  // 0x0BA4(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	bool                                               BP_NearBy_Location_Open;                                  // 0x0BA8(0x0001) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	unsigned char                                      UnknownData08[0x3];                                       // 0x0BA9(0x0003) MISSED OFFSET
	TArray<struct FString>                             BP_ARRAY_LobbyFriendDeleteFriendIDList;                   // 0x0BAC(0x000C) (Edit, BlueprintVisible, ZeroConstructor)
	int                                                BP_Friend_Platform;                                       // 0x0BB8(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	int                                                BP_BlackList_Friend_Scroll_End;                           // 0x0BBC(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	struct FString                                     BP_Add_Friend_ID;                                         // 0x0BC0(0x000C) (Edit, BlueprintVisible, ZeroConstructor)
	int                                                BP_Inner_Friend_Scroll_Start;                             // 0x0BCC(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	TArray<struct FBP_STRUCT_FriendProfile>            BP_ARRAY_Blacklist_Friend_Profile;                        // 0x0BD0(0x000C) (Edit, BlueprintVisible, ZeroConstructor)
	struct FString                                     BP_NearBy_Empty_Tips_Location_Close;                      // 0x0BDC(0x000C) (Edit, BlueprintVisible, ZeroConstructor)
	bool                                               BP_Friend_Send_Item;                                      // 0x0BE8(0x0001) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	unsigned char                                      UnknownData09[0x3];                                       // 0x0BE9(0x0003) MISSED OFFSET
	int                                                BP_Recent_Teammate_ScrollStart;                           // 0x0BEC(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	int                                                BP_Apply_Friend_Scroll_Start;                             // 0x0BF0(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	int                                                BP_Search_Friend_Scroll_Start;                            // 0x0BF4(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	int                                                BP_Friend_UpdatePlatIndex;                                // 0x0BF8(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	struct FString                                     BP_FRIEND_PROFILE_ID;                                     // 0x0BFC(0x000C) (Edit, BlueprintVisible, ZeroConstructor)
	class USceneComponent*                             DefaultSceneRoot;                                         // 0x0C08(0x0004) (BlueprintVisible, ZeroConstructor, IsPlainOldData)

	static UClass* StaticClass()
	{
		static UClass *pStaticClass = 0;
		if (!pStaticClass)
			 pStaticClass = UObject::FindClass("ScriptBlueprintGeneratedClass bp_lobby_friend.bp_lobby_friend_C");
		return pStaticClass;
	}


	void EventOpenFriendRuleDescriptionPanel_NoFetch();
	void EventOpenFriendRuleDescriptionPanel();
	void EventNearByCloseLocation_NoFetch();
	void EventNearByCloseLocation();
	void EventGetRecentTeammateList_NoFetch();
	void EventGetRecentTeammateList();
	void EventLobbyFriendLabelSearchReq_NoFetch();
	void EventLobbyFriendLabelSearchReq();
	void EventEnterBatchDeleteInnerFriend_NoFetch();
	void EventEnterBatchDeleteInnerFriend();
	void EventLobbyFriendScrollSearchList_NoFetch();
	void EventLobbyFriendScrollSearchList();
	void EventHideLobbyFriendUI_NoFetch();
	void EventHideLobbyFriendUI();
	void EventLobbyFriendDeleteBlackReq_NoFetch();
	void EventLobbyFriendDeleteBlackReq();
	void EventFetchInfo_NoFetch();
	void EventFetchInfo();
	void EventLobbyFriendAddFriendReqList_NoFetch();
	void EventLobbyFriendAddFriendReqList();
	void EventShowSendAddFriendRequestTips_NoFetch();
	void EventShowSendAddFriendRequestTips();
	void EventLeaveBatchDeleteInnerFriend_NoFetch();
	void EventLeaveBatchDeleteInnerFriend();
	void EventFriendOnTapChange_NoFetch();
	void EventFriendOnTapChange();
	void EventSelectBatchDeleteInnerFriend_NoFetch();
	void EventSelectBatchDeleteInnerFriend();
	void EventUnselectBatchDeleteInnerFriend_NoFetch();
	void EventUnselectBatchDeleteInnerFriend();
	void EventConfirmBatchDeleteInnerFriend_NoFetch();
	void EventConfirmBatchDeleteInnerFriend();
	void EventLobbyFriendFetchFriendList_NoFetch();
	void EventLobbyFriendFetchFriendList();
	void EventLobbyFriendBlackListScroll_NoFetch();
	void EventLobbyFriendBlackListScroll();
	void EventLobbyFriendRespondApply_NoFetch();
	void EventLobbyFriendRespondApply();
	void EventRecentTeammateScrollApplyList_NoFetch();
	void EventRecentTeammateScrollApplyList();
	void EventLobbyFriendIntimacyReq_NoFetch();
	void EventLobbyFriendIntimacyReq();
	void EventLobbyFriendReplyRelationReq_NoFetch();
	void EventLobbyFriendReplyRelationReq();
	void EventLobbyFriendScrollInnerList_NoFetch();
	void EventLobbyFriendScrollInnerList();
	void EventLobbyFriendBuildRelationReq_NoFetch();
	void EventLobbyFriendBuildRelationReq();
	void EventOpenMyCardPanelInFriendPanel_NoFetch();
	void EventOpenMyCardPanelInFriendPanel();
	void EventOpenIntimacyDescriptionPanel_NoFetch();
	void EventOpenIntimacyDescriptionPanel();
	void EventLobbyFriendWatch_NoFetch();
	void EventLobbyFriendWatch();
	void EventNearByOpenLocation_NoFetch();
	void EventNearByOpenLocation();
	void EventOpenNearByPanel_NoFetch();
	void EventOpenNearByPanel();
	void EventNearByUpdateFilterArray_NoFetch();
	void EventNearByUpdateFilterArray();
	void EventLobbyFriendSearchReq_NoFetch();
	void EventLobbyFriendSearchReq();
	void EventHideMasterPanel_NoFetch();
	void EventHideMasterPanel();
	void EventLobbyFriendApplyReq_NoFetch();
	void EventLobbyFriendApplyReq();
	void EventLobbyFriendDeleteReq_NoFetch();
	void EventLobbyFriendDeleteReq();
	void EventLobbyFriendMasterNotOpen_NoFetch();
	void EventLobbyFriendMasterNotOpen();
	void EventSetXYAPIShowRedPoint_NoFetch();
	void EventSetXYAPIShowRedPoint();
	void EventLobbySendItemReq_NoFetch();
	void EventLobbySendItemReq();
	void EventSetXYAPIHideRedPoint_NoFetch();
	void EventSetXYAPIHideRedPoint();
	void EventFetchNewNearByPersonInfoList_NoFetch();
	void EventFetchNewNearByPersonInfoList();
	void EventLobbySendFriendFinish_NoFetch();
	void EventLobbySendFriendFinish();
	void EventLobbyShowRecentLikePanel_NoFetch();
	void EventLobbyShowRecentLikePanel();
	void EventLobbyPresentCoinReq_NoFetch();
	void EventLobbyPresentCoinReq();
	void EventXYAPISetUrl_NoFetch();
	void EventXYAPISetUrl();
	void EventLobbyFriendProfileReq_NoFetch();
	void EventLobbyFriendProfileReq();
	void EventLobbyFriendSendItemList_NoFetch();
	void EventLobbyFriendSendItemList();
	void EventCheckWatchingSwitch_NoFetch();
	void EventCheckWatchingSwitch();
	void EventLobbyFriendScrollApplyList_NoFetch();
	void EventLobbyFriendScrollApplyList();
	void EventLobbyFriendRelationClick_NoFetch();
	void EventLobbyFriendRelationClick();
	void EventLobbyFriendScrollPlatList_NoFetch();
	void EventLobbyFriendScrollPlatList();
	void EventLobbyFriendAddQQFriend_NoFetch();
	void EventLobbyFriendAddQQFriend();
	void EventLobbyFriendDeleteRelationReq_NoFetch();
	void EventLobbyFriendDeleteRelationReq();
	void EventLobbyFriendChat_NoFetch();
	void EventLobbyFriendChat();
	void EventOpenMasterPanel_NoFetch();
	void EventOpenMasterPanel();
	void EventLobbyFriendGetBlackListReq_NoFetch();
	void EventLobbyFriendGetBlackListReq();
	void UserConstructionScript();
};


}

