#pragma once

// PlayerUnknown's Battlegrounds (0.27.0) SDK Generated By @IDRAGONCHEATS
namespace SDK
{
//---------------------------------------------------------------------------
//Script Structs
//---------------------------------------------------------------------------

// UserDefinedStruct BP_STRUCT_Rank_Alias_Info.BP_STRUCT_Rank_Alias_Info
// 0x0038
struct FBP_STRUCT_Rank_Alias_Info
{
	int                                                aliasId_0_539A9B00799ED74E1D0B142E0A68F714;               // 0x0000(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	struct FString                                     roleNation_1_6C9FB40051D5FFF2144E6E750F47DE0E;            // 0x0004(0x000C) (Edit, BlueprintVisible, ZeroConstructor)
	struct FString                                     title_2_4F15D5C002CFF8272B65E96D00F54E55;                 // 0x0010(0x000C) (Edit, BlueprintVisible, ZeroConstructor)
	struct FString                                     pathUrl_3_06BD85406426417F4854823908CDAC7C;               // 0x001C(0x000C) (Edit, BlueprintVisible, ZeroConstructor)
	int                                                quality_4_487C0F804C3B61FE6C0AFEEB06F16049;               // 0x0028(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	struct FString                                     uid_5_47BC5DC052725E2161CA4F0C0770F5B4;                   // 0x002C(0x000C) (Edit, BlueprintVisible, ZeroConstructor)
};

}

