#pragma once

// PlayerUnknown's Battlegrounds (0.27.0) SDK Generated By @IDRAGONCHEATS
namespace SDK
{
//---------------------------------------------------------------------------
//Enums
//---------------------------------------------------------------------------

// Enum UAESharedModule.EUAEBlackboardType
enum class EUAEBlackboardType : uint8_t
{
	EBT_Object                     = 0,
	EBT_WeakObjectPtr              = 1,
	EBT_Class                      = 2,
	EBT_Enum                       = 3,
	EBT_Int                        = 4,
	EBT_UInt                       = 5,
	EBT_Float                      = 6,
	EBT_Bool                       = 7,
	EBT_String                     = 8,
	EBT_Name                       = 9,
	EBT_Vector                     = 10,
	EBT_Rotator                    = 11,
	EBT_MAX                        = 12
};



//---------------------------------------------------------------------------
//Script Structs
//---------------------------------------------------------------------------

// ScriptStruct UAESharedModule.UAEBlackboardKeySelector
// 0x0008
struct FUAEBlackboardKeySelector
{
	struct FName                                       SelectedKeyName;                                          // 0x0000(0x0008) (Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, IsPlainOldData)
};

// ScriptStruct UAESharedModule.UAEBlackboardParameter
// 0x0010
struct FUAEBlackboardParameter
{
	struct FName                                       Name;                                                     // 0x0000(0x0008) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	TEnumAsByte<EUAEBlackboardType>                    Type;                                                     // 0x0008(0x0001) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	unsigned char                                      UnknownData00[0x7];                                       // 0x0009(0x0007) MISSED OFFSET
};

}

