#pragma once

// PlayerUnknown's Battlegrounds (0.27.0) SDK Generated By @IDRAGONCHEATS
#include "../SDK.hpp"

namespace SDK
{
//---------------------------------------------------------------------------
//Parameters
//---------------------------------------------------------------------------

// Function Global_Bp.Global_Bp_C.ShowItemPreviewPress
struct UGlobal_Bp_C_ShowItemPreviewPress_Params
{
};

// Function Global_Bp.Global_Bp_C.ShowItemPreviewClick
struct UGlobal_Bp_C_ShowItemPreviewClick_Params
{
	int                                                ItemID;                                                   // (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData)
};

// Function Global_Bp.Global_Bp_C.SetGlobalConfigData
struct UGlobal_Bp_C_SetGlobalConfigData_Params
{
};

// Function Global_Bp.Global_Bp_C.DestroyLobbyCameras
struct UGlobal_Bp_C_DestroyLobbyCameras_Params
{
};

// Function Global_Bp.Global_Bp_C.HideLobbyCamera
struct UGlobal_Bp_C_HideLobbyCamera_Params
{
};

// Function Global_Bp.Global_Bp_C.ShowLobbyCamera
struct UGlobal_Bp_C_ShowLobbyCamera_Params
{
};

// Function Global_Bp.Global_Bp_C.SetShadowDistanceScale
struct UGlobal_Bp_C_SetShadowDistanceScale_Params
{
};

// Function Global_Bp.Global_Bp_C.GetShadowDistanceScale
struct UGlobal_Bp_C_GetShadowDistanceScale_Params
{
};

// Function Global_Bp.Global_Bp_C.SetCloseLocation
struct UGlobal_Bp_C_SetCloseLocation_Params
{
};

// Function Global_Bp.Global_Bp_C.SetNearByRedPoint
struct UGlobal_Bp_C_SetNearByRedPoint_Params
{
};

// Function Global_Bp.Global_Bp_C.GetCorpsIconTexture
struct UGlobal_Bp_C_GetCorpsIconTexture_Params
{
	int                                                IconID;                                                   // (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData)
	class UTexture2D*                                  Value;                                                    // (Parm, OutParm, ZeroConstructor, IsPlainOldData)
};

// Function Global_Bp.Global_Bp_C.GetGlobalConfigData
struct UGlobal_Bp_C_GetGlobalConfigData_Params
{
};

// Function Global_Bp.Global_Bp_C.TryPlayAdvertise
struct UGlobal_Bp_C_TryPlayAdvertise_Params
{
};

// Function Global_Bp.Global_Bp_C.PlayAdvertise
struct UGlobal_Bp_C_PlayAdvertise_Params
{
};

// Function Global_Bp.Global_Bp_C.TryLoadAdvertise
struct UGlobal_Bp_C_TryLoadAdvertise_Params
{
};

// Function Global_Bp.Global_Bp_C.LoadAdvertise
struct UGlobal_Bp_C_LoadAdvertise_Params
{
};

// Function Global_Bp.Global_Bp_C.GetLocalizeStringWithNum
struct UGlobal_Bp_C_GetLocalizeStringWithNum_Params
{
};

// Function Global_Bp.Global_Bp_C.SaveMallShow10Animation
struct UGlobal_Bp_C_SaveMallShow10Animation_Params
{
};

// Function Global_Bp.Global_Bp_C.GetMallShow10Animation
struct UGlobal_Bp_C_GetMallShow10Animation_Params
{
};

// Function Global_Bp.Global_Bp_C.GetRankTexture
struct UGlobal_Bp_C_GetRankTexture_Params
{
	int                                                rankIntegral;                                             // (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData)
	class UTexture2D*                                  Output;                                                   // (Parm, OutParm, ZeroConstructor, IsPlainOldData)
};

// Function Global_Bp.Global_Bp_C.SwitchLobbyMeshBg
struct UGlobal_Bp_C_SwitchLobbyMeshBg_Params
{
};

// Function Global_Bp.Global_Bp_C.GetFrameTexture
struct UGlobal_Bp_C_GetFrameTexture_Params
{
	int                                                frameLevel;                                               // (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData)
	class UTexture2D*                                  Output;                                                   // (Parm, OutParm, ZeroConstructor, IsPlainOldData)
};

// Function Global_Bp.Global_Bp_C.ShowHelpshiftConversion
struct UGlobal_Bp_C_ShowHelpshiftConversion_Params
{
};

// Function Global_Bp.Global_Bp_C.EnterCreateRoleDelay
struct UGlobal_Bp_C_EnterCreateRoleDelay_Params
{
};

// Function Global_Bp.Global_Bp_C.EnterCreateRole
struct UGlobal_Bp_C_EnterCreateRole_Params
{
};

// Function Global_Bp.Global_Bp_C.EnterFightStopMusic
struct UGlobal_Bp_C_EnterFightStopMusic_Params
{
};

// Function Global_Bp.Global_Bp_C.OpenPGUrl
struct UGlobal_Bp_C_OpenPGUrl_Params
{
};

// Function Global_Bp.Global_Bp_C.EventAndroidQuitGame
struct UGlobal_Bp_C_EventAndroidQuitGame_Params
{
};

// Function Global_Bp.Global_Bp_C.QuitGame
struct UGlobal_Bp_C_QuitGame_Params
{
};

// Function Global_Bp.Global_Bp_C.EnterLobby
struct UGlobal_Bp_C_EnterLobby_Params
{
};

// Function Global_Bp.Global_Bp_C.EnterLogin
struct UGlobal_Bp_C_EnterLogin_Params
{
};

// Function Global_Bp.Global_Bp_C.SwitchLobbySkin
struct UGlobal_Bp_C_SwitchLobbySkin_Params
{
};

// Function Global_Bp.Global_Bp_C.Construct
struct UGlobal_Bp_C_Construct_Params
{
};

// Function Global_Bp.Global_Bp_C.ExecuteUbergraph_Global_Bp
struct UGlobal_Bp_C_ExecuteUbergraph_Global_Bp_Params
{
	int                                                EntryPoint;                                               // (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData)
};

}

