#pragma once

// PlayerUnknown's Battlegrounds (0.27.0) SDK Generated By @IDRAGONCHEATS
#include "../SDK.hpp"

namespace SDK
{
//---------------------------------------------------------------------------
//Parameters
//---------------------------------------------------------------------------

// Function Login_Loading_UIBP.Login_Loading_UIBP_C.UIHide
struct ULogin_Loading_UIBP_C_UIHide_Params
{
};

// Function Login_Loading_UIBP.Login_Loading_UIBP_C.RefreshLoading
struct ULogin_Loading_UIBP_C_RefreshLoading_Params
{
};

// Function Login_Loading_UIBP.Login_Loading_UIBP_C.FinishLoading
struct ULogin_Loading_UIBP_C_FinishLoading_Params
{
};

// Function Login_Loading_UIBP.Login_Loading_UIBP_C.InitLoading
struct ULogin_Loading_UIBP_C_InitLoading_Params
{
};

// Function Login_Loading_UIBP.Login_Loading_UIBP_C.UIShow
struct ULogin_Loading_UIBP_C_UIShow_Params
{
};

// Function Login_Loading_UIBP.Login_Loading_UIBP_C.Tick
struct ULogin_Loading_UIBP_C_Tick_Params
{
	struct FGeometry*                                  MyGeometry;                                               // (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData)
	float*                                             InDeltaTime;                                              // (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData)
};

// Function Login_Loading_UIBP.Login_Loading_UIBP_C.DelayShowLoading
struct ULogin_Loading_UIBP_C_DelayShowLoading_Params
{
};

// Function Login_Loading_UIBP.Login_Loading_UIBP_C.Construct
struct ULogin_Loading_UIBP_C_Construct_Params
{
};

// Function Login_Loading_UIBP.Login_Loading_UIBP_C.ExecuteUbergraph_Login_Loading_UIBP
struct ULogin_Loading_UIBP_C_ExecuteUbergraph_Login_Loading_UIBP_Params
{
	int                                                EntryPoint;                                               // (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData)
};

}

