#pragma once

// PlayerUnknown's Battlegrounds (0.27.0) SDK Generated By @IDRAGONCHEATS
namespace SDK
{
//---------------------------------------------------------------------------
//Script Structs
//---------------------------------------------------------------------------

// UserDefinedStruct BP_STRUCT_BattleResultData.BP_STRUCT_BattleResultData
// 0x0214
struct FBP_STRUCT_BattleResultData
{
	struct FString                                     Reason_0_090FA58547C1A0B16D89ED93556131B8;                // 0x0000(0x000C) (Edit, BlueprintVisible, ZeroConstructor)
	int                                                RemainingPlayerCount_1_B6DCB4414166FCD5925CDDB9D1FE4005;  // 0x000C(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	int                                                TotalPlayerCount_2_3C547194403DC35E7A7441A850D9052A;      // 0x0010(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	TArray<struct FBP_STRUCT_MemBTResultData>          BP_ARRAY_TeammateList_4_D1D37C9F463CFE5D12DB56A25C3FC3F5; // 0x0014(0x000C) (Edit, BlueprintVisible, ZeroConstructor)
	bool                                               IsSolo_5_7761A17048044B6BA00837870DEE79A6;                // 0x0020(0x0001) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	unsigned char                                      UnknownData00[0x3];                                       // 0x0021(0x0003) MISSED OFFSET
	int                                                RemainingTeamCount_6_09A91CE14B0638569CB67BA3C11DA4C1;    // 0x0024(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	int                                                TotalTeamCount_7_B45CD71043E4B40CE3733EB58A5FA2C8;        // 0x0028(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	int                                                HealTimes_8_92E7141942C26836199CD295FA664C38;             // 0x002C(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	int                                                destroyVehicleNum_10_39F2606240FAD9BB96112FB36D7F3476;    // 0x0030(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	int                                                ShootWeaponShotNum_15_00FDC55D46412A4EF2D46788057C4B8E;   // 0x0034(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	int                                                ShootWeaponShotAndHitPlayerNum_16_2F13756C4750D3F3F05932BC37A64410;// 0x0038(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	int                                                add_exp_18_33F80B2F441B32D5C0B97FA429A2643D;              // 0x003C(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	int                                                add_gold_19_88091C09400E4592461BFA9B7875B20F;             // 0x0040(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	int                                                battle_id_20_991B81644AB2AFE897194A8812ED48F2;            // 0x0044(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	int                                                max_game_num_21_89652E3B4A981D752CEE0DB8B057F65E;         // 0x0048(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	struct FBP_STRUCT_BTRating                         BP_STRUCT_BTRating_23_9103901146E6516BDB1721AD842CA08D;   // 0x004C(0x0020) (Edit, BlueprintVisible)
	int                                                person_rank_24_4BE9AF544E5666C0D1276F9D4B7381A1;          // 0x006C(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	int                                                team_rank_25_19B113CD47B5E1F5B1D2C4AE0CACF918;            // 0x0070(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	bool                                               is_last_survive_27_D64038A548BAF4E29E66ECB94800871A;      // 0x0074(0x0001) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	bool                                               is_team_result_28_77AFCE32426209D6DA3EDDB119CBB9C9;       // 0x0075(0x0001) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	unsigned char                                      UnknownData01[0x2];                                       // 0x0076(0x0002) MISSED OFFSET
	int                                                HeadShotRatio_29_CF108FB640585FC2F35E53BA84BB23EB;        // 0x0078(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	bool                                               is_version_match_30_8C55192942DA2E7A91B2189BE6B447B1;     // 0x007C(0x0001) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	unsigned char                                      UnknownData02[0x3];                                       // 0x007D(0x0003) MISSED OFFSET
	struct FString                                     final_level_41_373D4259445F1E41E1D787A83FEDB9AE;          // 0x0080(0x000C) (Edit, BlueprintVisible, ZeroConstructor)
	struct FBP_STRUCT_RADAR                            BP_STRUCT_RADAR_32_9B0B06274CA0904C8C6ACF9C0B2A1118;      // 0x008C(0x00A0) (Edit, BlueprintVisible)
	struct FBP_STRUCT_EXP_DETAIL                       BP_STRUCT_EXP_DETAIL_33_FF719D304AB7D06CBE973FA998C24768; // 0x012C(0x003C) (Edit, BlueprintVisible)
	struct FBP_STRUCT_GOLD_DETAIL                      BP_STRUCT_GOLD_DETAIL_34_7B6FA53C4264732A91CF779C7ADDF600;// 0x0168(0x0034) (Edit, BlueprintVisible)
	int                                                battle_owner_35_9B67D91445929AEB73E7AF886DA9A77B;         // 0x019C(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	int                                                famous_id_36_916DFF8C4F04711F0E5F80B5883BA08C;            // 0x01A0(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	int                                                get_gold_today_37_B74B5698443090483A1E9BB30255B216;       // 0x01A4(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	int                                                battle_type_38_4A56D05E4711978AE31924A97AC6D490;          // 0x01A8(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	bool                                               isobserver_39_8CE87EF145765FFC2EA57DA09566A2E7;           // 0x01AC(0x0001) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	unsigned char                                      UnknownData03[0x3];                                       // 0x01AD(0x0003) MISSED OFFSET
	int                                                sub_mode_40_30956600233A9EF42F9B8F200891AD95;             // 0x01B0(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	bool                                               segment_protect_42_6E49E7400FC56D9F1D16E4BD04F47144;      // 0x01B4(0x0001) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	bool                                               is_anchor_ob_45_6CC7AC00023421902654B4FD038AE7B2;         // 0x01B5(0x0001) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	unsigned char                                      UnknownData04[0x2];                                       // 0x01B6(0x0002) MISSED OFFSET
	int                                                char_add_exp_46_13658700555ABB3A41B40CFB0EA52F00;         // 0x01B8(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	int                                                add_carteam_coin_47_66672DC067EDE5916779219B0824F63E;     // 0x01BC(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	int                                                tournament_id_48_4B10B0C07C4C3DE11C73F85007F68AF4;        // 0x01C0(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	int                                                kill_score_49_05A57C407803CCDD335A5E4D05C32B65;           // 0x01C4(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	int                                                delay_time_50_43F119C04A44DD7B2A503CDA0D5F97E5;           // 0x01C8(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	bool                                               is_activity_protect_51_7C5954805947912248F676C00EAC34D4;  // 0x01CC(0x0001) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	unsigned char                                      UnknownData05[0x3];                                       // 0x01CD(0x0003) MISSED OFFSET
	int                                                league_seq_52_615119404ED12BA906CAD6940B11D141;           // 0x01D0(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	int                                                add_vaccinum_53_44984A004464421E5E26A6160E7096DD;         // 0x01D4(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	int                                                char_id_54_3F2565001A597A5272177D4C00D73F64;              // 0x01D8(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	struct FBP_STRUCT_CHAR_EXP_DETAIL                  BP_STRUCT_CHAR_EXP_DETAIL_55_1986DEC00524E28F09B977DB021ACCBC;// 0x01DC(0x0010) (Edit, BlueprintVisible)
	int                                                rank_score_56_06309C4019D1832B1E8D666606C19345;           // 0x01EC(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	struct FBP_STRUCT_BTRatingProtect                  BP_STRUCT_BTRatingProtect_58_055BB6C046BF660537A5C09A090F8B34;// 0x01F0(0x0010) (Edit, BlueprintVisible)
	bool                                               is_pug_result_59_1D6E93C039B5DFB5118C210C0F458B44;        // 0x0200(0x0001) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	unsigned char                                      UnknownData06[0x3];                                       // 0x0201(0x0003) MISSED OFFSET
	struct FBP_STRUCT_SegmentProtect                   BP_STRUCT_SegmentProtect_60_32B1CCC01422B36F312342B0004A3794;// 0x0204(0x0010) (Edit, BlueprintVisible)
};

}

