// PlayerUnknown's Battlegrounds (0.27.0) SDK Generated By @IDRAGONCHEATS
#include "../SDK.hpp"

namespace SDK
{
//---------------------------------------------------------------------------
//Functions
//---------------------------------------------------------------------------

// Function bp_lobby_friend.bp_lobby_friend_C.EventOpenFriendRuleDescriptionPanel_NoFetch
// (BlueprintCallable, BlueprintEvent)

void Abp_lobby_friend_C::EventOpenFriendRuleDescriptionPanel_NoFetch()
{
	static UFunction *pFunc = 0;
	if (!pFunc)
		pFunc = UObject::FindObject<UFunction>("Function bp_lobby_friend.bp_lobby_friend_C.EventOpenFriendRuleDescriptionPanel_NoFetch");

	Abp_lobby_friend_C_EventOpenFriendRuleDescriptionPanel_NoFetch_Params params;

	auto flags = pFunc->FunctionFlags;

	UObject *currentObj = (UObject *) this;
	currentObj->ProcessEvent(pFunc, &params);

	pFunc->FunctionFlags = flags;
}

// Function bp_lobby_friend.bp_lobby_friend_C.EventOpenFriendRuleDescriptionPanel
// (BlueprintCallable, BlueprintEvent)

void Abp_lobby_friend_C::EventOpenFriendRuleDescriptionPanel()
{
	static UFunction *pFunc = 0;
	if (!pFunc)
		pFunc = UObject::FindObject<UFunction>("Function bp_lobby_friend.bp_lobby_friend_C.EventOpenFriendRuleDescriptionPanel");

	Abp_lobby_friend_C_EventOpenFriendRuleDescriptionPanel_Params params;

	auto flags = pFunc->FunctionFlags;

	UObject *currentObj = (UObject *) this;
	currentObj->ProcessEvent(pFunc, &params);

	pFunc->FunctionFlags = flags;
}

// Function bp_lobby_friend.bp_lobby_friend_C.EventNearByCloseLocation_NoFetch
// (BlueprintCallable, BlueprintEvent)

void Abp_lobby_friend_C::EventNearByCloseLocation_NoFetch()
{
	static UFunction *pFunc = 0;
	if (!pFunc)
		pFunc = UObject::FindObject<UFunction>("Function bp_lobby_friend.bp_lobby_friend_C.EventNearByCloseLocation_NoFetch");

	Abp_lobby_friend_C_EventNearByCloseLocation_NoFetch_Params params;

	auto flags = pFunc->FunctionFlags;

	UObject *currentObj = (UObject *) this;
	currentObj->ProcessEvent(pFunc, &params);

	pFunc->FunctionFlags = flags;
}

// Function bp_lobby_friend.bp_lobby_friend_C.EventNearByCloseLocation
// (BlueprintCallable, BlueprintEvent)

void Abp_lobby_friend_C::EventNearByCloseLocation()
{
	static UFunction *pFunc = 0;
	if (!pFunc)
		pFunc = UObject::FindObject<UFunction>("Function bp_lobby_friend.bp_lobby_friend_C.EventNearByCloseLocation");

	Abp_lobby_friend_C_EventNearByCloseLocation_Params params;

	auto flags = pFunc->FunctionFlags;

	UObject *currentObj = (UObject *) this;
	currentObj->ProcessEvent(pFunc, &params);

	pFunc->FunctionFlags = flags;
}

// Function bp_lobby_friend.bp_lobby_friend_C.EventGetRecentTeammateList_NoFetch
// (BlueprintCallable, BlueprintEvent)

void Abp_lobby_friend_C::EventGetRecentTeammateList_NoFetch()
{
	static UFunction *pFunc = 0;
	if (!pFunc)
		pFunc = UObject::FindObject<UFunction>("Function bp_lobby_friend.bp_lobby_friend_C.EventGetRecentTeammateList_NoFetch");

	Abp_lobby_friend_C_EventGetRecentTeammateList_NoFetch_Params params;

	auto flags = pFunc->FunctionFlags;

	UObject *currentObj = (UObject *) this;
	currentObj->ProcessEvent(pFunc, &params);

	pFunc->FunctionFlags = flags;
}

// Function bp_lobby_friend.bp_lobby_friend_C.EventGetRecentTeammateList
// (BlueprintCallable, BlueprintEvent)

void Abp_lobby_friend_C::EventGetRecentTeammateList()
{
	static UFunction *pFunc = 0;
	if (!pFunc)
		pFunc = UObject::FindObject<UFunction>("Function bp_lobby_friend.bp_lobby_friend_C.EventGetRecentTeammateList");

	Abp_lobby_friend_C_EventGetRecentTeammateList_Params params;

	auto flags = pFunc->FunctionFlags;

	UObject *currentObj = (UObject *) this;
	currentObj->ProcessEvent(pFunc, &params);

	pFunc->FunctionFlags = flags;
}

// Function bp_lobby_friend.bp_lobby_friend_C.EventLobbyFriendLabelSearchReq_NoFetch
// (BlueprintCallable, BlueprintEvent)

void Abp_lobby_friend_C::EventLobbyFriendLabelSearchReq_NoFetch()
{
	static UFunction *pFunc = 0;
	if (!pFunc)
		pFunc = UObject::FindObject<UFunction>("Function bp_lobby_friend.bp_lobby_friend_C.EventLobbyFriendLabelSearchReq_NoFetch");

	Abp_lobby_friend_C_EventLobbyFriendLabelSearchReq_NoFetch_Params params;

	auto flags = pFunc->FunctionFlags;

	UObject *currentObj = (UObject *) this;
	currentObj->ProcessEvent(pFunc, &params);

	pFunc->FunctionFlags = flags;
}

// Function bp_lobby_friend.bp_lobby_friend_C.EventLobbyFriendLabelSearchReq
// (BlueprintCallable, BlueprintEvent)

void Abp_lobby_friend_C::EventLobbyFriendLabelSearchReq()
{
	static UFunction *pFunc = 0;
	if (!pFunc)
		pFunc = UObject::FindObject<UFunction>("Function bp_lobby_friend.bp_lobby_friend_C.EventLobbyFriendLabelSearchReq");

	Abp_lobby_friend_C_EventLobbyFriendLabelSearchReq_Params params;

	auto flags = pFunc->FunctionFlags;

	UObject *currentObj = (UObject *) this;
	currentObj->ProcessEvent(pFunc, &params);

	pFunc->FunctionFlags = flags;
}

// Function bp_lobby_friend.bp_lobby_friend_C.EventEnterBatchDeleteInnerFriend_NoFetch
// (BlueprintCallable, BlueprintEvent)

void Abp_lobby_friend_C::EventEnterBatchDeleteInnerFriend_NoFetch()
{
	static UFunction *pFunc = 0;
	if (!pFunc)
		pFunc = UObject::FindObject<UFunction>("Function bp_lobby_friend.bp_lobby_friend_C.EventEnterBatchDeleteInnerFriend_NoFetch");

	Abp_lobby_friend_C_EventEnterBatchDeleteInnerFriend_NoFetch_Params params;

	auto flags = pFunc->FunctionFlags;

	UObject *currentObj = (UObject *) this;
	currentObj->ProcessEvent(pFunc, &params);

	pFunc->FunctionFlags = flags;
}

// Function bp_lobby_friend.bp_lobby_friend_C.EventEnterBatchDeleteInnerFriend
// (BlueprintCallable, BlueprintEvent)

void Abp_lobby_friend_C::EventEnterBatchDeleteInnerFriend()
{
	static UFunction *pFunc = 0;
	if (!pFunc)
		pFunc = UObject::FindObject<UFunction>("Function bp_lobby_friend.bp_lobby_friend_C.EventEnterBatchDeleteInnerFriend");

	Abp_lobby_friend_C_EventEnterBatchDeleteInnerFriend_Params params;

	auto flags = pFunc->FunctionFlags;

	UObject *currentObj = (UObject *) this;
	currentObj->ProcessEvent(pFunc, &params);

	pFunc->FunctionFlags = flags;
}

// Function bp_lobby_friend.bp_lobby_friend_C.EventLobbyFriendScrollSearchList_NoFetch
// (BlueprintCallable, BlueprintEvent)

void Abp_lobby_friend_C::EventLobbyFriendScrollSearchList_NoFetch()
{
	static UFunction *pFunc = 0;
	if (!pFunc)
		pFunc = UObject::FindObject<UFunction>("Function bp_lobby_friend.bp_lobby_friend_C.EventLobbyFriendScrollSearchList_NoFetch");

	Abp_lobby_friend_C_EventLobbyFriendScrollSearchList_NoFetch_Params params;

	auto flags = pFunc->FunctionFlags;

	UObject *currentObj = (UObject *) this;
	currentObj->ProcessEvent(pFunc, &params);

	pFunc->FunctionFlags = flags;
}

// Function bp_lobby_friend.bp_lobby_friend_C.EventLobbyFriendScrollSearchList
// (BlueprintCallable, BlueprintEvent)

void Abp_lobby_friend_C::EventLobbyFriendScrollSearchList()
{
	static UFunction *pFunc = 0;
	if (!pFunc)
		pFunc = UObject::FindObject<UFunction>("Function bp_lobby_friend.bp_lobby_friend_C.EventLobbyFriendScrollSearchList");

	Abp_lobby_friend_C_EventLobbyFriendScrollSearchList_Params params;

	auto flags = pFunc->FunctionFlags;

	UObject *currentObj = (UObject *) this;
	currentObj->ProcessEvent(pFunc, &params);

	pFunc->FunctionFlags = flags;
}

// Function bp_lobby_friend.bp_lobby_friend_C.EventHideLobbyFriendUI_NoFetch
// (BlueprintCallable, BlueprintEvent)

void Abp_lobby_friend_C::EventHideLobbyFriendUI_NoFetch()
{
	static UFunction *pFunc = 0;
	if (!pFunc)
		pFunc = UObject::FindObject<UFunction>("Function bp_lobby_friend.bp_lobby_friend_C.EventHideLobbyFriendUI_NoFetch");

	Abp_lobby_friend_C_EventHideLobbyFriendUI_NoFetch_Params params;

	auto flags = pFunc->FunctionFlags;

	UObject *currentObj = (UObject *) this;
	currentObj->ProcessEvent(pFunc, &params);

	pFunc->FunctionFlags = flags;
}

// Function bp_lobby_friend.bp_lobby_friend_C.EventHideLobbyFriendUI
// (BlueprintCallable, BlueprintEvent)

void Abp_lobby_friend_C::EventHideLobbyFriendUI()
{
	static UFunction *pFunc = 0;
	if (!pFunc)
		pFunc = UObject::FindObject<UFunction>("Function bp_lobby_friend.bp_lobby_friend_C.EventHideLobbyFriendUI");

	Abp_lobby_friend_C_EventHideLobbyFriendUI_Params params;

	auto flags = pFunc->FunctionFlags;

	UObject *currentObj = (UObject *) this;
	currentObj->ProcessEvent(pFunc, &params);

	pFunc->FunctionFlags = flags;
}

// Function bp_lobby_friend.bp_lobby_friend_C.EventLobbyFriendDeleteBlackReq_NoFetch
// (BlueprintCallable, BlueprintEvent)

void Abp_lobby_friend_C::EventLobbyFriendDeleteBlackReq_NoFetch()
{
	static UFunction *pFunc = 0;
	if (!pFunc)
		pFunc = UObject::FindObject<UFunction>("Function bp_lobby_friend.bp_lobby_friend_C.EventLobbyFriendDeleteBlackReq_NoFetch");

	Abp_lobby_friend_C_EventLobbyFriendDeleteBlackReq_NoFetch_Params params;

	auto flags = pFunc->FunctionFlags;

	UObject *currentObj = (UObject *) this;
	currentObj->ProcessEvent(pFunc, &params);

	pFunc->FunctionFlags = flags;
}

// Function bp_lobby_friend.bp_lobby_friend_C.EventLobbyFriendDeleteBlackReq
// (BlueprintCallable, BlueprintEvent)

void Abp_lobby_friend_C::EventLobbyFriendDeleteBlackReq()
{
	static UFunction *pFunc = 0;
	if (!pFunc)
		pFunc = UObject::FindObject<UFunction>("Function bp_lobby_friend.bp_lobby_friend_C.EventLobbyFriendDeleteBlackReq");

	Abp_lobby_friend_C_EventLobbyFriendDeleteBlackReq_Params params;

	auto flags = pFunc->FunctionFlags;

	UObject *currentObj = (UObject *) this;
	currentObj->ProcessEvent(pFunc, &params);

	pFunc->FunctionFlags = flags;
}

// Function bp_lobby_friend.bp_lobby_friend_C.EventFetchInfo_NoFetch
// (BlueprintCallable, BlueprintEvent)

void Abp_lobby_friend_C::EventFetchInfo_NoFetch()
{
	static UFunction *pFunc = 0;
	if (!pFunc)
		pFunc = UObject::FindObject<UFunction>("Function bp_lobby_friend.bp_lobby_friend_C.EventFetchInfo_NoFetch");

	Abp_lobby_friend_C_EventFetchInfo_NoFetch_Params params;

	auto flags = pFunc->FunctionFlags;

	UObject *currentObj = (UObject *) this;
	currentObj->ProcessEvent(pFunc, &params);

	pFunc->FunctionFlags = flags;
}

// Function bp_lobby_friend.bp_lobby_friend_C.EventFetchInfo
// (BlueprintCallable, BlueprintEvent)

void Abp_lobby_friend_C::EventFetchInfo()
{
	static UFunction *pFunc = 0;
	if (!pFunc)
		pFunc = UObject::FindObject<UFunction>("Function bp_lobby_friend.bp_lobby_friend_C.EventFetchInfo");

	Abp_lobby_friend_C_EventFetchInfo_Params params;

	auto flags = pFunc->FunctionFlags;

	UObject *currentObj = (UObject *) this;
	currentObj->ProcessEvent(pFunc, &params);

	pFunc->FunctionFlags = flags;
}

// Function bp_lobby_friend.bp_lobby_friend_C.EventLobbyFriendAddFriendReqList_NoFetch
// (BlueprintCallable, BlueprintEvent)

void Abp_lobby_friend_C::EventLobbyFriendAddFriendReqList_NoFetch()
{
	static UFunction *pFunc = 0;
	if (!pFunc)
		pFunc = UObject::FindObject<UFunction>("Function bp_lobby_friend.bp_lobby_friend_C.EventLobbyFriendAddFriendReqList_NoFetch");

	Abp_lobby_friend_C_EventLobbyFriendAddFriendReqList_NoFetch_Params params;

	auto flags = pFunc->FunctionFlags;

	UObject *currentObj = (UObject *) this;
	currentObj->ProcessEvent(pFunc, &params);

	pFunc->FunctionFlags = flags;
}

// Function bp_lobby_friend.bp_lobby_friend_C.EventLobbyFriendAddFriendReqList
// (BlueprintCallable, BlueprintEvent)

void Abp_lobby_friend_C::EventLobbyFriendAddFriendReqList()
{
	static UFunction *pFunc = 0;
	if (!pFunc)
		pFunc = UObject::FindObject<UFunction>("Function bp_lobby_friend.bp_lobby_friend_C.EventLobbyFriendAddFriendReqList");

	Abp_lobby_friend_C_EventLobbyFriendAddFriendReqList_Params params;

	auto flags = pFunc->FunctionFlags;

	UObject *currentObj = (UObject *) this;
	currentObj->ProcessEvent(pFunc, &params);

	pFunc->FunctionFlags = flags;
}

// Function bp_lobby_friend.bp_lobby_friend_C.EventShowSendAddFriendRequestTips_NoFetch
// (BlueprintCallable, BlueprintEvent)

void Abp_lobby_friend_C::EventShowSendAddFriendRequestTips_NoFetch()
{
	static UFunction *pFunc = 0;
	if (!pFunc)
		pFunc = UObject::FindObject<UFunction>("Function bp_lobby_friend.bp_lobby_friend_C.EventShowSendAddFriendRequestTips_NoFetch");

	Abp_lobby_friend_C_EventShowSendAddFriendRequestTips_NoFetch_Params params;

	auto flags = pFunc->FunctionFlags;

	UObject *currentObj = (UObject *) this;
	currentObj->ProcessEvent(pFunc, &params);

	pFunc->FunctionFlags = flags;
}

// Function bp_lobby_friend.bp_lobby_friend_C.EventShowSendAddFriendRequestTips
// (BlueprintCallable, BlueprintEvent)

void Abp_lobby_friend_C::EventShowSendAddFriendRequestTips()
{
	static UFunction *pFunc = 0;
	if (!pFunc)
		pFunc = UObject::FindObject<UFunction>("Function bp_lobby_friend.bp_lobby_friend_C.EventShowSendAddFriendRequestTips");

	Abp_lobby_friend_C_EventShowSendAddFriendRequestTips_Params params;

	auto flags = pFunc->FunctionFlags;

	UObject *currentObj = (UObject *) this;
	currentObj->ProcessEvent(pFunc, &params);

	pFunc->FunctionFlags = flags;
}

// Function bp_lobby_friend.bp_lobby_friend_C.EventLeaveBatchDeleteInnerFriend_NoFetch
// (BlueprintCallable, BlueprintEvent)

void Abp_lobby_friend_C::EventLeaveBatchDeleteInnerFriend_NoFetch()
{
	static UFunction *pFunc = 0;
	if (!pFunc)
		pFunc = UObject::FindObject<UFunction>("Function bp_lobby_friend.bp_lobby_friend_C.EventLeaveBatchDeleteInnerFriend_NoFetch");

	Abp_lobby_friend_C_EventLeaveBatchDeleteInnerFriend_NoFetch_Params params;

	auto flags = pFunc->FunctionFlags;

	UObject *currentObj = (UObject *) this;
	currentObj->ProcessEvent(pFunc, &params);

	pFunc->FunctionFlags = flags;
}

// Function bp_lobby_friend.bp_lobby_friend_C.EventLeaveBatchDeleteInnerFriend
// (BlueprintCallable, BlueprintEvent)

void Abp_lobby_friend_C::EventLeaveBatchDeleteInnerFriend()
{
	static UFunction *pFunc = 0;
	if (!pFunc)
		pFunc = UObject::FindObject<UFunction>("Function bp_lobby_friend.bp_lobby_friend_C.EventLeaveBatchDeleteInnerFriend");

	Abp_lobby_friend_C_EventLeaveBatchDeleteInnerFriend_Params params;

	auto flags = pFunc->FunctionFlags;

	UObject *currentObj = (UObject *) this;
	currentObj->ProcessEvent(pFunc, &params);

	pFunc->FunctionFlags = flags;
}

// Function bp_lobby_friend.bp_lobby_friend_C.EventFriendOnTapChange_NoFetch
// (BlueprintCallable, BlueprintEvent)

void Abp_lobby_friend_C::EventFriendOnTapChange_NoFetch()
{
	static UFunction *pFunc = 0;
	if (!pFunc)
		pFunc = UObject::FindObject<UFunction>("Function bp_lobby_friend.bp_lobby_friend_C.EventFriendOnTapChange_NoFetch");

	Abp_lobby_friend_C_EventFriendOnTapChange_NoFetch_Params params;

	auto flags = pFunc->FunctionFlags;

	UObject *currentObj = (UObject *) this;
	currentObj->ProcessEvent(pFunc, &params);

	pFunc->FunctionFlags = flags;
}

// Function bp_lobby_friend.bp_lobby_friend_C.EventFriendOnTapChange
// (BlueprintCallable, BlueprintEvent)

void Abp_lobby_friend_C::EventFriendOnTapChange()
{
	static UFunction *pFunc = 0;
	if (!pFunc)
		pFunc = UObject::FindObject<UFunction>("Function bp_lobby_friend.bp_lobby_friend_C.EventFriendOnTapChange");

	Abp_lobby_friend_C_EventFriendOnTapChange_Params params;

	auto flags = pFunc->FunctionFlags;

	UObject *currentObj = (UObject *) this;
	currentObj->ProcessEvent(pFunc, &params);

	pFunc->FunctionFlags = flags;
}

// Function bp_lobby_friend.bp_lobby_friend_C.EventSelectBatchDeleteInnerFriend_NoFetch
// (BlueprintCallable, BlueprintEvent)

void Abp_lobby_friend_C::EventSelectBatchDeleteInnerFriend_NoFetch()
{
	static UFunction *pFunc = 0;
	if (!pFunc)
		pFunc = UObject::FindObject<UFunction>("Function bp_lobby_friend.bp_lobby_friend_C.EventSelectBatchDeleteInnerFriend_NoFetch");

	Abp_lobby_friend_C_EventSelectBatchDeleteInnerFriend_NoFetch_Params params;

	auto flags = pFunc->FunctionFlags;

	UObject *currentObj = (UObject *) this;
	currentObj->ProcessEvent(pFunc, &params);

	pFunc->FunctionFlags = flags;
}

// Function bp_lobby_friend.bp_lobby_friend_C.EventSelectBatchDeleteInnerFriend
// (BlueprintCallable, BlueprintEvent)

void Abp_lobby_friend_C::EventSelectBatchDeleteInnerFriend()
{
	static UFunction *pFunc = 0;
	if (!pFunc)
		pFunc = UObject::FindObject<UFunction>("Function bp_lobby_friend.bp_lobby_friend_C.EventSelectBatchDeleteInnerFriend");

	Abp_lobby_friend_C_EventSelectBatchDeleteInnerFriend_Params params;

	auto flags = pFunc->FunctionFlags;

	UObject *currentObj = (UObject *) this;
	currentObj->ProcessEvent(pFunc, &params);

	pFunc->FunctionFlags = flags;
}

// Function bp_lobby_friend.bp_lobby_friend_C.EventUnselectBatchDeleteInnerFriend_NoFetch
// (BlueprintCallable, BlueprintEvent)

void Abp_lobby_friend_C::EventUnselectBatchDeleteInnerFriend_NoFetch()
{
	static UFunction *pFunc = 0;
	if (!pFunc)
		pFunc = UObject::FindObject<UFunction>("Function bp_lobby_friend.bp_lobby_friend_C.EventUnselectBatchDeleteInnerFriend_NoFetch");

	Abp_lobby_friend_C_EventUnselectBatchDeleteInnerFriend_NoFetch_Params params;

	auto flags = pFunc->FunctionFlags;

	UObject *currentObj = (UObject *) this;
	currentObj->ProcessEvent(pFunc, &params);

	pFunc->FunctionFlags = flags;
}

// Function bp_lobby_friend.bp_lobby_friend_C.EventUnselectBatchDeleteInnerFriend
// (BlueprintCallable, BlueprintEvent)

void Abp_lobby_friend_C::EventUnselectBatchDeleteInnerFriend()
{
	static UFunction *pFunc = 0;
	if (!pFunc)
		pFunc = UObject::FindObject<UFunction>("Function bp_lobby_friend.bp_lobby_friend_C.EventUnselectBatchDeleteInnerFriend");

	Abp_lobby_friend_C_EventUnselectBatchDeleteInnerFriend_Params params;

	auto flags = pFunc->FunctionFlags;

	UObject *currentObj = (UObject *) this;
	currentObj->ProcessEvent(pFunc, &params);

	pFunc->FunctionFlags = flags;
}

// Function bp_lobby_friend.bp_lobby_friend_C.EventConfirmBatchDeleteInnerFriend_NoFetch
// (BlueprintCallable, BlueprintEvent)

void Abp_lobby_friend_C::EventConfirmBatchDeleteInnerFriend_NoFetch()
{
	static UFunction *pFunc = 0;
	if (!pFunc)
		pFunc = UObject::FindObject<UFunction>("Function bp_lobby_friend.bp_lobby_friend_C.EventConfirmBatchDeleteInnerFriend_NoFetch");

	Abp_lobby_friend_C_EventConfirmBatchDeleteInnerFriend_NoFetch_Params params;

	auto flags = pFunc->FunctionFlags;

	UObject *currentObj = (UObject *) this;
	currentObj->ProcessEvent(pFunc, &params);

	pFunc->FunctionFlags = flags;
}

// Function bp_lobby_friend.bp_lobby_friend_C.EventConfirmBatchDeleteInnerFriend
// (BlueprintCallable, BlueprintEvent)

void Abp_lobby_friend_C::EventConfirmBatchDeleteInnerFriend()
{
	static UFunction *pFunc = 0;
	if (!pFunc)
		pFunc = UObject::FindObject<UFunction>("Function bp_lobby_friend.bp_lobby_friend_C.EventConfirmBatchDeleteInnerFriend");

	Abp_lobby_friend_C_EventConfirmBatchDeleteInnerFriend_Params params;

	auto flags = pFunc->FunctionFlags;

	UObject *currentObj = (UObject *) this;
	currentObj->ProcessEvent(pFunc, &params);

	pFunc->FunctionFlags = flags;
}

// Function bp_lobby_friend.bp_lobby_friend_C.EventLobbyFriendFetchFriendList_NoFetch
// (BlueprintCallable, BlueprintEvent)

void Abp_lobby_friend_C::EventLobbyFriendFetchFriendList_NoFetch()
{
	static UFunction *pFunc = 0;
	if (!pFunc)
		pFunc = UObject::FindObject<UFunction>("Function bp_lobby_friend.bp_lobby_friend_C.EventLobbyFriendFetchFriendList_NoFetch");

	Abp_lobby_friend_C_EventLobbyFriendFetchFriendList_NoFetch_Params params;

	auto flags = pFunc->FunctionFlags;

	UObject *currentObj = (UObject *) this;
	currentObj->ProcessEvent(pFunc, &params);

	pFunc->FunctionFlags = flags;
}

// Function bp_lobby_friend.bp_lobby_friend_C.EventLobbyFriendFetchFriendList
// (BlueprintCallable, BlueprintEvent)

void Abp_lobby_friend_C::EventLobbyFriendFetchFriendList()
{
	static UFunction *pFunc = 0;
	if (!pFunc)
		pFunc = UObject::FindObject<UFunction>("Function bp_lobby_friend.bp_lobby_friend_C.EventLobbyFriendFetchFriendList");

	Abp_lobby_friend_C_EventLobbyFriendFetchFriendList_Params params;

	auto flags = pFunc->FunctionFlags;

	UObject *currentObj = (UObject *) this;
	currentObj->ProcessEvent(pFunc, &params);

	pFunc->FunctionFlags = flags;
}

// Function bp_lobby_friend.bp_lobby_friend_C.EventLobbyFriendBlackListScroll_NoFetch
// (BlueprintCallable, BlueprintEvent)

void Abp_lobby_friend_C::EventLobbyFriendBlackListScroll_NoFetch()
{
	static UFunction *pFunc = 0;
	if (!pFunc)
		pFunc = UObject::FindObject<UFunction>("Function bp_lobby_friend.bp_lobby_friend_C.EventLobbyFriendBlackListScroll_NoFetch");

	Abp_lobby_friend_C_EventLobbyFriendBlackListScroll_NoFetch_Params params;

	auto flags = pFunc->FunctionFlags;

	UObject *currentObj = (UObject *) this;
	currentObj->ProcessEvent(pFunc, &params);

	pFunc->FunctionFlags = flags;
}

// Function bp_lobby_friend.bp_lobby_friend_C.EventLobbyFriendBlackListScroll
// (BlueprintCallable, BlueprintEvent)

void Abp_lobby_friend_C::EventLobbyFriendBlackListScroll()
{
	static UFunction *pFunc = 0;
	if (!pFunc)
		pFunc = UObject::FindObject<UFunction>("Function bp_lobby_friend.bp_lobby_friend_C.EventLobbyFriendBlackListScroll");

	Abp_lobby_friend_C_EventLobbyFriendBlackListScroll_Params params;

	auto flags = pFunc->FunctionFlags;

	UObject *currentObj = (UObject *) this;
	currentObj->ProcessEvent(pFunc, &params);

	pFunc->FunctionFlags = flags;
}

// Function bp_lobby_friend.bp_lobby_friend_C.EventLobbyFriendRespondApply_NoFetch
// (BlueprintCallable, BlueprintEvent)

void Abp_lobby_friend_C::EventLobbyFriendRespondApply_NoFetch()
{
	static UFunction *pFunc = 0;
	if (!pFunc)
		pFunc = UObject::FindObject<UFunction>("Function bp_lobby_friend.bp_lobby_friend_C.EventLobbyFriendRespondApply_NoFetch");

	Abp_lobby_friend_C_EventLobbyFriendRespondApply_NoFetch_Params params;

	auto flags = pFunc->FunctionFlags;

	UObject *currentObj = (UObject *) this;
	currentObj->ProcessEvent(pFunc, &params);

	pFunc->FunctionFlags = flags;
}

// Function bp_lobby_friend.bp_lobby_friend_C.EventLobbyFriendRespondApply
// (BlueprintCallable, BlueprintEvent)

void Abp_lobby_friend_C::EventLobbyFriendRespondApply()
{
	static UFunction *pFunc = 0;
	if (!pFunc)
		pFunc = UObject::FindObject<UFunction>("Function bp_lobby_friend.bp_lobby_friend_C.EventLobbyFriendRespondApply");

	Abp_lobby_friend_C_EventLobbyFriendRespondApply_Params params;

	auto flags = pFunc->FunctionFlags;

	UObject *currentObj = (UObject *) this;
	currentObj->ProcessEvent(pFunc, &params);

	pFunc->FunctionFlags = flags;
}

// Function bp_lobby_friend.bp_lobby_friend_C.EventRecentTeammateScrollApplyList_NoFetch
// (BlueprintCallable, BlueprintEvent)

void Abp_lobby_friend_C::EventRecentTeammateScrollApplyList_NoFetch()
{
	static UFunction *pFunc = 0;
	if (!pFunc)
		pFunc = UObject::FindObject<UFunction>("Function bp_lobby_friend.bp_lobby_friend_C.EventRecentTeammateScrollApplyList_NoFetch");

	Abp_lobby_friend_C_EventRecentTeammateScrollApplyList_NoFetch_Params params;

	auto flags = pFunc->FunctionFlags;

	UObject *currentObj = (UObject *) this;
	currentObj->ProcessEvent(pFunc, &params);

	pFunc->FunctionFlags = flags;
}

// Function bp_lobby_friend.bp_lobby_friend_C.EventRecentTeammateScrollApplyList
// (BlueprintCallable, BlueprintEvent)

void Abp_lobby_friend_C::EventRecentTeammateScrollApplyList()
{
	static UFunction *pFunc = 0;
	if (!pFunc)
		pFunc = UObject::FindObject<UFunction>("Function bp_lobby_friend.bp_lobby_friend_C.EventRecentTeammateScrollApplyList");

	Abp_lobby_friend_C_EventRecentTeammateScrollApplyList_Params params;

	auto flags = pFunc->FunctionFlags;

	UObject *currentObj = (UObject *) this;
	currentObj->ProcessEvent(pFunc, &params);

	pFunc->FunctionFlags = flags;
}

// Function bp_lobby_friend.bp_lobby_friend_C.EventLobbyFriendIntimacyReq_NoFetch
// (BlueprintCallable, BlueprintEvent)

void Abp_lobby_friend_C::EventLobbyFriendIntimacyReq_NoFetch()
{
	static UFunction *pFunc = 0;
	if (!pFunc)
		pFunc = UObject::FindObject<UFunction>("Function bp_lobby_friend.bp_lobby_friend_C.EventLobbyFriendIntimacyReq_NoFetch");

	Abp_lobby_friend_C_EventLobbyFriendIntimacyReq_NoFetch_Params params;

	auto flags = pFunc->FunctionFlags;

	UObject *currentObj = (UObject *) this;
	currentObj->ProcessEvent(pFunc, &params);

	pFunc->FunctionFlags = flags;
}

// Function bp_lobby_friend.bp_lobby_friend_C.EventLobbyFriendIntimacyReq
// (BlueprintCallable, BlueprintEvent)

void Abp_lobby_friend_C::EventLobbyFriendIntimacyReq()
{
	static UFunction *pFunc = 0;
	if (!pFunc)
		pFunc = UObject::FindObject<UFunction>("Function bp_lobby_friend.bp_lobby_friend_C.EventLobbyFriendIntimacyReq");

	Abp_lobby_friend_C_EventLobbyFriendIntimacyReq_Params params;

	auto flags = pFunc->FunctionFlags;

	UObject *currentObj = (UObject *) this;
	currentObj->ProcessEvent(pFunc, &params);

	pFunc->FunctionFlags = flags;
}

// Function bp_lobby_friend.bp_lobby_friend_C.EventLobbyFriendReplyRelationReq_NoFetch
// (BlueprintCallable, BlueprintEvent)

void Abp_lobby_friend_C::EventLobbyFriendReplyRelationReq_NoFetch()
{
	static UFunction *pFunc = 0;
	if (!pFunc)
		pFunc = UObject::FindObject<UFunction>("Function bp_lobby_friend.bp_lobby_friend_C.EventLobbyFriendReplyRelationReq_NoFetch");

	Abp_lobby_friend_C_EventLobbyFriendReplyRelationReq_NoFetch_Params params;

	auto flags = pFunc->FunctionFlags;

	UObject *currentObj = (UObject *) this;
	currentObj->ProcessEvent(pFunc, &params);

	pFunc->FunctionFlags = flags;
}

// Function bp_lobby_friend.bp_lobby_friend_C.EventLobbyFriendReplyRelationReq
// (BlueprintCallable, BlueprintEvent)

void Abp_lobby_friend_C::EventLobbyFriendReplyRelationReq()
{
	static UFunction *pFunc = 0;
	if (!pFunc)
		pFunc = UObject::FindObject<UFunction>("Function bp_lobby_friend.bp_lobby_friend_C.EventLobbyFriendReplyRelationReq");

	Abp_lobby_friend_C_EventLobbyFriendReplyRelationReq_Params params;

	auto flags = pFunc->FunctionFlags;

	UObject *currentObj = (UObject *) this;
	currentObj->ProcessEvent(pFunc, &params);

	pFunc->FunctionFlags = flags;
}

// Function bp_lobby_friend.bp_lobby_friend_C.EventLobbyFriendScrollInnerList_NoFetch
// (BlueprintCallable, BlueprintEvent)

void Abp_lobby_friend_C::EventLobbyFriendScrollInnerList_NoFetch()
{
	static UFunction *pFunc = 0;
	if (!pFunc)
		pFunc = UObject::FindObject<UFunction>("Function bp_lobby_friend.bp_lobby_friend_C.EventLobbyFriendScrollInnerList_NoFetch");

	Abp_lobby_friend_C_EventLobbyFriendScrollInnerList_NoFetch_Params params;

	auto flags = pFunc->FunctionFlags;

	UObject *currentObj = (UObject *) this;
	currentObj->ProcessEvent(pFunc, &params);

	pFunc->FunctionFlags = flags;
}

// Function bp_lobby_friend.bp_lobby_friend_C.EventLobbyFriendScrollInnerList
// (BlueprintCallable, BlueprintEvent)

void Abp_lobby_friend_C::EventLobbyFriendScrollInnerList()
{
	static UFunction *pFunc = 0;
	if (!pFunc)
		pFunc = UObject::FindObject<UFunction>("Function bp_lobby_friend.bp_lobby_friend_C.EventLobbyFriendScrollInnerList");

	Abp_lobby_friend_C_EventLobbyFriendScrollInnerList_Params params;

	auto flags = pFunc->FunctionFlags;

	UObject *currentObj = (UObject *) this;
	currentObj->ProcessEvent(pFunc, &params);

	pFunc->FunctionFlags = flags;
}

// Function bp_lobby_friend.bp_lobby_friend_C.EventLobbyFriendBuildRelationReq_NoFetch
// (BlueprintCallable, BlueprintEvent)

void Abp_lobby_friend_C::EventLobbyFriendBuildRelationReq_NoFetch()
{
	static UFunction *pFunc = 0;
	if (!pFunc)
		pFunc = UObject::FindObject<UFunction>("Function bp_lobby_friend.bp_lobby_friend_C.EventLobbyFriendBuildRelationReq_NoFetch");

	Abp_lobby_friend_C_EventLobbyFriendBuildRelationReq_NoFetch_Params params;

	auto flags = pFunc->FunctionFlags;

	UObject *currentObj = (UObject *) this;
	currentObj->ProcessEvent(pFunc, &params);

	pFunc->FunctionFlags = flags;
}

// Function bp_lobby_friend.bp_lobby_friend_C.EventLobbyFriendBuildRelationReq
// (BlueprintCallable, BlueprintEvent)

void Abp_lobby_friend_C::EventLobbyFriendBuildRelationReq()
{
	static UFunction *pFunc = 0;
	if (!pFunc)
		pFunc = UObject::FindObject<UFunction>("Function bp_lobby_friend.bp_lobby_friend_C.EventLobbyFriendBuildRelationReq");

	Abp_lobby_friend_C_EventLobbyFriendBuildRelationReq_Params params;

	auto flags = pFunc->FunctionFlags;

	UObject *currentObj = (UObject *) this;
	currentObj->ProcessEvent(pFunc, &params);

	pFunc->FunctionFlags = flags;
}

// Function bp_lobby_friend.bp_lobby_friend_C.EventOpenMyCardPanelInFriendPanel_NoFetch
// (BlueprintCallable, BlueprintEvent)

void Abp_lobby_friend_C::EventOpenMyCardPanelInFriendPanel_NoFetch()
{
	static UFunction *pFunc = 0;
	if (!pFunc)
		pFunc = UObject::FindObject<UFunction>("Function bp_lobby_friend.bp_lobby_friend_C.EventOpenMyCardPanelInFriendPanel_NoFetch");

	Abp_lobby_friend_C_EventOpenMyCardPanelInFriendPanel_NoFetch_Params params;

	auto flags = pFunc->FunctionFlags;

	UObject *currentObj = (UObject *) this;
	currentObj->ProcessEvent(pFunc, &params);

	pFunc->FunctionFlags = flags;
}

// Function bp_lobby_friend.bp_lobby_friend_C.EventOpenMyCardPanelInFriendPanel
// (BlueprintCallable, BlueprintEvent)

void Abp_lobby_friend_C::EventOpenMyCardPanelInFriendPanel()
{
	static UFunction *pFunc = 0;
	if (!pFunc)
		pFunc = UObject::FindObject<UFunction>("Function bp_lobby_friend.bp_lobby_friend_C.EventOpenMyCardPanelInFriendPanel");

	Abp_lobby_friend_C_EventOpenMyCardPanelInFriendPanel_Params params;

	auto flags = pFunc->FunctionFlags;

	UObject *currentObj = (UObject *) this;
	currentObj->ProcessEvent(pFunc, &params);

	pFunc->FunctionFlags = flags;
}

// Function bp_lobby_friend.bp_lobby_friend_C.EventOpenIntimacyDescriptionPanel_NoFetch
// (BlueprintCallable, BlueprintEvent)

void Abp_lobby_friend_C::EventOpenIntimacyDescriptionPanel_NoFetch()
{
	static UFunction *pFunc = 0;
	if (!pFunc)
		pFunc = UObject::FindObject<UFunction>("Function bp_lobby_friend.bp_lobby_friend_C.EventOpenIntimacyDescriptionPanel_NoFetch");

	Abp_lobby_friend_C_EventOpenIntimacyDescriptionPanel_NoFetch_Params params;

	auto flags = pFunc->FunctionFlags;

	UObject *currentObj = (UObject *) this;
	currentObj->ProcessEvent(pFunc, &params);

	pFunc->FunctionFlags = flags;
}

// Function bp_lobby_friend.bp_lobby_friend_C.EventOpenIntimacyDescriptionPanel
// (BlueprintCallable, BlueprintEvent)

void Abp_lobby_friend_C::EventOpenIntimacyDescriptionPanel()
{
	static UFunction *pFunc = 0;
	if (!pFunc)
		pFunc = UObject::FindObject<UFunction>("Function bp_lobby_friend.bp_lobby_friend_C.EventOpenIntimacyDescriptionPanel");

	Abp_lobby_friend_C_EventOpenIntimacyDescriptionPanel_Params params;

	auto flags = pFunc->FunctionFlags;

	UObject *currentObj = (UObject *) this;
	currentObj->ProcessEvent(pFunc, &params);

	pFunc->FunctionFlags = flags;
}

// Function bp_lobby_friend.bp_lobby_friend_C.EventLobbyFriendWatch_NoFetch
// (BlueprintCallable, BlueprintEvent)

void Abp_lobby_friend_C::EventLobbyFriendWatch_NoFetch()
{
	static UFunction *pFunc = 0;
	if (!pFunc)
		pFunc = UObject::FindObject<UFunction>("Function bp_lobby_friend.bp_lobby_friend_C.EventLobbyFriendWatch_NoFetch");

	Abp_lobby_friend_C_EventLobbyFriendWatch_NoFetch_Params params;

	auto flags = pFunc->FunctionFlags;

	UObject *currentObj = (UObject *) this;
	currentObj->ProcessEvent(pFunc, &params);

	pFunc->FunctionFlags = flags;
}

// Function bp_lobby_friend.bp_lobby_friend_C.EventLobbyFriendWatch
// (BlueprintCallable, BlueprintEvent)

void Abp_lobby_friend_C::EventLobbyFriendWatch()
{
	static UFunction *pFunc = 0;
	if (!pFunc)
		pFunc = UObject::FindObject<UFunction>("Function bp_lobby_friend.bp_lobby_friend_C.EventLobbyFriendWatch");

	Abp_lobby_friend_C_EventLobbyFriendWatch_Params params;

	auto flags = pFunc->FunctionFlags;

	UObject *currentObj = (UObject *) this;
	currentObj->ProcessEvent(pFunc, &params);

	pFunc->FunctionFlags = flags;
}

// Function bp_lobby_friend.bp_lobby_friend_C.EventNearByOpenLocation_NoFetch
// (BlueprintCallable, BlueprintEvent)

void Abp_lobby_friend_C::EventNearByOpenLocation_NoFetch()
{
	static UFunction *pFunc = 0;
	if (!pFunc)
		pFunc = UObject::FindObject<UFunction>("Function bp_lobby_friend.bp_lobby_friend_C.EventNearByOpenLocation_NoFetch");

	Abp_lobby_friend_C_EventNearByOpenLocation_NoFetch_Params params;

	auto flags = pFunc->FunctionFlags;

	UObject *currentObj = (UObject *) this;
	currentObj->ProcessEvent(pFunc, &params);

	pFunc->FunctionFlags = flags;
}

// Function bp_lobby_friend.bp_lobby_friend_C.EventNearByOpenLocation
// (BlueprintCallable, BlueprintEvent)

void Abp_lobby_friend_C::EventNearByOpenLocation()
{
	static UFunction *pFunc = 0;
	if (!pFunc)
		pFunc = UObject::FindObject<UFunction>("Function bp_lobby_friend.bp_lobby_friend_C.EventNearByOpenLocation");

	Abp_lobby_friend_C_EventNearByOpenLocation_Params params;

	auto flags = pFunc->FunctionFlags;

	UObject *currentObj = (UObject *) this;
	currentObj->ProcessEvent(pFunc, &params);

	pFunc->FunctionFlags = flags;
}

// Function bp_lobby_friend.bp_lobby_friend_C.EventOpenNearByPanel_NoFetch
// (BlueprintCallable, BlueprintEvent)

void Abp_lobby_friend_C::EventOpenNearByPanel_NoFetch()
{
	static UFunction *pFunc = 0;
	if (!pFunc)
		pFunc = UObject::FindObject<UFunction>("Function bp_lobby_friend.bp_lobby_friend_C.EventOpenNearByPanel_NoFetch");

	Abp_lobby_friend_C_EventOpenNearByPanel_NoFetch_Params params;

	auto flags = pFunc->FunctionFlags;

	UObject *currentObj = (UObject *) this;
	currentObj->ProcessEvent(pFunc, &params);

	pFunc->FunctionFlags = flags;
}

// Function bp_lobby_friend.bp_lobby_friend_C.EventOpenNearByPanel
// (BlueprintCallable, BlueprintEvent)

void Abp_lobby_friend_C::EventOpenNearByPanel()
{
	static UFunction *pFunc = 0;
	if (!pFunc)
		pFunc = UObject::FindObject<UFunction>("Function bp_lobby_friend.bp_lobby_friend_C.EventOpenNearByPanel");

	Abp_lobby_friend_C_EventOpenNearByPanel_Params params;

	auto flags = pFunc->FunctionFlags;

	UObject *currentObj = (UObject *) this;
	currentObj->ProcessEvent(pFunc, &params);

	pFunc->FunctionFlags = flags;
}

// Function bp_lobby_friend.bp_lobby_friend_C.EventNearByUpdateFilterArray_NoFetch
// (BlueprintCallable, BlueprintEvent)

void Abp_lobby_friend_C::EventNearByUpdateFilterArray_NoFetch()
{
	static UFunction *pFunc = 0;
	if (!pFunc)
		pFunc = UObject::FindObject<UFunction>("Function bp_lobby_friend.bp_lobby_friend_C.EventNearByUpdateFilterArray_NoFetch");

	Abp_lobby_friend_C_EventNearByUpdateFilterArray_NoFetch_Params params;

	auto flags = pFunc->FunctionFlags;

	UObject *currentObj = (UObject *) this;
	currentObj->ProcessEvent(pFunc, &params);

	pFunc->FunctionFlags = flags;
}

// Function bp_lobby_friend.bp_lobby_friend_C.EventNearByUpdateFilterArray
// (BlueprintCallable, BlueprintEvent)

void Abp_lobby_friend_C::EventNearByUpdateFilterArray()
{
	static UFunction *pFunc = 0;
	if (!pFunc)
		pFunc = UObject::FindObject<UFunction>("Function bp_lobby_friend.bp_lobby_friend_C.EventNearByUpdateFilterArray");

	Abp_lobby_friend_C_EventNearByUpdateFilterArray_Params params;

	auto flags = pFunc->FunctionFlags;

	UObject *currentObj = (UObject *) this;
	currentObj->ProcessEvent(pFunc, &params);

	pFunc->FunctionFlags = flags;
}

// Function bp_lobby_friend.bp_lobby_friend_C.EventLobbyFriendSearchReq_NoFetch
// (BlueprintCallable, BlueprintEvent)

void Abp_lobby_friend_C::EventLobbyFriendSearchReq_NoFetch()
{
	static UFunction *pFunc = 0;
	if (!pFunc)
		pFunc = UObject::FindObject<UFunction>("Function bp_lobby_friend.bp_lobby_friend_C.EventLobbyFriendSearchReq_NoFetch");

	Abp_lobby_friend_C_EventLobbyFriendSearchReq_NoFetch_Params params;

	auto flags = pFunc->FunctionFlags;

	UObject *currentObj = (UObject *) this;
	currentObj->ProcessEvent(pFunc, &params);

	pFunc->FunctionFlags = flags;
}

// Function bp_lobby_friend.bp_lobby_friend_C.EventLobbyFriendSearchReq
// (BlueprintCallable, BlueprintEvent)

void Abp_lobby_friend_C::EventLobbyFriendSearchReq()
{
	static UFunction *pFunc = 0;
	if (!pFunc)
		pFunc = UObject::FindObject<UFunction>("Function bp_lobby_friend.bp_lobby_friend_C.EventLobbyFriendSearchReq");

	Abp_lobby_friend_C_EventLobbyFriendSearchReq_Params params;

	auto flags = pFunc->FunctionFlags;

	UObject *currentObj = (UObject *) this;
	currentObj->ProcessEvent(pFunc, &params);

	pFunc->FunctionFlags = flags;
}

// Function bp_lobby_friend.bp_lobby_friend_C.EventHideMasterPanel_NoFetch
// (BlueprintCallable, BlueprintEvent)

void Abp_lobby_friend_C::EventHideMasterPanel_NoFetch()
{
	static UFunction *pFunc = 0;
	if (!pFunc)
		pFunc = UObject::FindObject<UFunction>("Function bp_lobby_friend.bp_lobby_friend_C.EventHideMasterPanel_NoFetch");

	Abp_lobby_friend_C_EventHideMasterPanel_NoFetch_Params params;

	auto flags = pFunc->FunctionFlags;

	UObject *currentObj = (UObject *) this;
	currentObj->ProcessEvent(pFunc, &params);

	pFunc->FunctionFlags = flags;
}

// Function bp_lobby_friend.bp_lobby_friend_C.EventHideMasterPanel
// (BlueprintCallable, BlueprintEvent)

void Abp_lobby_friend_C::EventHideMasterPanel()
{
	static UFunction *pFunc = 0;
	if (!pFunc)
		pFunc = UObject::FindObject<UFunction>("Function bp_lobby_friend.bp_lobby_friend_C.EventHideMasterPanel");

	Abp_lobby_friend_C_EventHideMasterPanel_Params params;

	auto flags = pFunc->FunctionFlags;

	UObject *currentObj = (UObject *) this;
	currentObj->ProcessEvent(pFunc, &params);

	pFunc->FunctionFlags = flags;
}

// Function bp_lobby_friend.bp_lobby_friend_C.EventLobbyFriendApplyReq_NoFetch
// (BlueprintCallable, BlueprintEvent)

void Abp_lobby_friend_C::EventLobbyFriendApplyReq_NoFetch()
{
	static UFunction *pFunc = 0;
	if (!pFunc)
		pFunc = UObject::FindObject<UFunction>("Function bp_lobby_friend.bp_lobby_friend_C.EventLobbyFriendApplyReq_NoFetch");

	Abp_lobby_friend_C_EventLobbyFriendApplyReq_NoFetch_Params params;

	auto flags = pFunc->FunctionFlags;

	UObject *currentObj = (UObject *) this;
	currentObj->ProcessEvent(pFunc, &params);

	pFunc->FunctionFlags = flags;
}

// Function bp_lobby_friend.bp_lobby_friend_C.EventLobbyFriendApplyReq
// (BlueprintCallable, BlueprintEvent)

void Abp_lobby_friend_C::EventLobbyFriendApplyReq()
{
	static UFunction *pFunc = 0;
	if (!pFunc)
		pFunc = UObject::FindObject<UFunction>("Function bp_lobby_friend.bp_lobby_friend_C.EventLobbyFriendApplyReq");

	Abp_lobby_friend_C_EventLobbyFriendApplyReq_Params params;

	auto flags = pFunc->FunctionFlags;

	UObject *currentObj = (UObject *) this;
	currentObj->ProcessEvent(pFunc, &params);

	pFunc->FunctionFlags = flags;
}

// Function bp_lobby_friend.bp_lobby_friend_C.EventLobbyFriendDeleteReq_NoFetch
// (BlueprintCallable, BlueprintEvent)

void Abp_lobby_friend_C::EventLobbyFriendDeleteReq_NoFetch()
{
	static UFunction *pFunc = 0;
	if (!pFunc)
		pFunc = UObject::FindObject<UFunction>("Function bp_lobby_friend.bp_lobby_friend_C.EventLobbyFriendDeleteReq_NoFetch");

	Abp_lobby_friend_C_EventLobbyFriendDeleteReq_NoFetch_Params params;

	auto flags = pFunc->FunctionFlags;

	UObject *currentObj = (UObject *) this;
	currentObj->ProcessEvent(pFunc, &params);

	pFunc->FunctionFlags = flags;
}

// Function bp_lobby_friend.bp_lobby_friend_C.EventLobbyFriendDeleteReq
// (BlueprintCallable, BlueprintEvent)

void Abp_lobby_friend_C::EventLobbyFriendDeleteReq()
{
	static UFunction *pFunc = 0;
	if (!pFunc)
		pFunc = UObject::FindObject<UFunction>("Function bp_lobby_friend.bp_lobby_friend_C.EventLobbyFriendDeleteReq");

	Abp_lobby_friend_C_EventLobbyFriendDeleteReq_Params params;

	auto flags = pFunc->FunctionFlags;

	UObject *currentObj = (UObject *) this;
	currentObj->ProcessEvent(pFunc, &params);

	pFunc->FunctionFlags = flags;
}

// Function bp_lobby_friend.bp_lobby_friend_C.EventLobbyFriendMasterNotOpen_NoFetch
// (BlueprintCallable, BlueprintEvent)

void Abp_lobby_friend_C::EventLobbyFriendMasterNotOpen_NoFetch()
{
	static UFunction *pFunc = 0;
	if (!pFunc)
		pFunc = UObject::FindObject<UFunction>("Function bp_lobby_friend.bp_lobby_friend_C.EventLobbyFriendMasterNotOpen_NoFetch");

	Abp_lobby_friend_C_EventLobbyFriendMasterNotOpen_NoFetch_Params params;

	auto flags = pFunc->FunctionFlags;

	UObject *currentObj = (UObject *) this;
	currentObj->ProcessEvent(pFunc, &params);

	pFunc->FunctionFlags = flags;
}

// Function bp_lobby_friend.bp_lobby_friend_C.EventLobbyFriendMasterNotOpen
// (BlueprintCallable, BlueprintEvent)

void Abp_lobby_friend_C::EventLobbyFriendMasterNotOpen()
{
	static UFunction *pFunc = 0;
	if (!pFunc)
		pFunc = UObject::FindObject<UFunction>("Function bp_lobby_friend.bp_lobby_friend_C.EventLobbyFriendMasterNotOpen");

	Abp_lobby_friend_C_EventLobbyFriendMasterNotOpen_Params params;

	auto flags = pFunc->FunctionFlags;

	UObject *currentObj = (UObject *) this;
	currentObj->ProcessEvent(pFunc, &params);

	pFunc->FunctionFlags = flags;
}

// Function bp_lobby_friend.bp_lobby_friend_C.EventSetXYAPIShowRedPoint_NoFetch
// (BlueprintCallable, BlueprintEvent)

void Abp_lobby_friend_C::EventSetXYAPIShowRedPoint_NoFetch()
{
	static UFunction *pFunc = 0;
	if (!pFunc)
		pFunc = UObject::FindObject<UFunction>("Function bp_lobby_friend.bp_lobby_friend_C.EventSetXYAPIShowRedPoint_NoFetch");

	Abp_lobby_friend_C_EventSetXYAPIShowRedPoint_NoFetch_Params params;

	auto flags = pFunc->FunctionFlags;

	UObject *currentObj = (UObject *) this;
	currentObj->ProcessEvent(pFunc, &params);

	pFunc->FunctionFlags = flags;
}

// Function bp_lobby_friend.bp_lobby_friend_C.EventSetXYAPIShowRedPoint
// (BlueprintCallable, BlueprintEvent)

void Abp_lobby_friend_C::EventSetXYAPIShowRedPoint()
{
	static UFunction *pFunc = 0;
	if (!pFunc)
		pFunc = UObject::FindObject<UFunction>("Function bp_lobby_friend.bp_lobby_friend_C.EventSetXYAPIShowRedPoint");

	Abp_lobby_friend_C_EventSetXYAPIShowRedPoint_Params params;

	auto flags = pFunc->FunctionFlags;

	UObject *currentObj = (UObject *) this;
	currentObj->ProcessEvent(pFunc, &params);

	pFunc->FunctionFlags = flags;
}

// Function bp_lobby_friend.bp_lobby_friend_C.EventLobbySendItemReq_NoFetch
// (BlueprintCallable, BlueprintEvent)

void Abp_lobby_friend_C::EventLobbySendItemReq_NoFetch()
{
	static UFunction *pFunc = 0;
	if (!pFunc)
		pFunc = UObject::FindObject<UFunction>("Function bp_lobby_friend.bp_lobby_friend_C.EventLobbySendItemReq_NoFetch");

	Abp_lobby_friend_C_EventLobbySendItemReq_NoFetch_Params params;

	auto flags = pFunc->FunctionFlags;

	UObject *currentObj = (UObject *) this;
	currentObj->ProcessEvent(pFunc, &params);

	pFunc->FunctionFlags = flags;
}

// Function bp_lobby_friend.bp_lobby_friend_C.EventLobbySendItemReq
// (BlueprintCallable, BlueprintEvent)

void Abp_lobby_friend_C::EventLobbySendItemReq()
{
	static UFunction *pFunc = 0;
	if (!pFunc)
		pFunc = UObject::FindObject<UFunction>("Function bp_lobby_friend.bp_lobby_friend_C.EventLobbySendItemReq");

	Abp_lobby_friend_C_EventLobbySendItemReq_Params params;

	auto flags = pFunc->FunctionFlags;

	UObject *currentObj = (UObject *) this;
	currentObj->ProcessEvent(pFunc, &params);

	pFunc->FunctionFlags = flags;
}

// Function bp_lobby_friend.bp_lobby_friend_C.EventSetXYAPIHideRedPoint_NoFetch
// (BlueprintCallable, BlueprintEvent)

void Abp_lobby_friend_C::EventSetXYAPIHideRedPoint_NoFetch()
{
	static UFunction *pFunc = 0;
	if (!pFunc)
		pFunc = UObject::FindObject<UFunction>("Function bp_lobby_friend.bp_lobby_friend_C.EventSetXYAPIHideRedPoint_NoFetch");

	Abp_lobby_friend_C_EventSetXYAPIHideRedPoint_NoFetch_Params params;

	auto flags = pFunc->FunctionFlags;

	UObject *currentObj = (UObject *) this;
	currentObj->ProcessEvent(pFunc, &params);

	pFunc->FunctionFlags = flags;
}

// Function bp_lobby_friend.bp_lobby_friend_C.EventSetXYAPIHideRedPoint
// (BlueprintCallable, BlueprintEvent)

void Abp_lobby_friend_C::EventSetXYAPIHideRedPoint()
{
	static UFunction *pFunc = 0;
	if (!pFunc)
		pFunc = UObject::FindObject<UFunction>("Function bp_lobby_friend.bp_lobby_friend_C.EventSetXYAPIHideRedPoint");

	Abp_lobby_friend_C_EventSetXYAPIHideRedPoint_Params params;

	auto flags = pFunc->FunctionFlags;

	UObject *currentObj = (UObject *) this;
	currentObj->ProcessEvent(pFunc, &params);

	pFunc->FunctionFlags = flags;
}

// Function bp_lobby_friend.bp_lobby_friend_C.EventFetchNewNearByPersonInfoList_NoFetch
// (BlueprintCallable, BlueprintEvent)

void Abp_lobby_friend_C::EventFetchNewNearByPersonInfoList_NoFetch()
{
	static UFunction *pFunc = 0;
	if (!pFunc)
		pFunc = UObject::FindObject<UFunction>("Function bp_lobby_friend.bp_lobby_friend_C.EventFetchNewNearByPersonInfoList_NoFetch");

	Abp_lobby_friend_C_EventFetchNewNearByPersonInfoList_NoFetch_Params params;

	auto flags = pFunc->FunctionFlags;

	UObject *currentObj = (UObject *) this;
	currentObj->ProcessEvent(pFunc, &params);

	pFunc->FunctionFlags = flags;
}

// Function bp_lobby_friend.bp_lobby_friend_C.EventFetchNewNearByPersonInfoList
// (BlueprintCallable, BlueprintEvent)

void Abp_lobby_friend_C::EventFetchNewNearByPersonInfoList()
{
	static UFunction *pFunc = 0;
	if (!pFunc)
		pFunc = UObject::FindObject<UFunction>("Function bp_lobby_friend.bp_lobby_friend_C.EventFetchNewNearByPersonInfoList");

	Abp_lobby_friend_C_EventFetchNewNearByPersonInfoList_Params params;

	auto flags = pFunc->FunctionFlags;

	UObject *currentObj = (UObject *) this;
	currentObj->ProcessEvent(pFunc, &params);

	pFunc->FunctionFlags = flags;
}

// Function bp_lobby_friend.bp_lobby_friend_C.EventLobbySendFriendFinish_NoFetch
// (BlueprintCallable, BlueprintEvent)

void Abp_lobby_friend_C::EventLobbySendFriendFinish_NoFetch()
{
	static UFunction *pFunc = 0;
	if (!pFunc)
		pFunc = UObject::FindObject<UFunction>("Function bp_lobby_friend.bp_lobby_friend_C.EventLobbySendFriendFinish_NoFetch");

	Abp_lobby_friend_C_EventLobbySendFriendFinish_NoFetch_Params params;

	auto flags = pFunc->FunctionFlags;

	UObject *currentObj = (UObject *) this;
	currentObj->ProcessEvent(pFunc, &params);

	pFunc->FunctionFlags = flags;
}

// Function bp_lobby_friend.bp_lobby_friend_C.EventLobbySendFriendFinish
// (BlueprintCallable, BlueprintEvent)

void Abp_lobby_friend_C::EventLobbySendFriendFinish()
{
	static UFunction *pFunc = 0;
	if (!pFunc)
		pFunc = UObject::FindObject<UFunction>("Function bp_lobby_friend.bp_lobby_friend_C.EventLobbySendFriendFinish");

	Abp_lobby_friend_C_EventLobbySendFriendFinish_Params params;

	auto flags = pFunc->FunctionFlags;

	UObject *currentObj = (UObject *) this;
	currentObj->ProcessEvent(pFunc, &params);

	pFunc->FunctionFlags = flags;
}

// Function bp_lobby_friend.bp_lobby_friend_C.EventLobbyShowRecentLikePanel_NoFetch
// (BlueprintCallable, BlueprintEvent)

void Abp_lobby_friend_C::EventLobbyShowRecentLikePanel_NoFetch()
{
	static UFunction *pFunc = 0;
	if (!pFunc)
		pFunc = UObject::FindObject<UFunction>("Function bp_lobby_friend.bp_lobby_friend_C.EventLobbyShowRecentLikePanel_NoFetch");

	Abp_lobby_friend_C_EventLobbyShowRecentLikePanel_NoFetch_Params params;

	auto flags = pFunc->FunctionFlags;

	UObject *currentObj = (UObject *) this;
	currentObj->ProcessEvent(pFunc, &params);

	pFunc->FunctionFlags = flags;
}

// Function bp_lobby_friend.bp_lobby_friend_C.EventLobbyShowRecentLikePanel
// (BlueprintCallable, BlueprintEvent)

void Abp_lobby_friend_C::EventLobbyShowRecentLikePanel()
{
	static UFunction *pFunc = 0;
	if (!pFunc)
		pFunc = UObject::FindObject<UFunction>("Function bp_lobby_friend.bp_lobby_friend_C.EventLobbyShowRecentLikePanel");

	Abp_lobby_friend_C_EventLobbyShowRecentLikePanel_Params params;

	auto flags = pFunc->FunctionFlags;

	UObject *currentObj = (UObject *) this;
	currentObj->ProcessEvent(pFunc, &params);

	pFunc->FunctionFlags = flags;
}

// Function bp_lobby_friend.bp_lobby_friend_C.EventLobbyPresentCoinReq_NoFetch
// (BlueprintCallable, BlueprintEvent)

void Abp_lobby_friend_C::EventLobbyPresentCoinReq_NoFetch()
{
	static UFunction *pFunc = 0;
	if (!pFunc)
		pFunc = UObject::FindObject<UFunction>("Function bp_lobby_friend.bp_lobby_friend_C.EventLobbyPresentCoinReq_NoFetch");

	Abp_lobby_friend_C_EventLobbyPresentCoinReq_NoFetch_Params params;

	auto flags = pFunc->FunctionFlags;

	UObject *currentObj = (UObject *) this;
	currentObj->ProcessEvent(pFunc, &params);

	pFunc->FunctionFlags = flags;
}

// Function bp_lobby_friend.bp_lobby_friend_C.EventLobbyPresentCoinReq
// (BlueprintCallable, BlueprintEvent)

void Abp_lobby_friend_C::EventLobbyPresentCoinReq()
{
	static UFunction *pFunc = 0;
	if (!pFunc)
		pFunc = UObject::FindObject<UFunction>("Function bp_lobby_friend.bp_lobby_friend_C.EventLobbyPresentCoinReq");

	Abp_lobby_friend_C_EventLobbyPresentCoinReq_Params params;

	auto flags = pFunc->FunctionFlags;

	UObject *currentObj = (UObject *) this;
	currentObj->ProcessEvent(pFunc, &params);

	pFunc->FunctionFlags = flags;
}

// Function bp_lobby_friend.bp_lobby_friend_C.EventXYAPISetUrl_NoFetch
// (BlueprintCallable, BlueprintEvent)

void Abp_lobby_friend_C::EventXYAPISetUrl_NoFetch()
{
	static UFunction *pFunc = 0;
	if (!pFunc)
		pFunc = UObject::FindObject<UFunction>("Function bp_lobby_friend.bp_lobby_friend_C.EventXYAPISetUrl_NoFetch");

	Abp_lobby_friend_C_EventXYAPISetUrl_NoFetch_Params params;

	auto flags = pFunc->FunctionFlags;

	UObject *currentObj = (UObject *) this;
	currentObj->ProcessEvent(pFunc, &params);

	pFunc->FunctionFlags = flags;
}

// Function bp_lobby_friend.bp_lobby_friend_C.EventXYAPISetUrl
// (BlueprintCallable, BlueprintEvent)

void Abp_lobby_friend_C::EventXYAPISetUrl()
{
	static UFunction *pFunc = 0;
	if (!pFunc)
		pFunc = UObject::FindObject<UFunction>("Function bp_lobby_friend.bp_lobby_friend_C.EventXYAPISetUrl");

	Abp_lobby_friend_C_EventXYAPISetUrl_Params params;

	auto flags = pFunc->FunctionFlags;

	UObject *currentObj = (UObject *) this;
	currentObj->ProcessEvent(pFunc, &params);

	pFunc->FunctionFlags = flags;
}

// Function bp_lobby_friend.bp_lobby_friend_C.EventLobbyFriendProfileReq_NoFetch
// (BlueprintCallable, BlueprintEvent)

void Abp_lobby_friend_C::EventLobbyFriendProfileReq_NoFetch()
{
	static UFunction *pFunc = 0;
	if (!pFunc)
		pFunc = UObject::FindObject<UFunction>("Function bp_lobby_friend.bp_lobby_friend_C.EventLobbyFriendProfileReq_NoFetch");

	Abp_lobby_friend_C_EventLobbyFriendProfileReq_NoFetch_Params params;

	auto flags = pFunc->FunctionFlags;

	UObject *currentObj = (UObject *) this;
	currentObj->ProcessEvent(pFunc, &params);

	pFunc->FunctionFlags = flags;
}

// Function bp_lobby_friend.bp_lobby_friend_C.EventLobbyFriendProfileReq
// (BlueprintCallable, BlueprintEvent)

void Abp_lobby_friend_C::EventLobbyFriendProfileReq()
{
	static UFunction *pFunc = 0;
	if (!pFunc)
		pFunc = UObject::FindObject<UFunction>("Function bp_lobby_friend.bp_lobby_friend_C.EventLobbyFriendProfileReq");

	Abp_lobby_friend_C_EventLobbyFriendProfileReq_Params params;

	auto flags = pFunc->FunctionFlags;

	UObject *currentObj = (UObject *) this;
	currentObj->ProcessEvent(pFunc, &params);

	pFunc->FunctionFlags = flags;
}

// Function bp_lobby_friend.bp_lobby_friend_C.EventLobbyFriendSendItemList_NoFetch
// (BlueprintCallable, BlueprintEvent)

void Abp_lobby_friend_C::EventLobbyFriendSendItemList_NoFetch()
{
	static UFunction *pFunc = 0;
	if (!pFunc)
		pFunc = UObject::FindObject<UFunction>("Function bp_lobby_friend.bp_lobby_friend_C.EventLobbyFriendSendItemList_NoFetch");

	Abp_lobby_friend_C_EventLobbyFriendSendItemList_NoFetch_Params params;

	auto flags = pFunc->FunctionFlags;

	UObject *currentObj = (UObject *) this;
	currentObj->ProcessEvent(pFunc, &params);

	pFunc->FunctionFlags = flags;
}

// Function bp_lobby_friend.bp_lobby_friend_C.EventLobbyFriendSendItemList
// (BlueprintCallable, BlueprintEvent)

void Abp_lobby_friend_C::EventLobbyFriendSendItemList()
{
	static UFunction *pFunc = 0;
	if (!pFunc)
		pFunc = UObject::FindObject<UFunction>("Function bp_lobby_friend.bp_lobby_friend_C.EventLobbyFriendSendItemList");

	Abp_lobby_friend_C_EventLobbyFriendSendItemList_Params params;

	auto flags = pFunc->FunctionFlags;

	UObject *currentObj = (UObject *) this;
	currentObj->ProcessEvent(pFunc, &params);

	pFunc->FunctionFlags = flags;
}

// Function bp_lobby_friend.bp_lobby_friend_C.EventCheckWatchingSwitch_NoFetch
// (BlueprintCallable, BlueprintEvent)

void Abp_lobby_friend_C::EventCheckWatchingSwitch_NoFetch()
{
	static UFunction *pFunc = 0;
	if (!pFunc)
		pFunc = UObject::FindObject<UFunction>("Function bp_lobby_friend.bp_lobby_friend_C.EventCheckWatchingSwitch_NoFetch");

	Abp_lobby_friend_C_EventCheckWatchingSwitch_NoFetch_Params params;

	auto flags = pFunc->FunctionFlags;

	UObject *currentObj = (UObject *) this;
	currentObj->ProcessEvent(pFunc, &params);

	pFunc->FunctionFlags = flags;
}

// Function bp_lobby_friend.bp_lobby_friend_C.EventCheckWatchingSwitch
// (BlueprintCallable, BlueprintEvent)

void Abp_lobby_friend_C::EventCheckWatchingSwitch()
{
	static UFunction *pFunc = 0;
	if (!pFunc)
		pFunc = UObject::FindObject<UFunction>("Function bp_lobby_friend.bp_lobby_friend_C.EventCheckWatchingSwitch");

	Abp_lobby_friend_C_EventCheckWatchingSwitch_Params params;

	auto flags = pFunc->FunctionFlags;

	UObject *currentObj = (UObject *) this;
	currentObj->ProcessEvent(pFunc, &params);

	pFunc->FunctionFlags = flags;
}

// Function bp_lobby_friend.bp_lobby_friend_C.EventLobbyFriendScrollApplyList_NoFetch
// (BlueprintCallable, BlueprintEvent)

void Abp_lobby_friend_C::EventLobbyFriendScrollApplyList_NoFetch()
{
	static UFunction *pFunc = 0;
	if (!pFunc)
		pFunc = UObject::FindObject<UFunction>("Function bp_lobby_friend.bp_lobby_friend_C.EventLobbyFriendScrollApplyList_NoFetch");

	Abp_lobby_friend_C_EventLobbyFriendScrollApplyList_NoFetch_Params params;

	auto flags = pFunc->FunctionFlags;

	UObject *currentObj = (UObject *) this;
	currentObj->ProcessEvent(pFunc, &params);

	pFunc->FunctionFlags = flags;
}

// Function bp_lobby_friend.bp_lobby_friend_C.EventLobbyFriendScrollApplyList
// (BlueprintCallable, BlueprintEvent)

void Abp_lobby_friend_C::EventLobbyFriendScrollApplyList()
{
	static UFunction *pFunc = 0;
	if (!pFunc)
		pFunc = UObject::FindObject<UFunction>("Function bp_lobby_friend.bp_lobby_friend_C.EventLobbyFriendScrollApplyList");

	Abp_lobby_friend_C_EventLobbyFriendScrollApplyList_Params params;

	auto flags = pFunc->FunctionFlags;

	UObject *currentObj = (UObject *) this;
	currentObj->ProcessEvent(pFunc, &params);

	pFunc->FunctionFlags = flags;
}

// Function bp_lobby_friend.bp_lobby_friend_C.EventLobbyFriendRelationClick_NoFetch
// (BlueprintCallable, BlueprintEvent)

void Abp_lobby_friend_C::EventLobbyFriendRelationClick_NoFetch()
{
	static UFunction *pFunc = 0;
	if (!pFunc)
		pFunc = UObject::FindObject<UFunction>("Function bp_lobby_friend.bp_lobby_friend_C.EventLobbyFriendRelationClick_NoFetch");

	Abp_lobby_friend_C_EventLobbyFriendRelationClick_NoFetch_Params params;

	auto flags = pFunc->FunctionFlags;

	UObject *currentObj = (UObject *) this;
	currentObj->ProcessEvent(pFunc, &params);

	pFunc->FunctionFlags = flags;
}

// Function bp_lobby_friend.bp_lobby_friend_C.EventLobbyFriendRelationClick
// (BlueprintCallable, BlueprintEvent)

void Abp_lobby_friend_C::EventLobbyFriendRelationClick()
{
	static UFunction *pFunc = 0;
	if (!pFunc)
		pFunc = UObject::FindObject<UFunction>("Function bp_lobby_friend.bp_lobby_friend_C.EventLobbyFriendRelationClick");

	Abp_lobby_friend_C_EventLobbyFriendRelationClick_Params params;

	auto flags = pFunc->FunctionFlags;

	UObject *currentObj = (UObject *) this;
	currentObj->ProcessEvent(pFunc, &params);

	pFunc->FunctionFlags = flags;
}

// Function bp_lobby_friend.bp_lobby_friend_C.EventLobbyFriendScrollPlatList_NoFetch
// (BlueprintCallable, BlueprintEvent)

void Abp_lobby_friend_C::EventLobbyFriendScrollPlatList_NoFetch()
{
	static UFunction *pFunc = 0;
	if (!pFunc)
		pFunc = UObject::FindObject<UFunction>("Function bp_lobby_friend.bp_lobby_friend_C.EventLobbyFriendScrollPlatList_NoFetch");

	Abp_lobby_friend_C_EventLobbyFriendScrollPlatList_NoFetch_Params params;

	auto flags = pFunc->FunctionFlags;

	UObject *currentObj = (UObject *) this;
	currentObj->ProcessEvent(pFunc, &params);

	pFunc->FunctionFlags = flags;
}

// Function bp_lobby_friend.bp_lobby_friend_C.EventLobbyFriendScrollPlatList
// (BlueprintCallable, BlueprintEvent)

void Abp_lobby_friend_C::EventLobbyFriendScrollPlatList()
{
	static UFunction *pFunc = 0;
	if (!pFunc)
		pFunc = UObject::FindObject<UFunction>("Function bp_lobby_friend.bp_lobby_friend_C.EventLobbyFriendScrollPlatList");

	Abp_lobby_friend_C_EventLobbyFriendScrollPlatList_Params params;

	auto flags = pFunc->FunctionFlags;

	UObject *currentObj = (UObject *) this;
	currentObj->ProcessEvent(pFunc, &params);

	pFunc->FunctionFlags = flags;
}

// Function bp_lobby_friend.bp_lobby_friend_C.EventLobbyFriendAddQQFriend_NoFetch
// (BlueprintCallable, BlueprintEvent)

void Abp_lobby_friend_C::EventLobbyFriendAddQQFriend_NoFetch()
{
	static UFunction *pFunc = 0;
	if (!pFunc)
		pFunc = UObject::FindObject<UFunction>("Function bp_lobby_friend.bp_lobby_friend_C.EventLobbyFriendAddQQFriend_NoFetch");

	Abp_lobby_friend_C_EventLobbyFriendAddQQFriend_NoFetch_Params params;

	auto flags = pFunc->FunctionFlags;

	UObject *currentObj = (UObject *) this;
	currentObj->ProcessEvent(pFunc, &params);

	pFunc->FunctionFlags = flags;
}

// Function bp_lobby_friend.bp_lobby_friend_C.EventLobbyFriendAddQQFriend
// (BlueprintCallable, BlueprintEvent)

void Abp_lobby_friend_C::EventLobbyFriendAddQQFriend()
{
	static UFunction *pFunc = 0;
	if (!pFunc)
		pFunc = UObject::FindObject<UFunction>("Function bp_lobby_friend.bp_lobby_friend_C.EventLobbyFriendAddQQFriend");

	Abp_lobby_friend_C_EventLobbyFriendAddQQFriend_Params params;

	auto flags = pFunc->FunctionFlags;

	UObject *currentObj = (UObject *) this;
	currentObj->ProcessEvent(pFunc, &params);

	pFunc->FunctionFlags = flags;
}

// Function bp_lobby_friend.bp_lobby_friend_C.EventLobbyFriendDeleteRelationReq_NoFetch
// (BlueprintCallable, BlueprintEvent)

void Abp_lobby_friend_C::EventLobbyFriendDeleteRelationReq_NoFetch()
{
	static UFunction *pFunc = 0;
	if (!pFunc)
		pFunc = UObject::FindObject<UFunction>("Function bp_lobby_friend.bp_lobby_friend_C.EventLobbyFriendDeleteRelationReq_NoFetch");

	Abp_lobby_friend_C_EventLobbyFriendDeleteRelationReq_NoFetch_Params params;

	auto flags = pFunc->FunctionFlags;

	UObject *currentObj = (UObject *) this;
	currentObj->ProcessEvent(pFunc, &params);

	pFunc->FunctionFlags = flags;
}

// Function bp_lobby_friend.bp_lobby_friend_C.EventLobbyFriendDeleteRelationReq
// (BlueprintCallable, BlueprintEvent)

void Abp_lobby_friend_C::EventLobbyFriendDeleteRelationReq()
{
	static UFunction *pFunc = 0;
	if (!pFunc)
		pFunc = UObject::FindObject<UFunction>("Function bp_lobby_friend.bp_lobby_friend_C.EventLobbyFriendDeleteRelationReq");

	Abp_lobby_friend_C_EventLobbyFriendDeleteRelationReq_Params params;

	auto flags = pFunc->FunctionFlags;

	UObject *currentObj = (UObject *) this;
	currentObj->ProcessEvent(pFunc, &params);

	pFunc->FunctionFlags = flags;
}

// Function bp_lobby_friend.bp_lobby_friend_C.EventLobbyFriendChat_NoFetch
// (BlueprintCallable, BlueprintEvent)

void Abp_lobby_friend_C::EventLobbyFriendChat_NoFetch()
{
	static UFunction *pFunc = 0;
	if (!pFunc)
		pFunc = UObject::FindObject<UFunction>("Function bp_lobby_friend.bp_lobby_friend_C.EventLobbyFriendChat_NoFetch");

	Abp_lobby_friend_C_EventLobbyFriendChat_NoFetch_Params params;

	auto flags = pFunc->FunctionFlags;

	UObject *currentObj = (UObject *) this;
	currentObj->ProcessEvent(pFunc, &params);

	pFunc->FunctionFlags = flags;
}

// Function bp_lobby_friend.bp_lobby_friend_C.EventLobbyFriendChat
// (BlueprintCallable, BlueprintEvent)

void Abp_lobby_friend_C::EventLobbyFriendChat()
{
	static UFunction *pFunc = 0;
	if (!pFunc)
		pFunc = UObject::FindObject<UFunction>("Function bp_lobby_friend.bp_lobby_friend_C.EventLobbyFriendChat");

	Abp_lobby_friend_C_EventLobbyFriendChat_Params params;

	auto flags = pFunc->FunctionFlags;

	UObject *currentObj = (UObject *) this;
	currentObj->ProcessEvent(pFunc, &params);

	pFunc->FunctionFlags = flags;
}

// Function bp_lobby_friend.bp_lobby_friend_C.EventOpenMasterPanel_NoFetch
// (BlueprintCallable, BlueprintEvent)

void Abp_lobby_friend_C::EventOpenMasterPanel_NoFetch()
{
	static UFunction *pFunc = 0;
	if (!pFunc)
		pFunc = UObject::FindObject<UFunction>("Function bp_lobby_friend.bp_lobby_friend_C.EventOpenMasterPanel_NoFetch");

	Abp_lobby_friend_C_EventOpenMasterPanel_NoFetch_Params params;

	auto flags = pFunc->FunctionFlags;

	UObject *currentObj = (UObject *) this;
	currentObj->ProcessEvent(pFunc, &params);

	pFunc->FunctionFlags = flags;
}

// Function bp_lobby_friend.bp_lobby_friend_C.EventOpenMasterPanel
// (BlueprintCallable, BlueprintEvent)

void Abp_lobby_friend_C::EventOpenMasterPanel()
{
	static UFunction *pFunc = 0;
	if (!pFunc)
		pFunc = UObject::FindObject<UFunction>("Function bp_lobby_friend.bp_lobby_friend_C.EventOpenMasterPanel");

	Abp_lobby_friend_C_EventOpenMasterPanel_Params params;

	auto flags = pFunc->FunctionFlags;

	UObject *currentObj = (UObject *) this;
	currentObj->ProcessEvent(pFunc, &params);

	pFunc->FunctionFlags = flags;
}

// Function bp_lobby_friend.bp_lobby_friend_C.EventLobbyFriendGetBlackListReq_NoFetch
// (BlueprintCallable, BlueprintEvent)

void Abp_lobby_friend_C::EventLobbyFriendGetBlackListReq_NoFetch()
{
	static UFunction *pFunc = 0;
	if (!pFunc)
		pFunc = UObject::FindObject<UFunction>("Function bp_lobby_friend.bp_lobby_friend_C.EventLobbyFriendGetBlackListReq_NoFetch");

	Abp_lobby_friend_C_EventLobbyFriendGetBlackListReq_NoFetch_Params params;

	auto flags = pFunc->FunctionFlags;

	UObject *currentObj = (UObject *) this;
	currentObj->ProcessEvent(pFunc, &params);

	pFunc->FunctionFlags = flags;
}

// Function bp_lobby_friend.bp_lobby_friend_C.EventLobbyFriendGetBlackListReq
// (BlueprintCallable, BlueprintEvent)

void Abp_lobby_friend_C::EventLobbyFriendGetBlackListReq()
{
	static UFunction *pFunc = 0;
	if (!pFunc)
		pFunc = UObject::FindObject<UFunction>("Function bp_lobby_friend.bp_lobby_friend_C.EventLobbyFriendGetBlackListReq");

	Abp_lobby_friend_C_EventLobbyFriendGetBlackListReq_Params params;

	auto flags = pFunc->FunctionFlags;

	UObject *currentObj = (UObject *) this;
	currentObj->ProcessEvent(pFunc, &params);

	pFunc->FunctionFlags = flags;
}

// Function bp_lobby_friend.bp_lobby_friend_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void Abp_lobby_friend_C::UserConstructionScript()
{
	static UFunction *pFunc = 0;
	if (!pFunc)
		pFunc = UObject::FindObject<UFunction>("Function bp_lobby_friend.bp_lobby_friend_C.UserConstructionScript");

	Abp_lobby_friend_C_UserConstructionScript_Params params;

	auto flags = pFunc->FunctionFlags;

	UObject *currentObj = (UObject *) this;
	currentObj->ProcessEvent(pFunc, &params);

	pFunc->FunctionFlags = flags;
}

}

