#pragma once

// PlayerUnknown's Battlegrounds (0.27.0) SDK Generated By @IDRAGONCHEATS
#include "../SDK.hpp"

namespace SDK
{
//---------------------------------------------------------------------------
//Parameters
//---------------------------------------------------------------------------

// Function bp_pet_manager.bp_pet_manager_C.UserConstructionScript
struct Abp_pet_manager_C_UserConstructionScript_Params
{
};

}

