#pragma once

// PlayerUnknown's Battlegrounds (0.27.0) SDK Generated By @IDRAGONCHEATS
#include "../SDK.hpp"

namespace SDK
{
//---------------------------------------------------------------------------
//Parameters
//---------------------------------------------------------------------------

// Function UAESharedModule.UAEBlackboard.SetValueAsWeakObject
struct UUAEBlackboard_SetValueAsWeakObject_Params
{
	struct FUAEBlackboardKeySelector                   Key;                                                      // (ConstParm, Parm, OutParm, ReferenceParm)
	class UObject*                                     ObjectValue;                                              // (Parm, ZeroConstructor, IsPlainOldData)
};

// Function UAESharedModule.UAEBlackboard.SetValueAsVector
struct UUAEBlackboard_SetValueAsVector_Params
{
	struct FUAEBlackboardKeySelector                   Key;                                                      // (ConstParm, Parm, OutParm, ReferenceParm)
	struct FVector                                     VectorValue;                                              // (Parm, IsPlainOldData)
};

// Function UAESharedModule.UAEBlackboard.SetValueAsString
struct UUAEBlackboard_SetValueAsString_Params
{
	struct FUAEBlackboardKeySelector                   Key;                                                      // (ConstParm, Parm, OutParm, ReferenceParm)
	struct FString                                     StringValue;                                              // (Parm, ZeroConstructor)
};

// Function UAESharedModule.UAEBlackboard.SetValueAsRotator
struct UUAEBlackboard_SetValueAsRotator_Params
{
	struct FUAEBlackboardKeySelector                   Key;                                                      // (ConstParm, Parm, OutParm, ReferenceParm)
	struct FRotator                                    VectorValue;                                              // (Parm, IsPlainOldData)
};

// Function UAESharedModule.UAEBlackboard.SetValueAsObject
struct UUAEBlackboard_SetValueAsObject_Params
{
	struct FUAEBlackboardKeySelector                   Key;                                                      // (ConstParm, Parm, OutParm, ReferenceParm)
	class UObject*                                     ObjectValue;                                              // (Parm, ZeroConstructor, IsPlainOldData)
};

// Function UAESharedModule.UAEBlackboard.SetValueAsName
struct UUAEBlackboard_SetValueAsName_Params
{
	struct FUAEBlackboardKeySelector                   Key;                                                      // (ConstParm, Parm, OutParm, ReferenceParm)
	struct FName                                       NameValue;                                                // (Parm, ZeroConstructor, IsPlainOldData)
};

// Function UAESharedModule.UAEBlackboard.SetValueAsInt
struct UUAEBlackboard_SetValueAsInt_Params
{
	struct FUAEBlackboardKeySelector                   Key;                                                      // (ConstParm, Parm, OutParm, ReferenceParm)
	int                                                IntValue;                                                 // (Parm, ZeroConstructor, IsPlainOldData)
};

// Function UAESharedModule.UAEBlackboard.SetValueAsFloat
struct UUAEBlackboard_SetValueAsFloat_Params
{
	struct FUAEBlackboardKeySelector                   Key;                                                      // (ConstParm, Parm, OutParm, ReferenceParm)
	float                                              FloatValue;                                               // (Parm, ZeroConstructor, IsPlainOldData)
};

// Function UAESharedModule.UAEBlackboard.SetValueAsEnum
struct UUAEBlackboard_SetValueAsEnum_Params
{
	struct FUAEBlackboardKeySelector                   Key;                                                      // (ConstParm, Parm, OutParm, ReferenceParm)
	unsigned char                                      EnumValue;                                                // (Parm, ZeroConstructor, IsPlainOldData)
};

// Function UAESharedModule.UAEBlackboard.SetValueAsClass
struct UUAEBlackboard_SetValueAsClass_Params
{
	struct FUAEBlackboardKeySelector                   Key;                                                      // (ConstParm, Parm, OutParm, ReferenceParm)
	class UClass*                                      ClassValue;                                               // (Parm, ZeroConstructor, IsPlainOldData)
};

// Function UAESharedModule.UAEBlackboard.SetValueAsBool
struct UUAEBlackboard_SetValueAsBool_Params
{
	struct FUAEBlackboardKeySelector                   Key;                                                      // (ConstParm, Parm, OutParm, ReferenceParm)
	bool                                               BoolValue;                                                // (Parm, ZeroConstructor, IsPlainOldData)
};

// Function UAESharedModule.UAEBlackboard.IsExistWeakObject
struct UUAEBlackboard_IsExistWeakObject_Params
{
	struct FUAEBlackboardKeySelector                   Key;                                                      // (ConstParm, Parm, OutParm, ReferenceParm)
	bool                                               ReturnValue;                                              // (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData)
};

// Function UAESharedModule.UAEBlackboard.IsExistVector
struct UUAEBlackboard_IsExistVector_Params
{
	struct FUAEBlackboardKeySelector                   Key;                                                      // (ConstParm, Parm, OutParm, ReferenceParm)
	bool                                               ReturnValue;                                              // (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData)
};

// Function UAESharedModule.UAEBlackboard.IsExistString
struct UUAEBlackboard_IsExistString_Params
{
	struct FUAEBlackboardKeySelector                   Key;                                                      // (ConstParm, Parm, OutParm, ReferenceParm)
	bool                                               ReturnValue;                                              // (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData)
};

// Function UAESharedModule.UAEBlackboard.IsExistRotator
struct UUAEBlackboard_IsExistRotator_Params
{
	struct FUAEBlackboardKeySelector                   Key;                                                      // (ConstParm, Parm, OutParm, ReferenceParm)
	bool                                               ReturnValue;                                              // (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData)
};

// Function UAESharedModule.UAEBlackboard.IsExistObject
struct UUAEBlackboard_IsExistObject_Params
{
	struct FUAEBlackboardKeySelector                   Key;                                                      // (ConstParm, Parm, OutParm, ReferenceParm)
	bool                                               ReturnValue;                                              // (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData)
};

// Function UAESharedModule.UAEBlackboard.IsExistName
struct UUAEBlackboard_IsExistName_Params
{
	struct FUAEBlackboardKeySelector                   Key;                                                      // (ConstParm, Parm, OutParm, ReferenceParm)
	bool                                               ReturnValue;                                              // (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData)
};

// Function UAESharedModule.UAEBlackboard.IsExistInt
struct UUAEBlackboard_IsExistInt_Params
{
	struct FUAEBlackboardKeySelector                   Key;                                                      // (ConstParm, Parm, OutParm, ReferenceParm)
	bool                                               ReturnValue;                                              // (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData)
};

// Function UAESharedModule.UAEBlackboard.IsExistFloat
struct UUAEBlackboard_IsExistFloat_Params
{
	struct FUAEBlackboardKeySelector                   Key;                                                      // (ConstParm, Parm, OutParm, ReferenceParm)
	bool                                               ReturnValue;                                              // (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData)
};

// Function UAESharedModule.UAEBlackboard.IsExistEnum
struct UUAEBlackboard_IsExistEnum_Params
{
	struct FUAEBlackboardKeySelector                   Key;                                                      // (ConstParm, Parm, OutParm, ReferenceParm)
	bool                                               ReturnValue;                                              // (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData)
};

// Function UAESharedModule.UAEBlackboard.IsExistClass
struct UUAEBlackboard_IsExistClass_Params
{
	struct FUAEBlackboardKeySelector                   Key;                                                      // (ConstParm, Parm, OutParm, ReferenceParm)
	bool                                               ReturnValue;                                              // (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData)
};

// Function UAESharedModule.UAEBlackboard.IsExistBool
struct UUAEBlackboard_IsExistBool_Params
{
	struct FUAEBlackboardKeySelector                   Key;                                                      // (ConstParm, Parm, OutParm, ReferenceParm)
	bool                                               ReturnValue;                                              // (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData)
};

// Function UAESharedModule.UAEBlackboard.GetValueAsWeakObject
struct UUAEBlackboard_GetValueAsWeakObject_Params
{
	struct FUAEBlackboardKeySelector                   Key;                                                      // (ConstParm, Parm, OutParm, ReferenceParm)
	class UObject*                                     ReturnValue;                                              // (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData)
};

// Function UAESharedModule.UAEBlackboard.GetValueAsVector
struct UUAEBlackboard_GetValueAsVector_Params
{
	struct FUAEBlackboardKeySelector                   Key;                                                      // (ConstParm, Parm, OutParm, ReferenceParm)
	struct FVector                                     ReturnValue;                                              // (Parm, OutParm, ReturnParm, IsPlainOldData)
};

// Function UAESharedModule.UAEBlackboard.GetValueAsString
struct UUAEBlackboard_GetValueAsString_Params
{
	struct FUAEBlackboardKeySelector                   Key;                                                      // (ConstParm, Parm, OutParm, ReferenceParm)
	struct FString                                     ReturnValue;                                              // (Parm, OutParm, ZeroConstructor, ReturnParm)
};

// Function UAESharedModule.UAEBlackboard.GetValueAsRotator
struct UUAEBlackboard_GetValueAsRotator_Params
{
	struct FUAEBlackboardKeySelector                   Key;                                                      // (ConstParm, Parm, OutParm, ReferenceParm)
	struct FRotator                                    ReturnValue;                                              // (Parm, OutParm, ReturnParm, IsPlainOldData)
};

// Function UAESharedModule.UAEBlackboard.GetValueAsObject
struct UUAEBlackboard_GetValueAsObject_Params
{
	struct FUAEBlackboardKeySelector                   Key;                                                      // (ConstParm, Parm, OutParm, ReferenceParm)
	class UObject*                                     ReturnValue;                                              // (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData)
};

// Function UAESharedModule.UAEBlackboard.GetValueAsName
struct UUAEBlackboard_GetValueAsName_Params
{
	struct FUAEBlackboardKeySelector                   Key;                                                      // (ConstParm, Parm, OutParm, ReferenceParm)
	struct FName                                       ReturnValue;                                              // (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData)
};

// Function UAESharedModule.UAEBlackboard.GetValueAsInt
struct UUAEBlackboard_GetValueAsInt_Params
{
	struct FUAEBlackboardKeySelector                   Key;                                                      // (ConstParm, Parm, OutParm, ReferenceParm)
	int                                                ReturnValue;                                              // (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData)
};

// Function UAESharedModule.UAEBlackboard.GetValueAsFloat
struct UUAEBlackboard_GetValueAsFloat_Params
{
	struct FUAEBlackboardKeySelector                   Key;                                                      // (ConstParm, Parm, OutParm, ReferenceParm)
	float                                              ReturnValue;                                              // (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData)
};

// Function UAESharedModule.UAEBlackboard.GetValueAsEnum
struct UUAEBlackboard_GetValueAsEnum_Params
{
	struct FUAEBlackboardKeySelector                   Key;                                                      // (ConstParm, Parm, OutParm, ReferenceParm)
	unsigned char                                      ReturnValue;                                              // (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData)
};

// Function UAESharedModule.UAEBlackboard.GetValueAsClass
struct UUAEBlackboard_GetValueAsClass_Params
{
	struct FUAEBlackboardKeySelector                   Key;                                                      // (ConstParm, Parm, OutParm, ReferenceParm)
	class UClass*                                      ReturnValue;                                              // (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData)
};

// Function UAESharedModule.UAEBlackboard.GetValueAsBool
struct UUAEBlackboard_GetValueAsBool_Params
{
	struct FUAEBlackboardKeySelector                   Key;                                                      // (ConstParm, Parm, OutParm, ReferenceParm)
	bool                                               ReturnValue;                                              // (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData)
};

}

