// PlayerUnknown's Battlegrounds (0.26.0) SDK Generated By @IDRAGONCHEATS
#include "../SDK.hpp"

namespace SDK
{
//---------------------------------------------------------------------------
//Functions
//---------------------------------------------------------------------------

// Function bp_connection_waiting.bp_connection_waiting_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void Abp_connection_waiting_C::UserConstructionScript()
{
	static UFunction *pFunc = 0;
	if (!pFunc)
		pFunc = UObject::FindObject<UFunction>("Function bp_connection_waiting.bp_connection_waiting_C.UserConstructionScript");

	Abp_connection_waiting_C_UserConstructionScript_Params params;

	auto flags = pFunc->FunctionFlags;

	UObject *currentObj = (UObject *) this;
	currentObj->ProcessEvent(pFunc, &params);

	pFunc->FunctionFlags = flags;
}

}

