#pragma once

// PlayerUnknown's Battlegrounds (0.27.0) SDK Generated By @IDRAGONCHEATS
namespace SDK
{
//---------------------------------------------------------------------------
//Script Structs
//---------------------------------------------------------------------------

// UserDefinedStruct BP_STRUCT_OBTeamResult.BP_STRUCT_OBTeamResult
// 0x000C
struct FBP_STRUCT_OBTeamResult
{
	TArray<struct FBP_STRUCT_OBPersonalResult>         BP_ARRAY_OBPersonalResult_0_7F9CABC03957F2F90AA3A37D04560A14;// 0x0000(0x000C) (Edit, BlueprintVisible, ZeroConstructor)
};

}

