#pragma once

// PlayerUnknown's Battlegrounds (0.27.0) SDK Generated By @IDRAGONCHEATS
namespace SDK
{
//---------------------------------------------------------------------------
//Script Structs
//---------------------------------------------------------------------------

// UserDefinedStruct BP_STRUCT_AvatarChange.BP_STRUCT_AvatarChange
// 0x0010
struct FBP_STRUCT_AvatarChange
{
	struct FString                                     gid_0_0068A02D4FB8507FACCE29A6D83352E4;                   // 0x0000(0x000C) (Edit, BlueprintVisible, ZeroConstructor)
	int                                                resId_1_B16CC58E4E3009EDA5FFDF966711B5CB;                 // 0x000C(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
};

}

