#pragma once

// PlayerUnknown's Battlegrounds (0.27.0) SDK Generated By @IDRAGONCHEATS
namespace SDK
{
//---------------------------------------------------------------------------
//Classes
//---------------------------------------------------------------------------

// ScriptBlueprintGeneratedClass bp_room.bp_room_C
// 0x0148 (0x0448 - 0x0300)
class Abp_room_C : public ALuaClassObj
{
public:
	class UScriptContextComponent*                     Generated_ScriptContext;                                  // 0x0300(0x0004) (BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData)
	bool                                               BP_CreateRoom_Adv_Hot_Point_IsShow;                       // 0x0304(0x0001) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	unsigned char                                      UnknownData00[0x3];                                       // 0x0305(0x0003) MISSED OFFSET
	struct FString                                     BP_EnterRoom_Passwd;                                      // 0x0308(0x000C) (Edit, BlueprintVisible, ZeroConstructor)
	struct FString                                     BP_Room_SelfName;                                         // 0x0314(0x000C) (Edit, BlueprintVisible, ZeroConstructor)
	bool                                               BP_Room_IsAnchor;                                         // 0x0320(0x0001) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	unsigned char                                      UnknownData01[0x3];                                       // 0x0321(0x0003) MISSED OFFSET
	struct FString                                     BP_Room_CardInfo_Highlevel;                               // 0x0324(0x000C) (Edit, BlueprintVisible, ZeroConstructor)
	struct FBP_STRUCT_RoomInfo                         BP_STRUCT_RoomInfo;                                       // 0x0330(0x0074) (Edit, BlueprintVisible)
	int                                                BP_Zone_Id_In_Room;                                       // 0x03A4(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	bool                                               BP_Room_IsHighLevelRoom;                                  // 0x03A8(0x0001) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	unsigned char                                      UnknownData02[0x3];                                       // 0x03A9(0x0003) MISSED OFFSET
	struct FBP_STRUCT_GroupType                        BP_STRUCT_GroupType;                                      // 0x03AC(0x0010) (Edit, BlueprintVisible)
	int                                                BP_Room_Map_Select;                                       // 0x03BC(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	struct FString                                     BP_Room_CardInfo_Match;                                   // 0x03C0(0x000C) (Edit, BlueprintVisible, ZeroConstructor)
	TArray<struct FBP_STRUCT_GroupType>                BP_ARRAY_GroupTypeList;                                   // 0x03CC(0x000C) (Edit, BlueprintVisible, ZeroConstructor)
	int                                                LastRequestJoinRoomTime;                                  // 0x03D8(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	int                                                BP_EnterRoom_Type;                                        // 0x03DC(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	bool                                               BP_Room_IsCompetitionRoom;                                // 0x03E0(0x0001) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	unsigned char                                      UnknownData03[0x3];                                       // 0x03E1(0x0003) MISSED OFFSET
	struct FString                                     BP_Room_CardInfo_Normal;                                  // 0x03E4(0x000C) (Edit, BlueprintVisible, ZeroConstructor)
	bool                                               BP_Room_CardInfo_HighlevelIsTime;                         // 0x03F0(0x0001) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	unsigned char                                      UnknownData04[0x3];                                       // 0x03F1(0x0003) MISSED OFFSET
	TArray<int>                                        BP_ARRAY_ZoneListInRoom;                                  // 0x03F4(0x000C) (Edit, BlueprintVisible, ZeroConstructor)
	bool                                               BP_CreateRoom_Hot_Point_IsShow;                           // 0x0400(0x0001) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	unsigned char                                      UnknownData05[0x3];                                       // 0x0401(0x0003) MISSED OFFSET
	struct FString                                     BP_EnterRoom_ID;                                          // 0x0404(0x000C) (Edit, BlueprintVisible, ZeroConstructor)
	struct FString                                     BP_Room_ClientVersion;                                    // 0x0410(0x000C) (Edit, BlueprintVisible, ZeroConstructor)
	int                                                BP_SelectRoomID;                                          // 0x041C(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	bool                                               BP_Room_CardInfo_NormalIsTime;                            // 0x0420(0x0001) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	unsigned char                                      UnknownData06[0x3];                                       // 0x0421(0x0003) MISSED OFFSET
	TArray<struct FBP_STRUCT_RoomInfo>                 BP_ARRAY_RoomList;                                        // 0x0424(0x000C) (Edit, BlueprintVisible, ZeroConstructor)
	int                                                BP_Room_RefreshLeftTime;                                  // 0x0430(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	struct FString                                     BP_Room_CardInfo;                                         // 0x0434(0x000C) (Edit, BlueprintVisible, ZeroConstructor)
	bool                                               BP_Room_IsCurListNormalRoom;                              // 0x0440(0x0001) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	unsigned char                                      UnknownData07[0x3];                                       // 0x0441(0x0003) MISSED OFFSET
	class USceneComponent*                             DefaultSceneRoot;                                         // 0x0444(0x0004) (BlueprintVisible, ZeroConstructor, IsPlainOldData)

	static UClass* StaticClass()
	{
		static UClass *pStaticClass = 0;
		if (!pStaticClass)
			 pStaticClass = UObject::FindClass("ScriptBlueprintGeneratedClass bp_room.bp_room_C");
		return pStaticClass;
	}


	void EventOpenRoomChatUI_NoFetch();
	void EventOpenRoomChatUI();
	void EventGetZoneListInRoom_NoFetch();
	void EventGetZoneListInRoom();
	void EventGetMoreRoom_NoFetch();
	void EventGetMoreRoom();
	void EventSelectZoneInRoomList_Push_NoFetch();
	void EventSelectZoneInRoomList_Push();
	void EventShowRoomCreateUI_NoFetch();
	void EventShowRoomCreateUI();
	void EventRequestRoomList_NoFetch();
	void EventRequestRoomList();
	void EventCheckInputRoomID_NoFetch();
	void EventCheckInputRoomID();
	void EventNotAnchor_NoFetch();
	void EventNotAnchor();
	void EventAfterLeaveRoomList_NoFetch();
	void EventAfterLeaveRoomList();
	void EventRoomListChangeMap_NoFetch();
	void EventRoomListChangeMap();
	void EventRequestJoinRoom_NoFetch();
	void EventRequestJoinRoom();
	void EventCloseRoomChatUI_NoFetch();
	void EventCloseRoomChatUI();
	void EventCompareClickRefreshTime_NoFetch();
	void EventCompareClickRefreshTime();
	void EventEnterGamingRoomNotice_NoFetch();
	void EventEnterGamingRoomNotice();
	void EventFetchInfo_NoFetch();
	void EventFetchInfo();
	void EventRefreshRoomCardInfo_NoFetch();
	void EventRefreshRoomCardInfo();
	void EventVersionNotMatched_NoFetch();
	void EventVersionNotMatched();
	void EventAfterEnterRoomList_NoFetch();
	void EventAfterEnterRoomList();
	void EventRoomRelease_NoFetch();
	void EventRoomRelease();
	void EventEnterRoom_NoFetch();
	void EventEnterRoom();
	void UserConstructionScript();
};


}

