std::string JSON_ITEMS = "[\n"
                         "  {\n"
                         "    \"Category\": \"Scope\",\n"
                         "    \"Items\": [\n"
                         "      {\n"
                         "        \"itemId\": 203004,\n"
                         "        \"itemClass\": \"BP_MZJ_4X_Pickup_C_1\",\n"
                         "        \"itemName\": \"4x Scope\",\n"
                         "        \"itemTextColor\": \"0xFF9FBD1C\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 203014,\n"
                         "        \"itemClass\": \"BP_MZJ_3X_Pickup_C_1\",\n"
                         "        \"itemName\": \"3x Scope\",\n"
                         "        \"itemTextColor\": \"0xFF9FBD1C\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      }\n"
                         "    ]\n"
                         "  },\n"
                         "  {\n"
                         "    \"Category\": \"Ammo\",\n"
                         "    \"Items\": [\n"
                         "      {\n"
                         "        \"itemId\": 204011,\n"
                         "        \"itemClass\": \"BP_Extended_QuickDraw_Mag_AR\",\n"
                         "        \"itemName\": \"Extended Quickdraw Mag (AR)\",\n"
                         "        \"itemTextColor\": \"0xFF9FBD1C\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 204013,\n"
                         "        \"itemClass\": \"BP_Extended_QuickDraw_Mag_AR\",\n"
                         "        \"itemName\": \"Extended Quickdraw Mag (AR)\",\n"
                         "        \"itemTextColor\": \"0xFF9FBD1C\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      }\n"
                         "    ]\n"
                         "  }\n"
                         "]";
// 6x Scope and Bag entries are intentionally left out - no confirmed item ID exists for
// them anywhere in this project, and 3x/4x don't follow a pattern that could be safely
// extrapolated. The 204011/204013 AR mag IDs above are confirmed working (same IDs the
// unlimited-ammo mag-reattach feature uses). Everything else in the loot ESP filter
// (guns, other ammo, meds, drinks, level-3 gear) is matched by name/category text read
// directly off the pickup actor - see IsWantedLootItem in main.cpp.
