std::string JSON_ITEMS = "[\n"
                         "  {\n"
                         "    \"Category\": \"Rifle\",\n"
                         "    \"Items\": [\n"
                         "      {\n"
                         "        \"itemId\": 101001,\n"
                         "        \"itemClass\": \"BP_Rifle_AKM_Wrapper_C_1\",\n"
                         "        \"itemName\": \"AKM\",\n"
                         "        \"itemTextColor\": \"0xFFFCC89D\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 101002,\n"
                         "        \"itemClass\": \"BP_Rifle_M16A4_Wrapper_C_1\",\n"
                         "        \"itemName\": \"M16A4\",\n"
                         "        \"itemTextColor\": \"0xFF4DFF76\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 303001,\n"
                         "        \"itemClass\": \"BP_Ammo_556mm_Pickup_C_1\",\n"
                         "        \"itemName\": \"5.56mm\",\n"
                         "        \"itemTextColor\": \"0xFF4DFF76\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"                                                 
                         "        \"itemId\": 101003,\n"
                         "        \"itemClass\": \"BP_Rifle_SCAR_Wrapper_C_1\",\n"
                         "        \"itemName\": \"SCAR-L\",\n"
                         "        \"itemTextColor\": \"0xFFD1EEEE\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 204011,\n"
                         "        \"itemClass\": \"BP_DJ_Large_E_Pickup_C_1\",\n"
                         "        \"itemName\": \"Extended Quickdraw Mag (AR)\",\n"
                         "        \"itemTextColor\": \"0xFFFF0000\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"                         
                         "        \"itemId\": 204013,\n"
                         "        \"itemClass\": \"BP_DJ_Large_EQ_Pickup_C_1\",\n"
                         "        \"itemName\": \"Extended Quickdraw Mag (AR)\",\n"
                         "        \"itemTextColor\": \"0xFFFF0000\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"                         
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 101004,\n"
                         "        \"itemClass\": \"BP_Rifle_M416_Wrapper_C_1\",\n"
                         "        \"itemName\": \"M416\",\n"
                         "        \"itemTextColor\": \"0xFFD1EEEE\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 101010,\n"
                         "        \"itemClass\": \"BP_Rifle_G36_Wrapper_C_1\",\n"
                         "        \"itemName\": \"G36C\",\n"
                         "        \"itemTextColor\": \"0xFFFF0000\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 203004,\n"
                         "        \"itemClass\": \"BP_MZJ_4X_Pickup_C_1\",\n"
                         "        \"itemName\": \"4x Scope\",\n"
                         "        \"itemTextColor\": \"0xFF9FBD1C\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 203014,\n"
                         "        \"itemClass\": \"BP_MZJ_3X_Pickup_C_1\",\n"
                         "        \"itemName\": \"3x Scope\",\n"
                         "        \"itemTextColor\": \"0xFF9FBD1C\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 601005,\n"
                         "        \"itemClass\": \"Firstaid_Pickup_C_1\",\n"
                         "        \"itemName\": \"First Aid Kit\",\n"
                         "        \"itemTextColor\": \"0xFF4DFF76\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      }\n"
                         "    ]\n"
                         "  }\n"
                         "]";